# Generated by Django 6.1.1 on 2026-09-13 13:21

import _utils.file_upload
import django.contrib.postgres.indexes
import django.db.models.deletion
import docs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval', '0002_initial'),
        ('company', '0001_initial'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(blank=True, choices=[('1', '일반문서'), ('2', '소송기록')], max_length=1, null=True, verbose_name='유형')),
                ('color', models.CharField(blank=True, max_length=21, null=True, verbose_name='색상')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='이름')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬 순서')),
                ('active', models.BooleanField(default=True, verbose_name='사용중')),
                ('default', models.BooleanField(default=False, verbose_name='기본값')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.category', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '01. 카테고리',
                'verbose_name_plural': '01. 카테고리',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='휴지통')),
                ('doc_type', models.CharField(blank=True, choices=[('1', '일반문서'), ('2', '소송기록')], max_length=1, null=True, verbose_name='유형')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='제목')),
                ('execution_date', models.DateField(blank=True, help_text='문서 발신/수신/시행일자', null=True, verbose_name='문서 시행일자')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='설명')),
                ('hit', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='아이피')),
                ('device', models.CharField(blank=True, default='', max_length=255, verbose_name='등록기기')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('security_level', models.CharField(choices=[('1', '1등급 비공개 (작성자/허가자)'), ('2', '2등급 팀 공개 (소속 부서)'), ('3', '3등급 프로젝트 공개 (워크스페이스 멤버)'), ('4', '4등급 전사 공개')], db_index=True, default='3', help_text='1:비공개 / 2:팀공개 / 3:프로젝트공개 / 4:전사공개', max_length=1, verbose_name='보안 등급')),
                ('is_blind', models.BooleanField(default=False, verbose_name='숨김')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='보안 등급과 무관하게 열람을 허가할 사용자', related_name='granted_documents', to=settings.AUTH_USER_MODEL, verbose_name='개별 열람 허가자')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.category', verbose_name='카테고리')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('issue_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.issueproject', verbose_name='업무 프로젝트')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL, verbose_name='편집자')),
            ],
            options={
                'verbose_name': '02. 문서',
                'verbose_name_plural': '02. 문서',
                'ordering': ['-is_pinned', '-created'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=_utils.file_upload.get_docs_file_path, verbose_name='파일')),
                ('file_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='파일명')),
                ('file_type', models.CharField(blank=True, max_length=80, verbose_name='타입')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='사이즈')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='부가설명')),
                ('hit', models.PositiveIntegerField(default=0, verbose_name='다운로드수')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('docs', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='docs.document', verbose_name='문서')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=_utils.file_upload.get_docs_image_path, verbose_name='이미지')),
                ('image_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='파일명')),
                ('image_type', models.CharField(blank=True, max_length=30, verbose_name='타입')),
                ('image_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='사이즈')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('docs', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='docs.document', verbose_name='문서')),
            ],
        ),
        migrations.CreateModel(
            name='LawsuitCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('1', '민사'), ('2', '형사'), ('3', '행정'), ('4', '신청'), ('5', '집행')], max_length=1, verbose_name='유형')),
                ('level', models.CharField(blank=True, choices=[('1', '1심'), ('2', '2심'), ('3', '3심'), ('4', '고소/수사'), ('5', '신청'), ('6', '항고/이의'), ('7', '압류/추심'), ('8', '정지/이의')], max_length=1, verbose_name='심급')),
                ('court', models.CharField(blank=True, choices=[('000100', '대법원'), ('000200', '서울고등법원'), ('000201', '서울고등법원(춘천재판부)'), ('000202', '서울고등법원(인천재판부)'), ('000600', '대전고등법원'), ('000601', '대전고등법원(청주재판부)'), ('000300', '대구고등법원'), ('000400', '부산고등법원'), ('000401', '부산고등법원(창원재판부)'), ('000402', '부산고등법원(울산재판부)'), ('000500', '광주고등법원'), ('000501', '광주고등법원(제주재판부)'), ('000502', '광주고등법원(전주재판부)'), ('000800', '수원고등법원'), ('000700', '특허법원'), ('000230', '서울가정법원'), ('000220', '서울행정법원'), ('000221', '서울회생법원'), ('-', '------------'), ('000210', '서울중앙지방법원'), ('000211', '서울동부지방법원'), ('000212', '서울남부지방법원'), ('000213', '서울북부지방법원'), ('000215', '서울서부지방법원'), ('-', '------------'), ('000214', '의정부지방법원'), ('214807', '고양지원'), ('214801', '파주시법원'), ('214802', '포천시법원'), ('214804', '남양주시법원'), ('214808', '동두천시법원'), ('214803', '가평군법원'), ('214805', '연천군법원'), ('214806', '철원군법원'), ('-', '------------'), ('000240', '인천지방법원'), ('000241', '인천지방법원 부천지원'), ('240812', '김포시법원'), ('240811', '강화군법원'), ('000228', '인천가정법원'), ('000229', '인천가정법원 부천지원'), ('-', '------------'), ('000250', '수원지방법원'), ('000251', '성남지원'), ('000252', '여주지원'), ('000253', '평택지원'), ('250826', '안산지원'), ('000254', '안양지원'), ('250823', '용인시법원'), ('250824', '오산시법원'), ('250825', '광명시법원'), ('250821', '안성시법원'), ('251827', '광주시법원'), ('252828', '양평군법원'), ('252829', '이천시법원'), ('000302', '수원가정법원'), ('000303', '수원가정법원 성남지원'), ('000304', '수원가정법원 여주지원'), ('000305', '수원가정법원 평택지원'), ('000322', '수원가정법원 안산지원'), ('000306', '수원가정법원 안양지원'), ('-', '------------'), ('000260', '춘천지방법원'), ('000261', '강릉지원'), ('000262', '원주지원'), ('000263', '속초지원'), ('000264', '영월지원'), ('260842', '홍천군법원'), ('260843', '양구군법원'), ('261845', '삼척시법원'), ('261846', '동해시법원'), ('264851', '정선군법원'), ('264853', '평창군법원'), ('264852', '태백시법원'), ('262847', '횡성군법원'), ('260841', '인제군법원'), ('260844', '화천군법원'), ('263848', '고성군법원'), ('263849', '양양군법원'), ('-', '------------'), ('000280', '대전지방법원'), ('000281', '대전지방법원 홍성지원'), ('000284', '대전지방법원 공주지원'), ('000282', '대전지방법원 논산지원'), ('000285', '대전지방법원 서산지원'), ('000283', '대전지방법원 천안지원'), ('280872', '금산군법원'), ('280871', '세종특별자치시법원'), ('281874', '보령시법원'), ('281873', '서천군법원'), ('281875', '예산군법원'), ('283877', '아산시법원'), ('285879', '태안군법원'), ('285881', '당진시법원'), ('282876', '부여군법원'), ('284878', '청양군법원'), ('000286', '대전가정법원'), ('000292', '대전가정법원 홍성지원'), ('000295', '대전가정법원 공주지원'), ('000293', '대전가정법원 논산지원'), ('000296', '대전가정법원 서산지원'), ('000294', '대전가정법원 천안지원'), ('-', '------------'), ('000270', '청주지방법원'), ('000271', '충주지원'), ('000272', '제천지원'), ('000273', '영동지원'), ('270863', '진천군법원'), ('270861', '보은군법원'), ('272865', '단양군법원'), ('271864', '음성군법원'), ('273866', '옥천군법원'), ('270862', '괴산군법원'), ('-', '------------'), ('000310', '대구지방법원'), ('000320', '대구지방법원 서부지원'), ('000311', '대구지방법원 안동지원'), ('000312', '대구지방법원 경주지원'), ('000317', '대구지방법원 포항지원'), ('000313', '대구지방법원 김천지원'), ('000314', '대구지방법원 상주지원'), ('000315', '대구지방법원 의성지원'), ('000316', '대구지방법원 영덕지원'), ('310895', '경산시법원'), ('310893', '칠곡군법원'), ('310891', '청도군법원'), ('310892', '영천시법원'), ('310894', '성주군법원'), ('310896', '고령군법원'), ('311897', '영주시법원'), ('311898', '봉화군법원'), ('313901', '구미시법원'), ('314903', '문경시법원'), ('314902', '예천군법원'), ('315904', '청송군법원'), ('315905', '군위군법원'), ('316906', '울진군법원'), ('316907', '영양군법원'), ('000318', '대구가정법원'), ('000399', '대구가정법원 안동지원'), ('000390', '대구가정법원 경주지원'), ('000395', '대구가정법원 포항지원'), ('000391', '대구가정법원 김천지원'), ('000392', '대구가정법원 상주지원'), ('000393', '대구가정법원 의성지원'), ('000394', '대구가정법원 영덕지원'), ('-', '------------'), ('000410', '부산지방법원'), ('000412', '부산지방법원 동부지원'), ('000414', '부산지방법원 서부지원'), ('000413', '부산가정법원'), ('-', '------------'), ('000411', '울산지방법원'), ('411911', '양산시법원'), ('000477', '울산가정법원'), ('-', '------------'), ('000420', '창원지방법원'), ('000431', '마산지원'), ('000421', '진주지원'), ('000422', '통영지원'), ('000423', '밀양지원'), ('000424', '거창지원'), ('420922', '창원남부시법원'), ('420923', '김해시법원'), ('420921', '함안군법원'), ('420924', '의령군법원'), ('421927', '사천시법원'), ('421928', '남해군법원'), ('421926', '하동군법원'), ('422931', '거제시법원'), ('422932', '고성군법원(경)'), ('423933', '창녕군법원'), ('424934', '합천군법원'), ('424935', '함양군법원'), ('421929', '산청군법원'), ('-', '------------'), ('000510', '광주지방법원'), ('000511', '광주지방법원 목포지원'), ('000512', '광주지방법원 장흥지원'), ('000513', '광주지방법원 순천지원'), ('000514', '광주지방법원 해남지원'), ('510946', '담양군법원'), ('511947', '함평군법원'), ('512951', '강진군법원'), ('513955', '구례군법원'), ('510942', '영광군법원'), ('510943', '나주시법원'), ('510944', '장성군법원'), ('510945', '화순군법원'), ('510941', '곡성군법원'), ('513956', '광양시법원'), ('513953', '고흥군법원'), ('513954', '여수시법원'), ('513952', '보성군법원'), ('511949', '무안군법원'), ('511948', '영암군법원'), ('514958', '완도군법원'), ('514959', '진도군법원'), ('000515', '광주가정법원'), ('000599', '광주가정법원 목포지원'), ('000590', '광주가정법원 장흥지원'), ('000591', '광주가정법원 순천지원'), ('000592', '광주가정법원 해남지원'), ('-', '------------'), ('000520', '전주지방법원'), ('000521', '군산지원'), ('000522', '정읍지원'), ('000523', '남원지원'), ('520971', '진안군법원'), ('520972', '김제시법원'), ('520973', '무주군법원'), ('520974', '임실군법원'), ('521975', '익산시법원'), ('522976', '부안군법원'), ('522977', '고창군법원'), ('523978', '장수군법원'), ('523979', '순창군법원'), ('-', '------------'), ('000530', '제주지방법원'), ('530991', '서귀포시법원'), ('-', '------------'), ('000110', '법원행정처')], default='', max_length=10, verbose_name='법원명')),
                ('other_agency', models.CharField(blank=True, default='', help_text='사건 유형이 기소 전 형사 사건인 경우 해당 수사기관을 기재', max_length=30, verbose_name='기타 처리기관')),
                ('case_number', models.CharField(max_length=20, verbose_name='사건번호')),
                ('case_name', models.CharField(db_index=True, max_length=30, verbose_name='사건명')),
                ('plaintiff', models.CharField(blank=True, default='', max_length=30, verbose_name='원고(신청인)')),
                ('plaintiff_attorney', models.CharField(blank=True, default='', max_length=50, verbose_name='원고 대리인')),
                ('plaintiff_case_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='원고 소가')),
                ('defendant', models.CharField(max_length=30, verbose_name='피고(피신청인)')),
                ('defendant_attorney', models.CharField(blank=True, default='', max_length=50, verbose_name='피고 대리인')),
                ('defendant_case_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='피고 소가')),
                ('related_debtor', models.CharField(blank=True, default='', max_length=30, verbose_name='제3채무자')),
                ('case_start_date', models.DateField(verbose_name='사건개시일')),
                ('case_end_date', models.DateField(blank=True, null=True, verbose_name='사건종결일')),
                ('summary', models.TextField(blank=True, default='', verbose_name='개요 및 경과')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawsuitcases', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('issue_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.issueproject', verbose_name='업무 프로젝트')),
                ('related_case', models.ForeignKey(blank=True, help_text='본안 사건인 경우 원심 사건, 신청/집행 사건인 경우 관련 본안 사건 지정', null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.lawsuitcase', verbose_name='관련사건')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lawsuitcases', to=settings.AUTH_USER_MODEL, verbose_name='편집자')),
            ],
            options={
                'verbose_name': '03. 소송사건',
                'verbose_name_plural': '03. 소송사건',
                'ordering': ['-case_start_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='lawsuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.lawsuitcase', verbose_name='사건번호'),
        ),
        migrations.CreateModel(
            name='LetterSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='연도')),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='마지막 번호')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_sequences', to='company.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '05. 공문 번호 시퀀스',
                'verbose_name_plural': '05. 공문 번호 시퀀스',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500, verbose_name='링크')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='부가설명')),
                ('hit', models.PositiveIntegerField(default=0, verbose_name='클릭수')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('creator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('docs', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='docs.document', verbose_name='문서')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='문서번호')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='수신처명')),
                ('via', models.CharField(blank=True, default='', help_text='최종 수신처로 가기 전 거치는 중간 기관 또는 부서', max_length=100, verbose_name='경유')),
                ('recipient_reference', models.CharField(blank=True, default='', help_text='참조인 또는 부서', max_length=100, verbose_name='참조')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('sender_display_type', models.CharField(choices=[('company_only', '회사명만 표기 (주식회사 OOO)'), ('company_rep', '회사명 + 대표직함 및 성명 표기 (주식회사 OOO 대표이사 홍길동)'), ('co_rep', '공동대표 병기 (공동대표이사 A & B 나란히 날인)')], default='company_only', help_text='공문서 하단 중앙 발신 명의 및 인장 날인 형태 선택', max_length=20, verbose_name='발신 명의 표기 방식')),
                ('sender_duty_title', models.CharField(blank=True, default='', help_text='예: 대표이사, 본부장, 현장소장 (단독/직접 발송 시 지정, 미지정 시 결재선/기본값 자동 산출)', max_length=20, verbose_name='발신 명의 표기 직책')),
                ('sender_name', models.CharField(blank=True, default='', help_text='예: 유용식, 고창균 (단독/직접 발송 시 지정, 미지정 시 결재선/기본값 자동 산출)', max_length=30, verbose_name='발신 명의 표기 성명')),
                ('issue_date', models.DateField(help_text='기안자가 희망하는 발신 예정일/요청일. 실제 공문서 시행일자는 최종 결재 승인일(또는 발송 완료일)로 자동 확정됩니다.', verbose_name='발신 요청일(예정일)')),
                ('sender_zipcode', models.CharField(blank=True, default='', max_length=5, verbose_name='발신 우편번호')),
                ('sender_address', models.CharField(blank=True, default='', max_length=255, verbose_name='발신 주소')),
                ('drafter_name', models.CharField(max_length=50, verbose_name='기안/담당자명')),
                ('drafter_position', models.CharField(blank=True, default='', max_length=50, verbose_name='기안/담당 직위')),
                ('is_solo_approval', models.BooleanField(default=False, help_text='대표이사, 현장소장, 본부장 등 최종 승인(전결)권자가 직접 기안하여 공문서 하단 담당자란을 생략하고 단독 결재로 처리하는 경우', verbose_name='승인(전결)권자 직접 기안 (담당 생략)')),
                ('recipient_address', models.CharField(blank=True, default='', max_length=255, verbose_name='수신처 주소')),
                ('recipient_contact', models.CharField(blank=True, default='', max_length=50, verbose_name='수신처 연락처')),
                ('attachment_text', models.TextField(blank=True, default='', help_text='직접 텍스트로 붙임 목록을 기입할 경우 사용', verbose_name='붙임 텍스트')),
                ('disclosure_type', models.CharField(choices=[('1', '공개'), ('2', '부분공개'), ('3', '비공개')], default='1', help_text='1: 공개, 2: 부분공개, 3: 비공개(영업비밀/대외비)', max_length=1, verbose_name='공개 구분')),
                ('dispatch_method', models.CharField(choices=[('email', '이메일'), ('registered_mail', '등기우편'), ('direct', '인편/직접교부'), ('courier', '퀵/택배'), ('fax', '팩스'), ('etc', '기타')], default='email', max_length=20, verbose_name='발송 방법')),
                ('tracking_number', models.CharField(blank=True, default='', help_text='등기우편 번호, 송장번호, 팩스 확인번호 등', max_length=50, verbose_name='등기/송장 번호')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 완료일시')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=_utils.file_upload.get_letter_pdf_path, verbose_name='PDF 파일')),
                ('approval_status', models.CharField(choices=[('none', '미상신'), ('pending', '결재진행중'), ('approved', '결재승인'), ('rejected', '반려')], db_index=True, default='none', max_length=10, verbose_name='결재 상태')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('approval_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_letters', to='approval.approvaldocument', verbose_name='연동 전자결재 문서')),
                ('co_seal', models.ForeignKey(blank=True, help_text='공동대표 체제 시 두 번째 대표이사의 날인 인감', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_official_letters', to='company.companyseal', verbose_name='공동대표 보조 인감')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_letters', to='company.company', verbose_name='회사')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_letters', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_letters', to='company.companyseal', verbose_name='날인 인감')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_letters', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '06. 공문',
                'verbose_name_plural': '06. 공문',
                'ordering': ['-issue_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='OfficialLetterAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=docs.models.get_letter_attachment_path, verbose_name='첨부파일')),
                ('name', models.CharField(blank=True, default='', help_text='공문에 표기될 명칭 (미입력 시 파일명 사용)', max_length=255, verbose_name='붙임 명칭')),
                ('quantity', models.CharField(blank=True, default='1부', help_text='예: 1부, 2부, 1식 등', max_length=50, verbose_name='수량/부수')),
                ('ordering', models.PositiveSmallIntegerField(default=1, verbose_name='표시 순서')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='docs.officialletter', verbose_name='공문')),
            ],
            options={
                'verbose_name': '07. 공문 첨부파일',
                'verbose_name_plural': '07. 공문 첨부파일',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='docs_document_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='docs_document_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AlterUniqueTogether(
            name='lettersequence',
            unique_together={('company', 'year')},
        ),
    ]
