# Generated by Django 6.0.7 on 2026-07-11 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('docs', '0001_initial'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='issue_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.issueproject', verbose_name='업무 프로젝트'),
        ),
        migrations.AddField(
            model_name='document',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddField(
            model_name='file',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='file',
            name='docs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='docs.document', verbose_name='문서'),
        ),
        migrations.AddField(
            model_name='image',
            name='docs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='docs.document', verbose_name='문서'),
        ),
        migrations.AddField(
            model_name='lawsuitcase',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawsuitcases', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='lawsuitcase',
            name='issue_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.issueproject', verbose_name='업무 프로젝트'),
        ),
        migrations.AddField(
            model_name='lawsuitcase',
            name='related_case',
            field=models.ForeignKey(blank=True, help_text='본안 사건인 경우 원심 사건, 신청/집행 사건인 경우 관련 본안 사건 지정', null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.lawsuitcase', verbose_name='관련사건'),
        ),
        migrations.AddField(
            model_name='lawsuitcase',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_lawsuitcases', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddField(
            model_name='document',
            name='lawsuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.lawsuitcase', verbose_name='사건번호'),
        ),
        migrations.AddField(
            model_name='lettersequence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_sequences', to='company.company', verbose_name='회사'),
        ),
        migrations.AddField(
            model_name='link',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='link',
            name='docs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='docs.document', verbose_name='문서'),
        ),
        migrations.AddField(
            model_name='officialletter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_letters', to='company.company', verbose_name='회사'),
        ),
        migrations.AddField(
            model_name='officialletter',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_letters', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='officialletter',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_letters', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AlterUniqueTogether(
            name='lettersequence',
            unique_together={('company', 'year')},
        ),
    ]
