# Generated by Django 6.0.1 on 2026-01-15 17:06

import django.db.models.deletion
import docs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('docs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True, verbose_name='문서번호')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='제목')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='수신처명')),
                ('recipient_address', models.CharField(blank=True, default='', max_length=255, verbose_name='수신처 주소')),
                ('recipient_contact', models.CharField(blank=True, default='', max_length=50, verbose_name='수신처 연락처')),
                ('recipient_reference', models.CharField(blank=True, default='', help_text='참조인 또는 부서', max_length=100, verbose_name='참조')),
                ('sender_name', models.CharField(max_length=50, verbose_name='발신자명')),
                ('sender_position', models.CharField(blank=True, default='', max_length=50, verbose_name='발신자 직위')),
                ('sender_department', models.CharField(blank=True, default='', max_length=50, verbose_name='발신 부서')),
                ('content', models.TextField(verbose_name='내용')),
                ('issue_date', models.DateField(verbose_name='발신일자')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=docs.models.get_letter_pdf_path, verbose_name='PDF 파일')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_letters', to='company.company', verbose_name='회사')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_letters', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_letters', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '06. 공문',
                'verbose_name_plural': '06. 공문',
                'ordering': ['-issue_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='LetterSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='연도')),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='마지막 번호')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_sequences', to='company.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '05. 공문 번호 시퀀스',
                'verbose_name_plural': '05. 공문 번호 시퀀스',
                'ordering': ['-year'],
                'unique_together': {('company', 'year')},
            },
        ),
    ]
