# Generated by Django 6.1.1 on 2026-09-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialletter',
            name='approval_mode',
            field=models.CharField(choices=[('approval', '전자결재 상신 발송'), ('manual', '단독 / 직접 발송')], db_index=True, default='approval', help_text='approval: 사내 전자결재 품의 연동, manual: 전자결재 생략 단독/직접 발송', max_length=10, verbose_name='발송 결재 방식'),
        ),
    ]
