# Generated by Django 6.1 on 2026-08-25 14:26

from django.conf import settings
from django.db import migrations, models


def migrate_is_secret_to_security_level(apps, schema_editor):
    """
    기존 is_secret=True 문서를 security_level='1'(비공개)로 이관.
    is_secret=False(기본값) → security_level='3'(프로젝트 공개, 신규 기본값과 동일).
    """
    Document = apps.get_model('docs', 'Document')
    # is_secret=True인 문서만 PRIVATE(1등급)으로 설정 (나머지는 default='3' 적용)
    # 주의: apps.get_model()은 커스텀 매니저를 포함하지 않으므로 objects 사용
    Document.objects.filter(is_secret=True).update(security_level='1')


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1단계: security_level 필드 추가 (default='3')
        migrations.AddField(
            model_name='document',
            name='security_level',
            field=models.CharField(choices=[('1', '1등급 비공개 (작성자/허가자)'), ('2', '2등급 팀 공개 (소속 부서)'), ('3', '3등급 프로젝트 공개 (워크스페이스 멤버)'), ('4', '4등급 전사 공개')], db_index=True, default='3', help_text='1:비공개 / 2:팀공개 / 3:프로젝트공개 / 4:전사공개', max_length=1, verbose_name='보안 등급'),
        ),
        # 2단계: is_secret=True 데이터를 security_level='1'로 이관
        migrations.RunPython(
            migrate_is_secret_to_security_level,
            reverse_code=migrations.RunPython.noop,
        ),
        # 3단계: is_secret, password 필드 삭제
        migrations.RemoveField(
            model_name='document',
            name='is_secret',
        ),
        migrations.RemoveField(
            model_name='document',
            name='password',
        ),
        # 4단계: allowed_users M2M 테이블 생성
        migrations.AddField(
            model_name='document',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='보안 등급과 무관하게 열람을 허가할 사용자', related_name='granted_documents', to=settings.AUTH_USER_MODEL, verbose_name='개별 열람 허가자'),
        ),
    ]
