# Generated by Django 6.1 on 2026-08-22 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0010_approvalaction_delegated_from_and_more'),
        ('docs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialletter',
            name='approval_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_letters', to='approval.approvaldocument', verbose_name='연동 전자결재 문서'),
        ),
        migrations.AddField(
            model_name='officialletter',
            name='approval_status',
            field=models.CharField(choices=[('none', '미상신'), ('pending', '결재진행중'), ('approved', '결재승인'), ('rejected', '반려')], db_index=True, default='none', max_length=10, verbose_name='결재 상태'),
        ),
    ]
