# Generated by Django 6.0.6 on 2026-07-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['is_pinned', '-created'], 'verbose_name': '04. 문서', 'verbose_name_plural': '04. 문서'},
        ),
        migrations.AddField(
            model_name='document',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='상단 고정'),
        ),
    ]
