# Generated by Django 6.1.1 on 2026-09-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_officialletter_approval_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id'], 'verbose_name': '01. 카테고리', 'verbose_name_plural': '01. 카테고리'},
        ),
    ]
