# Generated by Django 6.0.6 on 2026-06-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='설명'),
        ),
    ]
