# Generated by Django 6.0.7 on 2026-07-17 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_initial'),
        ('work', '0011_alter_meeting_project_alter_member_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawsuitcase',
            name='issue_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.issueproject', verbose_name='업무 프로젝트'),
        ),
    ]
