# Generated by Django 6.0.6 on 2026-06-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_document_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='content',
            new_name='description',
        ),
    ]
