# Generated by Django 6.1.1 on 2026-09-16 15:53

import django.db.models.deletion
import django.utils.timezone
import docs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_initial'),
        ('company', '0001_initial'),
        ('docs', '0003_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, db_index=True, help_text='미입력 시 [회사약칭]-접수-YYYY-NNN 자동 발번', max_length=50, unique=True, verbose_name='사내 접수번호')),
                ('document_number', models.CharField(db_index=True, help_text='발신 기관/업체에서 부여한 원본 공문 문서번호', max_length=100, verbose_name='발신처 문서번호')),
                ('sender_name', models.CharField(db_index=True, max_length=100, verbose_name='발신처(기관/업체명)')),
                ('sender_contact', models.CharField(blank=True, default='', max_length=100, verbose_name='발신처 연락처/담당자')),
                ('received_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='접수일자')),
                ('reply_due_date', models.DateField(blank=True, db_index=True, help_text='대외 회신이 필요한 경우 답변 마감 기한 (D-Day 모니터링 연동)', null=True, verbose_name='회신 기한')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='수신 공문 제목')),
                ('content', models.TextField(blank=True, default='', verbose_name='주요 내용 및 요약')),
                ('scan_file', models.FileField(blank=True, help_text='접수된 원본 공문서 스캔 PDF 파일', null=True, upload_to=docs.models.get_inbound_scan_path, verbose_name='공문 원본 스캔본')),
                ('status', models.CharField(choices=[('received', '접수'), ('in_progress', '처리중'), ('replied', '회신완료'), ('closed', '종결')], db_index=True, default='received', max_length=20, verbose_name='처리 상태')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('approval_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_inbound_letters', to='approval.approvaldocument', verbose_name='연동 전자결재 품의')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_letters', to='company.company', verbose_name='회사')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inbound_letters', to=settings.AUTH_USER_MODEL, verbose_name='접수 등록자')),
                ('recipient_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inbound_letters', to='company.department', verbose_name='배부/주관 부서')),
                ('recipient_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_inbound_letters', to='company.staff', verbose_name='처리 담당자')),
                ('updator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inbound_letters', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '09. 수신 공문',
                'verbose_name_plural': '09. 수신 공문',
                'ordering': ['-received_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='InboundLetterAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=docs.models.get_inbound_attachment_path, verbose_name='첨부파일')),
                ('name', models.CharField(blank=True, default='', help_text='미입력 시 파일명 사용', max_length=255, verbose_name='첨부 명칭')),
                ('quantity', models.CharField(blank=True, default='1부', max_length=50, verbose_name='수량/부수')),
                ('ordering', models.PositiveSmallIntegerField(default=1, verbose_name='표시 순서')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='docs.inboundletter', verbose_name='수신 공문')),
            ],
            options={
                'verbose_name': '10. 수신 공문 첨부파일',
                'verbose_name_plural': '10. 수신 공문 첨부파일',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InboundSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='연도')),
                ('last_sequence', models.PositiveIntegerField(default=0, verbose_name='마지막 번호')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_sequences', to='company.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '08. 수신공문 접수번호 시퀀스',
                'verbose_name_plural': '08. 수신공문 접수번호 시퀀스',
                'ordering': ['-year'],
                'unique_together': {('company', 'year')},
            },
        ),
    ]
