# Generated by Django 6.1 on 2026-09-04 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companyseal'),
        ('docs', '0003_document_security_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialletter',
            name='seal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_letters', to='company.companyseal', verbose_name='날인 인감'),
        ),
    ]
