# Generated by Django 6.0.6 on 2026-07-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_document_options_document_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-is_pinned', '-created'], 'verbose_name': '04. 문서', 'verbose_name_plural': '04. 문서'},
        ),
    ]
