# Generated by Django 6.1 on 2026-09-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_officialletter_seal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialletter',
            name='document_number',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='문서번호'),
        ),
    ]
