# Generated by Django 6.1.1 on 2026-09-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_inboundletter_inboundletterattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialletter',
            name='parent_inbound_letter',
            field=models.ForeignKey(blank=True, help_text='이 공문이 특정 수신 공문에 대한 회신(답신)인 경우 연결', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_letters', to='docs.inboundletter', verbose_name='회신 대상 수신공문'),
        ),
    ]
