# Generated by Django 6.0.6 on 2026-07-07 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_document_options'),
        ('work', '0003_alter_issue_expected_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': '01. 카테고리', 'verbose_name_plural': '01. 카테고리'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-is_pinned', '-created'], 'verbose_name': '02. 문서', 'verbose_name_plural': '02. 문서'},
        ),
        migrations.AddField(
            model_name='category',
            name='doc_type_new',
            field=models.CharField(blank=True, choices=[('1', '일반 업무'), ('2', '소송 업무')], max_length=1, null=True, verbose_name='유형'),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type_new',
            field=models.CharField(blank=True, choices=[('1', '일반 업무'), ('2', '소송 업무')], max_length=1, null=True, verbose_name='유형'),
        ),
        migrations.AlterField(
            model_name='category',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.doctype', verbose_name='유형1'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.doctype', verbose_name='유형1'),
        ),
        migrations.AlterField(
            model_name='document',
            name='issue_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.issueproject', verbose_name='업무 프로젝트'),
        ),
    ]
