# Generated by Django 6.1.1 on 2026-09-19 08:22

import _utils.file_upload
import docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_officialletter_parent_inbound_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundletter',
            name='scan_file',
            field=models.FileField(blank=True, help_text='접수된 원본 공문서 스캔 PDF 파일', max_length=500, null=True, upload_to=docs.models.get_inbound_scan_path, verbose_name='공문 원본 스캔본'),
        ),
        migrations.AlterField(
            model_name='inboundletterattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=docs.models.get_inbound_attachment_path, verbose_name='첨부파일'),
        ),
        migrations.AlterField(
            model_name='officialletter',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=_utils.file_upload.get_letter_pdf_path, verbose_name='PDF 파일'),
        ),
        migrations.AlterField(
            model_name='officialletterattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to=docs.models.get_letter_attachment_path, verbose_name='첨부파일'),
        ),
    ]
