# Generated by Django 6.0.6 on 2026-07-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_alter_category_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_type',
        ),
    ]
