# Generated by Django 6.1 on 2026-09-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_alter_officialletter_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialletter',
            name='via',
            field=models.CharField(blank=True, default='', help_text='최종 수신처로 가기 전 거치는 중간 기관 또는 부서', max_length=100, verbose_name='경유'),
        ),
    ]
