# Generated by Django 6.1 on 2026-09-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_officialletter_via'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialletter',
            name='sender_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='발신 주소'),
        ),
        migrations.AddField(
            model_name='officialletter',
            name='sender_zipcode',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='발신 우편번호'),
        ),
    ]
