# Generated by Django 6.0.6 on 2026-07-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_remove_category_doc_type_remove_document_doc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='doc_type_new',
            new_name='doc_type',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='doc_type_new',
            new_name='doc_type',
        ),
    ]
