# Generated by Django 6.0.6 on 2026-07-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_rename_doc_type_new_category_doc_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocType',
        ),
    ]
