# Generated by Django 6.1 on 2026-09-11 12:15

import django.db.models.deletion
import docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_officialletter_sender_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialletter',
            name='attachment_text',
            field=models.TextField(blank=True, default='', help_text='직접 텍스트로 붙임 목록을 기입할 경우 사용', verbose_name='붙임 텍스트'),
        ),
        migrations.AddField(
            model_name='officialletter',
            name='dispatch_method',
            field=models.CharField(choices=[('email', '이메일'), ('registered_mail', '등기우편'), ('direct', '인편/직접교부'), ('courier', '퀵/택배'), ('fax', '팩스'), ('etc', '기타')], default='email', max_length=20, verbose_name='발송 방법'),
        ),
        migrations.AddField(
            model_name='officialletter',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='발송 완료일시'),
        ),
        migrations.AddField(
            model_name='officialletter',
            name='tracking_number',
            field=models.CharField(blank=True, default='', help_text='등기우편 번호, 송장번호, 팩스 확인번호 등', max_length=50, verbose_name='등기/송장 번호'),
        ),
        migrations.CreateModel(
            name='OfficialLetterAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=docs.models.get_letter_attachment_path, verbose_name='첨부파일')),
                ('name', models.CharField(blank=True, default='', help_text='공문에 표기될 명칭 (미입력 시 파일명 사용)', max_length=255, verbose_name='붙임 명칭')),
                ('quantity', models.CharField(blank=True, default='1부', help_text='예: 1부, 2부, 1식 등', max_length=50, verbose_name='수량/부수')),
                ('ordering', models.PositiveSmallIntegerField(default=1, verbose_name='표시 순서')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='docs.officialletter', verbose_name='공문')),
            ],
            options={
                'verbose_name': '07. 공문 첨부파일',
                'verbose_name_plural': '07. 공문 첨부파일',
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
