# Generated by Django 6.0.6 on 2026-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_delete_doctype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('1', '일반문서'), ('2', '소송기록')], max_length=1, null=True, verbose_name='유형'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('1', '일반문서'), ('2', '소송기록')], max_length=1, null=True, verbose_name='유형'),
        ),
    ]
