# Generated by Django 6.1 on 2026-09-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_rename_sender_name_to_drafter'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialletter',
            name='disclosure_type',
            field=models.CharField(choices=[('1', '공개'), ('2', '부분공개'), ('3', '비공개')], default='1', help_text='1: 공개, 2: 부분공개, 3: 비공개(영업비밀/대외비)', max_length=1, verbose_name='공개 구분'),
        ),
        migrations.AlterField(
            model_name='officialletter',
            name='issue_date',
            field=models.DateField(help_text='기안자가 희망하는 발신 예정일/요청일. 실제 공문서 시행일자는 최종 결재 승인일(또는 발송 완료일)로 자동 확정됩니다.', verbose_name='발신 요청일(예정일)'),
        ),
    ]
