# Generated by Django 6.1 on 2026-09-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_officialletter_is_solo_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialletter',
            name='is_solo_approval',
            field=models.BooleanField(default=False, help_text='대표이사, 현장소장, 본부장 등 최종 승인(전결)권자가 직접 기안하여 공문서 하단 담당자란을 생략하고 단독 결재로 처리하는 경우', verbose_name='승인(전결)권자 직접 기안 (담당 생략)'),
        ),
    ]
