# Generated by Django 6.1.1 on 2026-09-12 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_companyseal_final_approval_duty_and_more'),
        ('docs', '0012_alter_officialletter_is_solo_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialletter',
            name='co_seal',
            field=models.ForeignKey(blank=True, help_text='공동대표 체제 시 두 번째 대표이사의 날인 인감', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_official_letters', to='company.companyseal', verbose_name='공동대표 보조 인감'),
        ),
        migrations.AddField(
            model_name='officialletter',
            name='sender_display_type',
            field=models.CharField(choices=[('company_only', '회사명만 표기 (주식회사 OOO)'), ('company_rep', '회사명 + 대표직함 및 성명 표기 (주식회사 OOO 대표이사 홍길동)'), ('co_rep', '공동대표 병기 (공동대표이사 A & B 나란히 날인)')], default='company_only', help_text='공문서 하단 중앙 발신 명의 및 인장 날인 형태 선택', max_length=20, verbose_name='발신 명의 표기 방식'),
        ),
    ]
