# Generated by Django 6.1.1 on 2026-09-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_officialletter_co_seal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialletter',
            name='sender_duty_title',
            field=models.CharField(blank=True, default='', help_text='예: 대표이사, 본부장, 현장소장 (단독/직접 발송 시 지정, 미지정 시 결재선/기본값 자동 산출)', max_length=20, verbose_name='발신 명의 표기 직책'),
        ),
        migrations.AddField(
            model_name='officialletter',
            name='sender_name',
            field=models.CharField(blank=True, default='', help_text='예: 유용식, 고창균 (단독/직접 발송 시 지정, 미지정 시 결재선/기본값 자동 산출)', max_length=30, verbose_name='발신 명의 표기 성명'),
        ),
    ]
