# Generated by Django 6.0 on 2025-12-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredSenderNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='iwinv 관리자 페이지에서 사전 등록된 발신번호', max_length=20, unique=True, verbose_name='발신번호')),
                ('label', models.CharField(blank=True, help_text='발신번호에 대한 설명 (예: 본사, 고객센터)', max_length=50, verbose_name='설명')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '02. 등록된 발신번호',
                'verbose_name_plural': '02. 등록된 발신번호',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageSendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(blank=True, max_length=100, verbose_name='조직 구분 ID')),
                ('request_no', models.CharField(blank=True, db_index=True, help_text='iwinv API 요청번호', max_length=100, verbose_name='요청번호')),
                ('message_type', models.CharField(choices=[('SMS', 'SMS'), ('LMS', 'LMS'), ('MMS', 'MMS'), ('KAKAO', '카카오 알림톡')], db_index=True, max_length=10, verbose_name='메시지 타입')),
                ('sender_number', models.CharField(db_index=True, max_length=20, verbose_name='발신번호')),
                ('title', models.CharField(blank=True, help_text='LMS 발송 시 제목', max_length=100, verbose_name='제목')),
                ('message_content', models.TextField(verbose_name='메시지 내용')),
                ('recipients', models.JSONField(help_text='발송된 전체 수신번호 배열', verbose_name='수신번호 목록')),
                ('recipient_count', models.IntegerField(db_index=True, default=0, verbose_name='수신자 수')),
                ('scheduled_send', models.BooleanField(default=False, verbose_name='예약 발송')),
                ('schedule_datetime', models.DateTimeField(blank=True, null=True, verbose_name='예약 일시')),
                ('sent_at', models.DateTimeField(db_index=True, verbose_name='발송 일시')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='프로젝트')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='발송자')),
            ],
            options={
                'verbose_name': '04. 메시지 발송 기록',
                'verbose_name_plural': '04. 메시지 발송 기록',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='템플릿 이름 (LMS 전송 시 제목으로도 사용 가능)', max_length=100, verbose_name='템플릿 제목')),
                ('message_type', models.CharField(choices=[('SMS', 'SMS'), ('LMS', 'LMS'), ('MMS', 'MMS')], db_index=True, default='SMS', max_length=10, verbose_name='메시지 타입')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('variables', models.JSONField(blank=True, default=list, help_text='템플릿에서 사용하는 변수 예: ["이름", "금액"]', verbose_name='변수 목록')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '03. 메시지 템플릿',
                'verbose_name_plural': '03. 메시지 템플릿',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesBillIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=20, verbose_name='시행자명')),
                ('host_tel', models.CharField(max_length=13, verbose_name='시행사 전화')),
                ('agency', models.CharField(blank=True, max_length=20, verbose_name='대행사명')),
                ('agency_tel', models.CharField(blank=True, max_length=13, verbose_name='대행사 전화')),
                ('bank_account1', models.CharField(max_length=20, verbose_name='수납은행[1]')),
                ('bank_number1', models.CharField(max_length=25, verbose_name='계좌번호[1]')),
                ('bank_host1', models.CharField(max_length=20, verbose_name='예금주[1]')),
                ('bank_account2', models.CharField(blank=True, max_length=20, verbose_name='수납은행[2]')),
                ('bank_number2', models.CharField(blank=True, max_length=25, verbose_name='계좌번호[2]')),
                ('bank_host2', models.CharField(blank=True, max_length=20, verbose_name='예금주[2]')),
                ('zipcode', models.CharField(max_length=5, verbose_name='우편번호')),
                ('address1', models.CharField(max_length=35, verbose_name='주소')),
                ('address2', models.CharField(blank=True, max_length=50, verbose_name='상세주소')),
                ('address3', models.CharField(blank=True, max_length=30, verbose_name='참고항목')),
                ('title', models.CharField(db_index=True, max_length=80, verbose_name='고지서 제목')),
                ('content', models.TextField(verbose_name='고지서 내용')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='최종 변경일')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('now_payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.installmentpaymentorder', verbose_name='현재 발행회차')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '01. 프로젝트 고지서 정보',
                'verbose_name_plural': '01. 프로젝트 고지서 정보',
                'ordering': ['id'],
            },
        ),
    ]
