# Generated by Django 6.1.1 on 2026-09-20 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_initial'),
        ('notice', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='이메일 제목')),
                ('content', models.TextField(verbose_name='이메일 본문 (HTML)')),
                ('sender_name', models.CharField(blank=True, default='', max_length=50, verbose_name='발신자명')),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='발신 이메일')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='총 수신자 수')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='발송 성공 건수')),
                ('fail_count', models.PositiveIntegerField(default=0, verbose_name='발송 실패 건수')),
                ('status', models.CharField(choices=[('pending', '발송 대기'), ('sending', '발송 중'), ('completed', '발송 완료'), ('failed', '발송 실패')], db_index=True, default='pending', max_length=15, verbose_name='발송 상태')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_notices', to='project.project', verbose_name='프로젝트')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='발송자')),
            ],
            options={
                'verbose_name': '05. 이메일 발송 관리',
                'verbose_name_plural': '05. 이메일 발송 관리',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=50, verbose_name='수신자명')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='수신 이메일')),
                ('unit_info', models.CharField(blank=True, default='', max_length=50, verbose_name='동호수 정보')),
                ('status', models.CharField(choices=[('pending', '대기'), ('success', '성공'), ('fail', '실패')], db_index=True, default='pending', max_length=10, verbose_name='발송 상태')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='오류/실패 사유')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송일시')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contractor', verbose_name='계약자')),
                ('email_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='notice.emailnotice', verbose_name='이메일 공지')),
            ],
            options={
                'verbose_name': '06. 이메일 발송 로그',
                'verbose_name_plural': '06. 이메일 발송 로그',
                'ordering': ['id'],
            },
        ),
    ]
