# Generated by Django 6.1.1 on 2026-09-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_add_email_notice_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='template_code',
            field=models.CharField(blank=True, help_text='카카오 알림톡 승인 템플릿 코드 (알림톡 필수)', max_length=50, verbose_name='템플릿 코드'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='message_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('LMS', 'LMS'), ('MMS', 'MMS'), ('KAKAO', '카카오 알림톡')], db_index=True, default='SMS', max_length=10, verbose_name='메시지 타입'),
        ),
    ]
