# Generated by Django 6.0.6 on 2026-07-05 04:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='은행코드')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='은행명')),
            ],
            options={
                'verbose_name': '은행 코드',
                'verbose_name_plural': '은행 코드',
            },
        ),
        migrations.CreateModel(
            name='CompanyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='자동 생성됨. 수동 입력 시 규칙 무시', max_length=50, unique=True, verbose_name='계정코드')),
                ('name', models.CharField(max_length=255, verbose_name='계정명')),
                ('description', models.CharField(blank=True, default='', help_text='계정 용도 및 사용 지침', max_length=255, verbose_name='설명')),
                ('depth', models.PositiveIntegerField(default=1, editable=False, verbose_name='계층 깊이')),
                ('category', models.CharField(choices=[('asset', '자산'), ('liability', '부채'), ('equity', '자본'), ('revenue', '수익'), ('expense', '비용'), ('transfer', '대체'), ('cancel', '취소')], help_text='회계 계정의 대분류', max_length=20, verbose_name='계정구분')),
                ('direction', models.CharField(blank=True, choices=[('deposit', '입금'), ('withdraw', '출금')], help_text='이 계정이 사용되는 기본 거래 방향 (분류 전용 계정은 비워둠)', max_length=10, null=True, verbose_name='거래방향')),
                ('is_category_only', models.BooleanField(default=False, help_text='체크 시: 이 계정은 분류 목적으로만 사용되며 직접 거래에 사용 불가. 대분류/중분류 등 상위 계정에 주로 사용', verbose_name='분류 전용')),
                ('is_transfer_fee', models.BooleanField(default=False, help_text='체크 시: 이 계정은 은행 송금 이체수수료 계정임.', verbose_name='이체수수료 여부')),
                ('is_active', models.BooleanField(default=True, help_text='비활성화 시 신규 거래에 사용 불가', verbose_name='활성 여부')),
                ('order', models.PositiveIntegerField(default=0, help_text='같은 레벨 내 표시 순서', verbose_name='정렬순서')),
                ('requires_affiliate', models.BooleanField(default=False, help_text='체크 시: 회계분개 입력 시 관계회사 또는 프로젝트 선택 필수<br>용도: 관계회사 대여금, 투자금 등 집계가 필요한 계정', verbose_name='관계회사/프로젝트 필수')),
            ],
            options={
                'verbose_name': '01. 본사 계정 과목',
                'verbose_name_plural': '01. 본사 계정 과목',
                'ordering': ['code', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, help_text='BankTransaction.transaction_id 참조', verbose_name='거래 ID')),
                ('amount', models.PositiveBigIntegerField(help_text='이 회계 분개의 금액 (분할 시 일부 금액)', verbose_name='금액')),
                ('trader', models.CharField(blank=True, help_text='거래 상대방', max_length=50, null=True, verbose_name='거래처')),
                ('evidence_type', models.CharField(blank=True, choices=[('0', '증빙없음'), ('1', '세금계산서'), ('2', '계산서(면세)'), ('3', '신용/체크카드 매출전표'), ('4', '현금영수증'), ('5', '원천징수영수증/지급명세서'), ('6', '지로용지 및 청구서')], max_length=1, null=True, verbose_name='증빙종류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '04. 본사 회계 분개',
                'verbose_name_plural': '04. 본사 회계 분개',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='순서')),
                ('alias_name', models.CharField(db_index=True, max_length=20, verbose_name='계좌별칭')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='계좌번호')),
                ('holder', models.CharField(blank=True, max_length=20, verbose_name='예금주')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='개설일자')),
                ('note', models.CharField(blank=True, max_length=50, verbose_name='비고')),
                ('is_hide', models.BooleanField(default=False, verbose_name='숨기기 여부')),
                ('inactive', models.BooleanField(default=False, verbose_name='비활성 여부')),
            ],
            options={
                'verbose_name': '02. 본사 관리 계좌',
                'verbose_name_plural': '02. 본사 관리 계좌',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyBankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='도메인 간 연결을 위한 UUID 식별자', unique=True, verbose_name='거래 ID')),
                ('deal_date', models.DateField(verbose_name='거래일자')),
                ('amount', models.PositiveBigIntegerField(help_text='거래 금액 (양수)', verbose_name='금액')),
                ('content', models.CharField(blank=True, default='', help_text='거래 기록 사항', max_length=100, verbose_name='적요')),
                ('note', models.TextField(blank=True, default='', help_text='추가 설명', verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '03. 본사 은행 거래',
                'verbose_name_plural': '03. 본사 은행 거래',
                'ordering': ['-deal_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyLedgerCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated', models.DateField(blank=True, null=True, verbose_name='정산일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '05. 본사 원장 정산',
                'verbose_name_plural': '05. 본사 원장 정산',
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('import', '가져오기'), ('export', '내보내기')], max_length=10, verbose_name='작업 유형')),
                ('resource_type', models.CharField(choices=[('company_account', 'CompanyAccount'), ('project_account', 'ProjectAccount')], max_length=30, verbose_name='리소스 유형')),
                ('file', models.FileField(blank=True, null=True, upload_to='ledger_import_jobs/', verbose_name='파일')),
                ('task_id', models.CharField(blank=True, max_length=255, verbose_name='태스크 ID')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('total_records', models.IntegerField(default=0, verbose_name='전체 레코드')),
                ('processed_records', models.IntegerField(default=0, verbose_name='처리된 레코드')),
                ('success_count', models.IntegerField(default=0, verbose_name='성공 건수')),
                ('error_count', models.IntegerField(default=0, verbose_name='오류 건수')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('error_details', models.JSONField(blank=True, null=True, verbose_name='오류 상세')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='ledger_export_results/', verbose_name='결과 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
            ],
            options={
                'verbose_name': '12. 가져오기/내보내기 작업',
                'verbose_name_plural': '12. 가져오기/내보내기 작업',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='자동 생성됨. 수동 입력 시 규칙 무시', max_length=50, unique=True, verbose_name='계정코드')),
                ('name', models.CharField(max_length=255, verbose_name='계정명')),
                ('description', models.CharField(blank=True, default='', help_text='계정 용도 및 사용 지침', max_length=255, verbose_name='설명')),
                ('depth', models.PositiveIntegerField(default=1, editable=False, verbose_name='계층 깊이')),
                ('category', models.CharField(choices=[('asset', '자산'), ('liability', '부채'), ('equity', '자본'), ('revenue', '수익'), ('expense', '비용'), ('transfer', '대체'), ('cancel', '취소')], help_text='회계 계정의 대분류', max_length=20, verbose_name='계정구분')),
                ('direction', models.CharField(blank=True, choices=[('deposit', '입금'), ('withdraw', '출금')], help_text='이 계정이 사용되는 기본 거래 방향 (분류 전용 계정은 비워둠)', max_length=10, null=True, verbose_name='거래방향')),
                ('is_category_only', models.BooleanField(default=False, help_text='체크 시: 이 계정은 분류 목적으로만 사용되며 직접 거래에 사용 불가. 대분류/중분류 등 상위 계정에 주로 사용', verbose_name='분류 전용')),
                ('is_transfer_fee', models.BooleanField(default=False, help_text='체크 시: 이 계정은 은행 송금 이체수수료 계정임.', verbose_name='이체수수료 여부')),
                ('is_active', models.BooleanField(default=True, help_text='비활성화 시 신규 거래에 사용 불가', verbose_name='활성 여부')),
                ('order', models.PositiveIntegerField(default=0, help_text='같은 레벨 내 표시 순서', verbose_name='정렬순서')),
                ('is_payment', models.BooleanField(default=False, verbose_name='공급대금 여부')),
                ('requires_contract', models.BooleanField(default=False, verbose_name='계약 관련 여부')),
                ('is_related_contractor', models.BooleanField(default=False, verbose_name='계약자 관련 여부')),
            ],
            options={
                'verbose_name': '07. 프로젝트 계정 과목',
                'verbose_name_plural': '07. 프로젝트 계정 과목',
                'ordering': ['code', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(db_index=True, help_text='BankTransaction.transaction_id 참조', verbose_name='거래 ID')),
                ('amount', models.PositiveBigIntegerField(help_text='이 회계 분개의 금액 (분할 시 일부 금액)', verbose_name='금액')),
                ('trader', models.CharField(blank=True, help_text='거래 상대방', max_length=50, null=True, verbose_name='거래처')),
                ('evidence_type', models.CharField(blank=True, choices=[('0', '증빙없음'), ('1', '세금계산서'), ('2', '계산서(면세)'), ('3', '신용/체크카드 매출전표'), ('4', '현금영수증'), ('5', '원천징수영수증/지급명세서'), ('6', '지로용지 및 청구서')], max_length=1, null=True, verbose_name='증빙종류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '10. 프로젝트 회계 분개',
                'verbose_name_plural': '10. 프로젝트 회계 분개',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='순서')),
                ('alias_name', models.CharField(db_index=True, max_length=20, verbose_name='계좌별칭')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='계좌번호')),
                ('holder', models.CharField(blank=True, max_length=20, verbose_name='예금주')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='개설일자')),
                ('note', models.CharField(blank=True, max_length=50, verbose_name='비고')),
                ('is_hide', models.BooleanField(default=False, verbose_name='숨기기 여부')),
                ('inactive', models.BooleanField(default=False, verbose_name='비활성 여부')),
                ('directpay', models.BooleanField(default=False, verbose_name='용역비 직불 여부')),
                ('is_imprest', models.BooleanField(default=False, verbose_name='운영비 계좌 여부')),
            ],
            options={
                'verbose_name': '08. 프로젝트 관리 계좌',
                'verbose_name_plural': '08. 프로젝트 관리 계좌',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='도메인 간 연결을 위한 UUID 식별자', unique=True, verbose_name='거래 ID')),
                ('deal_date', models.DateField(verbose_name='거래일자')),
                ('amount', models.PositiveBigIntegerField(help_text='거래 금액 (양수)', verbose_name='금액')),
                ('content', models.CharField(blank=True, default='', help_text='거래 기록 사항', max_length=100, verbose_name='적요')),
                ('note', models.TextField(blank=True, default='', help_text='추가 설명', verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '09. 프로젝트 은행 거래',
                'verbose_name_plural': '09. 프로젝트 은행 거래',
                'ordering': ['-deal_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLedgerCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated', models.DateField(blank=True, null=True, verbose_name='정산일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '11. 프로젝트 원장 정산',
                'verbose_name_plural': '11. 프로젝트 원장 정산',
            },
        ),
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('company', '관계 회사'), ('project', '관련 프로젝트')], db_index=True, help_text='관계회사 또는 관련 프로젝트 구분', max_length=20, verbose_name='구분')),
                ('description', models.CharField(blank=True, default='', help_text='대여 목적, 조건 등 추가 설명', max_length=200, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('company', models.ForeignKey(blank=True, help_text='대여금/투자금 등이 발생한 관계회사', null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='관계 회사')),
            ],
            options={
                'verbose_name': '06. 관계회사/프로젝트',
                'verbose_name_plural': '06. 관계회사/프로젝트',
                'ordering': ['id'],
            },
        ),
    ]
