# Generated by Django 6.0 on 2025-12-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ibs', '0001_initial'),
        ('ledger', '0001_initial'),
        ('payment', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaccountingentry',
            name='installment_order',
            field=models.ForeignKey(blank=True, help_text='분할 납부 회차 정보', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.installmentpaymentorder', verbose_name='납부회차'),
        ),
        migrations.AddField(
            model_name='projectaccountingentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='projectbankaccount',
            name='bankcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.bankcode', verbose_name='거래은행'),
        ),
        migrations.AddField(
            model_name='projectbankaccount',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_bank_accounts', to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='projectbanktransaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.projectbankaccount', verbose_name='거래계좌'),
        ),
        migrations.AddField(
            model_name='projectbanktransaction',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='projectbanktransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='projectbanktransaction',
            name='sort',
            field=models.ForeignKey(help_text='입금/출금 구분', on_delete=django.db.models.deletion.PROTECT, to='ibs.accountsort', verbose_name='거래구분'),
        ),
        migrations.AddField(
            model_name='projectbanktransaction',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_transactions', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddField(
            model_name='projectledgercalculation',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='projectledgercalculation',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['sort', 'company'], name='ledger_affi_sort_8c823f_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['sort', 'project'], name='ledger_affi_sort_e6f047_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['parent', 'order'], name='ledger_comp_parent__e10532_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['category', 'is_active'], name='ledger_comp_categor_e85ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['requires_affiliate'], name='ledger_comp_require_2bc52e_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccountingentry',
            index=models.Index(fields=['account', 'created_at'], name='ledger_comp_account_af139f_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccountingentry',
            index=models.Index(fields=['affiliate'], name='ledger_comp_affilia_f23a11_idx'),
        ),
        migrations.AddIndex(
            model_name='companybanktransaction',
            index=models.Index(fields=['bank_account', 'deal_date'], name='ledger_comp_bank_ac_debfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccount',
            index=models.Index(fields=['parent', 'order'], name='ledger_proj_parent__4d9c24_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccount',
            index=models.Index(fields=['category', 'is_active'], name='ledger_proj_categor_5de2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccount',
            index=models.Index(fields=['is_payment'], name='ledger_proj_is_paym_39d0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccount',
            index=models.Index(fields=['is_related_contract'], name='ledger_proj_is_rela_2c92c0_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccount',
            index=models.Index(fields=['is_payment', 'is_related_contract'], name='ledger_proj_is_paym_8cb153_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccountingentry',
            index=models.Index(fields=['account', 'created_at'], name='ledger_proj_account_56a3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccountingentry',
            index=models.Index(fields=['contract'], name='ledger_proj_contrac_4ce359_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbanktransaction',
            index=models.Index(fields=['bank_account', 'deal_date'], name='ledger_proj_bank_ac_aff305_idx'),
        ),
    ]
