# Generated by Django 6.0.7 on 2026-07-11 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('contract', '0003_initial'),
        ('ibs', '0001_initial'),
        ('ledger', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='project',
            field=models.ForeignKey(blank=True, help_text='대여금/투자금 등이 발생한 관련 프로젝트', null=True, on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='관련 프로젝트'),
        ),
        migrations.AddField(
            model_name='companyaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.companyaccount', verbose_name='상위 계정'),
        ),
        migrations.AddField(
            model_name='companyaccountingentry',
            name='account',
            field=models.ForeignKey(help_text='회계 분개에 사용할 계정 과목', limit_choices_to={'is_active': True, 'is_category_only': False}, on_delete=django.db.models.deletion.PROTECT, to='ledger.companyaccount', verbose_name='계정 과목'),
        ),
        migrations.AddField(
            model_name='companyaccountingentry',
            name='affiliate',
            field=models.ForeignKey(blank=True, help_text='관계회사 대여금, 투자금 등의 경우 필수 입력', null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.affiliate', verbose_name='관계회사/프로젝트'),
        ),
        migrations.AddField(
            model_name='companyaccountingentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='회사'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='bankcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.bankcode', verbose_name='거래은행'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_bank_accounts', to='company.company', verbose_name='회사정보'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='com_bank_accounts', to='company.department', verbose_name='관리부서'),
        ),
        migrations.AddField(
            model_name='companybanktransaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.companybankaccount', verbose_name='거래계좌'),
        ),
        migrations.AddField(
            model_name='companybanktransaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='회사'),
        ),
        migrations.AddField(
            model_name='companybanktransaction',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='companybanktransaction',
            name='sort',
            field=models.ForeignKey(help_text='입금/출금 구분', on_delete=django.db.models.deletion.PROTECT, to='ibs.accountsort', verbose_name='거래구분'),
        ),
        migrations.AddField(
            model_name='companybanktransaction',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_transactions', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddField(
            model_name='companyledgercalculation',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='회사'),
        ),
        migrations.AddField(
            model_name='companyledgercalculation',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='projectaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.projectaccount', verbose_name='상위 계정'),
        ),
        migrations.AddField(
            model_name='projectaccountingentry',
            name='account',
            field=models.ForeignKey(help_text='회계 분개에 사용할 계정 과목', limit_choices_to={'is_active': True, 'is_category_only': False}, on_delete=django.db.models.deletion.PROTECT, to='ledger.projectaccount', verbose_name='계정 과목'),
        ),
        migrations.AddField(
            model_name='projectaccountingentry',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='공급계약 관련 계정 사용 시 필수 입력', null=True, on_delete=django.db.models.deletion.PROTECT, to='contract.contract', verbose_name='공급계약'),
        ),
        migrations.AddField(
            model_name='projectaccountingentry',
            name='contractor',
            field=models.ForeignKey(blank=True, help_text='계정 관련 계약자', null=True, on_delete=django.db.models.deletion.PROTECT, to='contract.contractor', verbose_name='계약자'),
        ),
        migrations.AddField(
            model_name='projectaccountingentry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='projectbankaccount',
            name='bankcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.bankcode', verbose_name='거래은행'),
        ),
        migrations.AddField(
            model_name='projectbankaccount',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_bank_accounts', to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='projectbanktransaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.projectbankaccount', verbose_name='거래계좌'),
        ),
        migrations.AddField(
            model_name='projectbanktransaction',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='projectbanktransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='projectbanktransaction',
            name='sort',
            field=models.ForeignKey(help_text='입금/출금 구분', on_delete=django.db.models.deletion.PROTECT, to='ibs.accountsort', verbose_name='거래구분'),
        ),
        migrations.AddField(
            model_name='projectbanktransaction',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_transactions', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddField(
            model_name='projectledgercalculation',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='projectledgercalculation',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['sort', 'company'], name='ledger_affi_sort_8c823f_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['sort', 'project'], name='ledger_affi_sort_e6f047_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['parent', 'order'], name='ledger_comp_parent__e10532_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['category', 'is_active'], name='ledger_comp_categor_e85ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccount',
            index=models.Index(fields=['requires_affiliate'], name='ledger_comp_require_2bc52e_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccountingentry',
            index=models.Index(fields=['account', 'created_at'], name='ledger_comp_account_af139f_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccountingentry',
            index=models.Index(fields=['affiliate'], name='ledger_comp_affilia_f23a11_idx'),
        ),
        migrations.AddIndex(
            model_name='companybanktransaction',
            index=models.Index(fields=['bank_account', 'deal_date'], name='ledger_comp_bank_ac_debfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccount',
            index=models.Index(fields=['parent', 'order'], name='ledger_proj_parent__4d9c24_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccount',
            index=models.Index(fields=['category', 'is_active'], name='ledger_proj_categor_5de2f0_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccount',
            index=models.Index(fields=['is_payment'], name='ledger_proj_is_paym_39d0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccount',
            index=models.Index(fields=['requires_contract'], name='ledger_proj_require_edd4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccount',
            index=models.Index(fields=['is_payment', 'requires_contract'], name='ledger_proj_is_paym_df63f2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccountingentry',
            index=models.Index(fields=['account', 'created_at'], name='ledger_proj_account_56a3e7_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccountingentry',
            index=models.Index(fields=['contract'], name='ledger_proj_contrac_4ce359_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbanktransaction',
            index=models.Index(fields=['bank_account', 'deal_date'], name='ledger_proj_bank_ac_aff305_idx'),
        ),
    ]
