# Generated by Django 6.0.6 on 2026-07-02 03:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybanktransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='도메인 간 연결을 위한 UUID 식별자', unique=True, verbose_name='거래 ID'),
        ),
        migrations.AlterField(
            model_name='projectbanktransaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='도메인 간 연결을 위한 UUID 식별자', unique=True, verbose_name='거래 ID'),
        ),
    ]
