# Generated by Django 6.0 on 2025-12-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectaccount',
            name='ledger_proj_is_rela_2c92c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='projectaccount',
            name='ledger_proj_is_paym_8cb153_idx',
        ),
        migrations.AddField(
            model_name='projectaccount',
            name='is_related_contractor',
            field=models.BooleanField(default=False, verbose_name='계약자 관련 여부'),
        ),
        migrations.AddField(
            model_name='projectaccount',
            name='requires_contract',
            field=models.BooleanField(default=False, verbose_name='계약 관련 여부'),
        ),
        migrations.AlterField(
            model_name='projectaccount',
            name='is_payment',
            field=models.BooleanField(default=False, verbose_name='공급대금 여부'),
        ),
        migrations.AddIndex(
            model_name='projectaccount',
            index=models.Index(fields=['requires_contract'], name='ledger_proj_require_edd4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='projectaccount',
            index=models.Index(fields=['is_payment', 'requires_contract'], name='ledger_proj_is_paym_df63f2_idx'),
        ),
        migrations.RemoveField(
            model_name='projectaccount',
            name='is_related_contract',
        ),
    ]
