# Generated by Django 6.0 on 2025-12-29 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_initial'),
        ('ledger', '0003_remove_projectaccount_ledger_proj_is_rela_2c92c0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectaccountingentry',
            name='contractor',
            field=models.ForeignKey(blank=True, help_text='계정 관련 계약자', null=True, on_delete=django.db.models.deletion.PROTECT, to='contract.contractor', verbose_name='계약자'),
        ),
    ]
