# Generated by Django 6.0 on 2025-12-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_projectaccountingentry_contractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybanktransaction',
            name='is_balanced',
        ),
        migrations.RemoveField(
            model_name='projectbanktransaction',
            name='is_balanced',
        ),
    ]
