# Generated by Django 6.0 on 2026-01-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_remove_companybanktransaction_is_balanced_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectaccountingentry',
            name='installment_order',
        ),
    ]
