# Generated by Django 6.0.1 on 2026-01-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_remove_projectaccountingentry_installment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccount',
            name='is_transfer_fee',
            field=models.BooleanField(default=False, help_text='체크 시: 이 계정은 은행 송금 이체수수료 계정임.', verbose_name='이체수수료 여부'),
        ),
        migrations.AddField(
            model_name='projectaccount',
            name='is_transfer_fee',
            field=models.BooleanField(default=False, help_text='체크 시: 이 계정은 은행 송금 이체수수료 계정임.', verbose_name='이체수수료 여부'),
        ),
    ]
