{{- if .Values.erpRedirect.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hibs.fullname" . }}-erp-redirect
  annotations:
    kubernetes.io/ingress.class: nginx
    # 전용 인그레스이므로 if문 없이 즉시 리다이렉트 (성능 최적화 및 경로 보존)
    nginx.ingress.kubernetes.io/configuration-snippet: |
      return 301 https://ibs.dyibs.com$request_uri;
spec:
  {{- if .Values.nginx.ingress.tls }}
  tls:
    - hosts:
        - erp.dyibs.com
      secretName: {{ (index .Values.nginx.ingress.tls 0).secretName }}
  {{- end }}
  rules:
    - host: erp.dyibs.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ printf "%s-%s" .Release.Name "nginx" | trunc 63 | trimSuffix "-" }}
                port:
                  number: {{ .Values.nginx.service.port }}
{{- end }}
