{{- if include "cnpg-postgres.createSecret" . }}
---
# Superuser (postgres) credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpg-postgres.fullname" . }}-superuser
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cnpg-postgres.labels" . | nindent 4 }}
    cnpg.io/reload: "true"
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ required "A valid .Values.auth.postgresPassword is required!" .Values.auth.postgresPassword | quote }}

---
# Application user credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpg-postgres.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cnpg-postgres.labels" . | nindent 4 }}
    cnpg.io/reload: "true"
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ include "cnpg-postgres.username" . | quote }}
  password: {{ required "A valid .Values.auth.password is required!" .Values.auth.password | quote }}
  {{- if .Values.auth.database }}
  dbname: {{ include "cnpg-postgres.database" . | quote }}
  {{- end }}

{{- if and .Values.backup.enabled .Values.backup.s3.enabled }}
---
# S3 backup credentials (if enabled)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpg-postgres.fullname" . }}-backup-s3
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cnpg-postgres.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  ACCESS_KEY_ID: {{ .Values.backup.s3.accessKeyId | default "" | quote }}
  ACCESS_SECRET_KEY: {{ .Values.backup.s3.secretAccessKey | default "" | quote }}
{{- end }}

{{- end }}
