# Generated by Django 6.0 on 2025-12-29 12:02

import board.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='이름')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='설명')),
                ('search_able', models.BooleanField(default=True, verbose_name='검색 사용')),
                ('manager', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='관리자')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='board.board')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='work.issueproject', verbose_name='업무 프로젝트')),
            ],
            options={
                'verbose_name': '01. 게시판 관리',
                'verbose_name_plural': '01. 게시판 관리',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='제목')),
                ('content', models.TextField(blank=True, default='', verbose_name='내용')),
                ('hit', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='좋아요')),
                ('blame', models.PositiveSmallIntegerField(default=0, verbose_name='신고')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='아이피')),
                ('device', models.CharField(blank=True, default='', max_length=255, verbose_name='등록기기')),
                ('is_secret', models.BooleanField(default=False, verbose_name='비밀글')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='패스워드')),
                ('is_hide_comment', models.BooleanField(default=False, verbose_name='댓글숨기기')),
                ('is_notice', models.BooleanField(default=False, verbose_name='공지')),
                ('is_blind', models.BooleanField(default=False, verbose_name='숨김')),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True, verbose_name='휴지통')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='board.board', verbose_name='게시판')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '03. 게시물 관리',
                'verbose_name_plural': '03. 게시물 관리',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='좋아요')),
                ('blame', models.PositiveSmallIntegerField(default=0, verbose_name='신고')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='아이피')),
                ('device', models.CharField(blank=True, max_length=255, verbose_name='등록기기')),
                ('secret', models.BooleanField(default=False, verbose_name='비밀글')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='board.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.post', verbose_name='게시물')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=21, null=True, verbose_name='색상')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='이름')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='정렬 순서')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='게시판')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.postcategory', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '02. 카테고리 관리',
                'verbose_name_plural': '02. 카테고리 관리',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.postcategory', verbose_name='카테고리'),
        ),
        migrations.CreateModel(
            name='PostFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=board.models.get_post_file_path, verbose_name='파일')),
                ('file_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='파일명')),
                ('file_type', models.CharField(blank=True, max_length=80, verbose_name='타입')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='사이즈')),
                ('hit', models.PositiveIntegerField(default=0, verbose_name='다운로드수')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='board.post', verbose_name='게시물')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=board.models.get_post_img_path, verbose_name='이미지')),
                ('image_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='파일명')),
                ('image_type', models.CharField(blank=True, max_length=30, verbose_name='타입')),
                ('image_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='사이즈')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.post', verbose_name='게시물')),
            ],
        ),
        migrations.CreateModel(
            name='PostLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500, verbose_name='링크')),
                ('hit', models.PositiveIntegerField(default=0, verbose_name='클릭수')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='board.post', verbose_name='게시물')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='태그')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='게시판')),
                ('post', models.ManyToManyField(blank=True, to='board.post', verbose_name='게시물')),
            ],
            options={
                'verbose_name': '04. 태그 관리',
                'verbose_name_plural': '04. 태그 관리',
                'ordering': ['id'],
            },
        ),
    ]
