# Generated by Django 6.0 on 2025-12-29 12:02

import contract.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_quantity', models.PositiveIntegerField(default=0, verbose_name='제출 수량')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
            ],
            options={
                'verbose_name': '계약자 제출 서류',
                'verbose_name_plural': '계약자 제출 서류',
                'db_table': 'contract_document',
                'ordering': ['required_document__display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contract.models.get_contract_document_file_name, verbose_name='파일')),
                ('file_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='파일명')),
                ('file_type', models.CharField(blank=True, max_length=80, verbose_name='파일 타입')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='파일 크기')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, verbose_name='업로드일시')),
            ],
            options={
                'verbose_name': '제출 서류 파일',
                'verbose_name_plural': '제출 서류 파일',
                'db_table': 'contract_document_file',
                'ordering': ['-uploaded_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contract.models.get_contract_file_name, verbose_name='파일경로')),
                ('file_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='파일명')),
                ('file_type', models.CharField(blank=True, max_length=80, verbose_name='타입')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='사이즈')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='계약자명')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('gender', models.CharField(blank=True, choices=[('M', '남자'), ('F', '여자')], max_length=1, verbose_name='성별')),
                ('qualification', models.CharField(choices=[('1', '일반분양'), ('2', '미인가조합원'), ('3', '인가조합원'), ('4', '부적격조합원')], default='1', max_length=1, verbose_name='등록상태')),
                ('status', models.CharField(choices=[('1', '청약'), ('2', '계약'), ('3', '청약 해지'), ('4', '계약 해지'), ('5', '양도 승계')], max_length=1, verbose_name='계약상태')),
                ('reservation_date', models.DateField(blank=True, null=True, verbose_name='청약일자')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='계약일자')),
                ('is_active', models.BooleanField(default=True, verbose_name='유효계약자여부')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
            ],
            options={
                'verbose_name': '06. 계약자 정보',
                'verbose_name_plural': '06. 계약자 정보',
            },
        ),
        migrations.CreateModel(
            name='ContractorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zipcode', models.CharField(max_length=5, verbose_name='우편번호')),
                ('id_address1', models.CharField(max_length=50, verbose_name='주민등록 주소')),
                ('id_address2', models.CharField(blank=True, max_length=30, verbose_name='상세주소')),
                ('id_address3', models.CharField(blank=True, max_length=30, verbose_name='참고항목')),
                ('dm_zipcode', models.CharField(max_length=5, verbose_name='우편번호')),
                ('dm_address1', models.CharField(max_length=50, verbose_name='우편송부 주소')),
                ('dm_address2', models.CharField(blank=True, max_length=50, verbose_name='상세주소')),
                ('dm_address3', models.CharField(blank=True, max_length=30, verbose_name='참고항목')),
                ('is_current', models.BooleanField(default=True, verbose_name='현주소 여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
            ],
            options={
                'verbose_name': '07. 계약자 주소',
                'verbose_name_plural': '07. 계약자 주소',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ContractorConsultationLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateField(verbose_name='상담일자')),
                ('channel', models.CharField(choices=[('visit', '방문'), ('phone', '전화'), ('email', '이메일'), ('sms', '문자'), ('kakao', '카카오톡'), ('other', '기타')], max_length=10, verbose_name='상담채널')),
                ('category', models.CharField(choices=[('payment', '납부상담'), ('contract', '계약상담'), ('change', '변경상담'), ('complaint', '민원/불만'), ('question', '문의'), ('succession', '승계상담'), ('release', '해지상담'), ('document', '서류관련'), ('etc', '기타')], max_length=20, verbose_name='상담유형')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='상담제목')),
                ('content', models.TextField(blank=True, default='', verbose_name='상담내용')),
                ('status', models.CharField(choices=[('1', '처리대기'), ('2', '처리중'), ('3', '처리완료'), ('4', '보류')], default='1', max_length=1, verbose_name='처리상태')),
                ('priority', models.CharField(choices=[('low', '낮음'), ('normal', '보통'), ('high', '높음'), ('urgent', '긴급')], default='normal', max_length=10, verbose_name='중요도')),
                ('follow_up_required', models.BooleanField(default=False, verbose_name='후속조치 필요')),
                ('follow_up_note', models.TextField(blank=True, verbose_name='후속조치 내용')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='처리완료일')),
                ('is_important', models.BooleanField(default=False, verbose_name='중요표시')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '08. 계약자 상담 기록',
                'verbose_name_plural': '08. 계약자 상담 기록',
                'ordering': ['-consultation_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ContractorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_phone', models.CharField(max_length=13, verbose_name='휴대전화')),
                ('home_phone', models.CharField(blank=True, max_length=13, verbose_name='집 전화')),
                ('other_phone', models.CharField(blank=True, max_length=13, verbose_name='기타 전화')),
                ('email', models.EmailField(blank=True, max_length=30, verbose_name='이메일')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', '신청 취소'), ('3', '해지 신청'), ('4', '해지 완료'), ('5', '자격 상실')], max_length=1, verbose_name='상태')),
                ('refund_amount', models.PositiveIntegerField(verbose_name='환불(예정)금액')),
                ('refund_account_bank', models.CharField(max_length=20, verbose_name='환불계좌(은행)')),
                ('refund_account_number', models.CharField(max_length=25, verbose_name='환불계좌(번호)')),
                ('refund_account_depositor', models.CharField(max_length=20, verbose_name='환불계좌(예금주)')),
                ('request_date', models.DateField(verbose_name='해지신청일')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='해지(환불)처리일')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
            ],
            options={
                'verbose_name': '10. 계약 해지 정보',
                'verbose_name_plural': '10. 계약 해지 정보',
            },
        ),
        migrations.CreateModel(
            name='ContractPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='분양가격')),
                ('price_build', models.PositiveIntegerField(blank=True, null=True, verbose_name='건물가')),
                ('price_land', models.PositiveIntegerField(blank=True, null=True, verbose_name='대지가')),
                ('price_tax', models.PositiveIntegerField(blank=True, null=True, verbose_name='부가세')),
                ('payment_amounts', models.JSONField(blank=True, default=dict, help_text='납부순서별 납부 금액 {"1": 10000000, "2": 30000000, "3": 20000000} (pay_time 기준)', verbose_name='회차별 납부금액')),
                ('calculated', models.DateTimeField(auto_now=True, help_text='마지막 계산 수행 시각', verbose_name='계산일시')),
                ('is_cache_valid', models.BooleanField(default=False, help_text='저장된 계산값이 유효한지 여부', verbose_name='캐시 유효성')),
            ],
            options={
                'verbose_name': '05. 계약 공급가격',
                'verbose_name_plural': '05. 계약 공급가격',
                'ordering': ('-contract__project', 'contract'),
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('proof', '증명서류'), ('pledge', '동의서류')], default='proof', max_length=20, verbose_name='서류구분')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='서류명')),
                ('default_quantity', models.PositiveIntegerField(default=1, verbose_name='기본 수량')),
                ('require_type', models.CharField(choices=[('required', '필수'), ('optional', '선택'), ('conditional', '조건부 필수')], default='required', max_length=20, verbose_name='필수 여부')),
                ('is_default_item', models.BooleanField(default=True, help_text='프로젝트 생성 시 자동으로 추가될 필수 서류', verbose_name='기본 서류 여부')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
            ],
            options={
                'verbose_name': '02. 필요 서류 유형 [템플릿]',
                'verbose_name_plural': '02. 필요 서류 유형 [템플릿]',
                'db_table': 'contract_document_type',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(verbose_name='차수')),
                ('sort', models.CharField(choices=[('1', '조합모집'), ('2', '일반분양')], default='1', max_length=1, verbose_name='구분')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='차수명')),
                ('is_default_for_uncontracted', models.BooleanField(default=False, help_text='미계약 세대 ContractPrice 생성 시 적용할 기본 차수 여부', verbose_name='미계약세대 기본설정')),
            ],
            options={
                'verbose_name': '01. 계약 차수 그룹',
                'verbose_name_plural': '01. 계약 차수 그룹',
                'ordering': ['-project', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('proof', '증명서류'), ('pledge', '동의서류')], default='proof', max_length=20, verbose_name='서류구분')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, verbose_name='필요 수량')),
                ('require_type', models.CharField(choices=[('required', '필수'), ('optional', '선택'), ('conditional', '조건부 필수')], default='required', max_length=20, verbose_name='필수 여부')),
                ('description', models.CharField(blank=True, default='', help_text='프로젝트별 특이사항, 요구 조건 또는 추가 요구사항', max_length=255, verbose_name='설명')),
                ('display_order', models.PositiveIntegerField(blank=True, default=0, help_text='서류 목록 표시 시 정렬 순서', verbose_name='표시 순서')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
            ],
            options={
                'verbose_name': '03. 프로젝트별 필요 서류',
                'verbose_name_plural': '03. 프로젝트별 필요 서류',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Succession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(verbose_name='승계신청일')),
                ('trading_date', models.DateField(verbose_name='매매계약일')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='변경인가일')),
                ('is_approval', models.BooleanField(default=False, verbose_name='변경인가여부')),
                ('note', models.TextField(blank=True, verbose_name='비고')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
            ],
            options={
                'verbose_name': '09. 권리 의무 승계',
                'verbose_name_plural': '09. 권리 의무 승계',
                'ordering': ['-apply_date', '-trading_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='계약 일련 번호')),
                ('activation', models.BooleanField(default=True, verbose_name='계약 활성 여부')),
                ('is_sup_cont', models.BooleanField(default=False, verbose_name='공급계약 체결여부')),
                ('sup_cont_date', models.DateField(blank=True, null=True, verbose_name='공급계약 체결일')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '04. 계약 정보',
                'verbose_name_plural': '04. 계약 정보',
                'ordering': ('-project', '-created'),
            },
        ),
    ]
