# Generated by Django 6.0 on 2025-12-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0001_initial'),
        ('items', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='key_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract', to='items.keyunit', verbose_name='계약유닛'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='contract',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.unittype', verbose_name='타입'),
        ),
        migrations.AddField(
            model_name='contract',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contracts', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contract_documents', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddField(
            model_name='contractdocumentfile',
            name='contract_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contract.contractdocument', verbose_name='계약 서류'),
        ),
        migrations.AddField(
            model_name='contractdocumentfile',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로드자'),
        ),
        migrations.AddField(
            model_name='contractfile',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='contract.contract', verbose_name='계약 정보'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='prev_contract',
            field=models.ForeignKey(blank=True, help_text='계약해지/양도승계 전 계약건', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_contractors', to='contract.contract', verbose_name='종전 계약건'),
        ),
        migrations.AddField(
            model_name='contractfile',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_files', to='contract.contractor', verbose_name='계약자'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_documents', to='contract.contractor', verbose_name='계약자'),
        ),
        migrations.AddField(
            model_name='contractoraddress',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contract.contractor', verbose_name='계약자 정보'),
        ),
        migrations.AddField(
            model_name='contractoraddress',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='contractorconsultationlogs',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='상담담당자'),
        ),
        migrations.AddField(
            model_name='contractorconsultationlogs',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_logs', to='contract.contractor', verbose_name='계약자'),
        ),
        migrations.AddField(
            model_name='contractorconsultationlogs',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consultations', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='contractorconsultationlogs',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_consultations', to=settings.AUTH_USER_MODEL, verbose_name='수정자'),
        ),
        migrations.AddField(
            model_name='contractorcontact',
            name='contractor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contractor', verbose_name='계약자 정보'),
        ),
        migrations.AddField(
            model_name='contractorcontact',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='contractorrelease',
            name='contractor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.contractor', verbose_name='계약자 정보'),
        ),
        migrations.AddField(
            model_name='contractorrelease',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='contractorrelease',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='contractorrelease',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contractor_releases', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddField(
            model_name='contractprice',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
        migrations.AddField(
            model_name='contractprice',
            name='house_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_price', to='items.houseunit', verbose_name='세대정보'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_document_types', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='contractprice',
            name='order_group',
            field=models.ForeignKey(blank=True, help_text='분양 차수 - 생성 시 자동 설정, 수정 시 유지', null=True, on_delete=django.db.models.deletion.PROTECT, to='contract.ordergroup', verbose_name='차수'),
        ),
        migrations.AddField(
            model_name='contract',
            name='order_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.ordergroup', verbose_name='차수'),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_requirements', to='contract.documenttype', verbose_name='서류 유형'),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_required_documents', to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='requireddocument',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_required_documents', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='required_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_submissions', to='contract.requireddocument', verbose_name='필요 서류'),
        ),
        migrations.AddField(
            model_name='succession',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curr_contractor', to='contract.contractor', verbose_name='양수계약자'),
        ),
        migrations.AddField(
            model_name='succession',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contract', verbose_name='계약 정보'),
        ),
        migrations.AddField(
            model_name='succession',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='succession',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prev_contractor', to='contract.contractor', verbose_name='양도계약자'),
        ),
        migrations.AddField(
            model_name='succession',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_successions', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddConstraint(
            model_name='contractoraddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('contractor',), name='unique_current_address_per_contractor'),
        ),
        migrations.AddConstraint(
            model_name='ordergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_for_uncontracted', True)), fields=('project',), name='unique_default_uncontracted_per_project'),
        ),
        migrations.AlterUniqueTogether(
            name='requireddocument',
            unique_together={('project', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='contractdocument',
            unique_together={('contractor', 'required_document')},
        ),
    ]
