# Generated by Django 6.0.1 on 2026-01-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorrelease',
            name='refund_account_bank',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='환불계좌(은행)'),
        ),
        migrations.AlterField(
            model_name='contractorrelease',
            name='refund_account_depositor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='환불계좌(예금주)'),
        ),
        migrations.AlterField(
            model_name='contractorrelease',
            name='refund_account_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='환불계좌(번호)'),
        ),
        migrations.AlterField(
            model_name='contractorrelease',
            name='refund_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='환불(예정)금액'),
        ),
    ]
