# Generated by Django 6.0.1 on 2026-01-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contractorrelease_refund_account_bank_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ('-project', '-created', '-pk'), 'verbose_name': '04. 계약 정보', 'verbose_name_plural': '04. 계약 정보'},
        ),
    ]
