# Generated by Django 6.0.7 on 2026-08-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorrelease',
            name='release_type',
            field=models.CharField(choices=[('1', '해지신청 (계약자)'), ('2', '부적격확인 (계약자)'), ('3', '해지통보 (공급자)')], default='1', max_length=1, verbose_name='해지 유형'),
        ),
    ]
