# Generated by Django 6.0.7 on 2026-07-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorrelease',
            name='refund_completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='해지(환불)처리일'),
        ),
        migrations.AlterField(
            model_name='contractorrelease',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='해지 확정 처리일'),
        ),
    ]
