# Generated by Django 6.0.7 on 2026-07-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='계약 활성 여부'),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='계약 완료 여부'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='change_type',
            field=models.CharField(blank=True, choices=[('1', '해지신청'), ('2', '부적격확인'), ('3', '승계신청')], max_length=1, null=True, verbose_name='변경 유형'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='now_status',
            field=models.CharField(choices=[('1', '청약'), ('2', '계약'), ('3', '변경처리중'), ('4', '계약종결')], default='1', max_length=1, verbose_name='계약자 상태'),
        ),
        migrations.AddField(
            model_name='succession',
            name='status',
            field=models.CharField(choices=[('1', '신청접수'), ('2', '변경인가대기'), ('3', '승계완료'), ('9', '승계취소')], default='1', verbose_name='상태'),
        ),
    ]
