# Generated by Django 6.0.7 on 2026-07-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contract_is_active_contract_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='activation',
        ),
    ]
