# Generated by Django 6.0.2 on 2026-02-10 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_contract_options'),
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.unittype', verbose_name='타입'),
        ),
    ]
