# Generated by Django 6.0.7 on 2026-08-07 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_contractorrelease_release_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='succession',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prev_contractor', to='contract.contractor', verbose_name='양도계약자'),
        ),
    ]
