# Generated by Django 6.0.7 on 2026-07-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_remove_contract_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='비고'),
        ),
    ]
