# Generated by Django 6.0.7 on 2026-08-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_succession_seller'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorrelease',
            name='contractor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='contract.contractor', verbose_name='계약자 정보'),
        ),
        migrations.AlterField(
            model_name='contractorrelease',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='프로젝트'),
        ),
    ]
