# Generated by Django 6.0.7 on 2026-07-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_contractor_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='status',
        ),
        migrations.AlterField(
            model_name='contractor',
            name='qualification',
            field=models.CharField(choices=[('1', '일반분양'), ('2', '미인가조합원'), ('3', '인가조합원')], default='1', max_length=1, verbose_name='등록상태'),
        ),
    ]
