# Generated by Django 6.0.7 on 2026-07-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_remove_contractor_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractor',
            old_name='now_status',
            new_name='status',
        ),
    ]
