# Generated by Django 6.0.7 on 2026-07-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_rename_now_status_contractor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='succession',
            name='is_approval',
        ),
        migrations.AlterField(
            model_name='succession',
            name='status',
            field=models.CharField(choices=[('1', '신청접수'), ('2', '변경인가대기'), ('3', '승계완료'), ('4', '승계취소')], default='1', verbose_name='상태'),
        ),
    ]
