# Generated by Django 6.0.7 on 2026-07-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_remove_succession_is_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorrelease',
            name='new_status',
            field=models.CharField(choices=[('0', '신청취소'), ('1', '신청접수'), ('2', '해지승인'), ('3', '변경인가대기'), ('4', '해지확정')], default='1', max_length=1, verbose_name='새 상태'),
        ),
        migrations.AddField(
            model_name='contractorrelease',
            name='release_type',
            field=models.CharField(choices=[('1', '해지신청'), ('2', '부적격확인')], default='1', max_length=1, verbose_name='해지 유형'),
        ),
    ]
