# Generated by Django 6.0.7 on 2026-07-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_contractorrelease_new_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorrelease',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='succession',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='비고'),
        ),
    ]
