# Generated by Django 6.0.7 on 2026-07-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_alter_contractorrelease_note_alter_succession_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorrelease',
            name='new_status',
            field=models.CharField(choices=[('1', '신청접수'), ('2', '해지승인'), ('3', '변경인가대기'), ('4', '해지확정'), ('9', '신청취소')], default='1', max_length=1, verbose_name='새 상태'),
        ),
        migrations.AlterField(
            model_name='succession',
            name='status',
            field=models.CharField(choices=[('1', '신청접수'), ('2', '변경인가대기'), ('3', '승계완료'), ('9', '승계취소')], default='1', verbose_name='상태'),
        ),
    ]
