# Generated by Django 6.0.7 on 2026-07-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_alter_contractorrelease_new_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorrelease',
            name='new_status',
            field=models.CharField(choices=[('1', '접수등록'), ('2', '해지승인대기'), ('3', '변경인가대기'), ('4', '해지확정'), ('9', '신청취소')], default='1', max_length=1, verbose_name='새 상태'),
        ),
    ]
