{{- if .Values.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ include "mariadb.primary.fullname" . }}-{{ .Values.global.appMode }}-backup-pvc
spec:
  storageClassName: dump-backup-{{ .Values.global.appMode }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.volumes.backupPvcStorage }}
{{- end }}
