# Generated by Django 6.0 on 2025-12-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0002_initial'),
        ('items', '0002_initial'),
        ('ledger', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallmentPaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sort', models.CharField(choices=[('1', '공동주택'), ('2', '오피스텔'), ('3', '숙박시설'), ('4', '지식산업센터'), ('5', '근린생활시설'), ('6', '기타')], default='1', max_length=1, verbose_name='타입종류')),
                ('pay_sort', models.CharField(choices=[('1', '계약금'), ('2', '중도금'), ('3', '잔금'), ('4', '계약금 정산'), ('5', '미납 연체료'), ('6', '기타 부담금'), ('7', '제세 공과금'), ('8', '후불 이자'), ('9', '업무 대행비')], default='1', max_length=1, verbose_name='종류')),
                ('is_except_price', models.BooleanField(default=False, help_text='취등록세, 후불 이자 등 공급가 불포함 항목인지 여부', verbose_name='공급가 불포함 여부')),
                ('pay_code', models.PositiveSmallIntegerField(help_text='프로젝트 내 납부회차별 코드번호 - 동일 회차 중복(분리) 등록 가능', verbose_name='납입회차 코드')),
                ('pay_time', models.PositiveSmallIntegerField(help_text='동일 납부회차에 2가지 항목을 분리해서 납부하여야 하는 경우(ex: 분담금 + 업무대행료)\n                                                하나의 납입회차 코드(ex: 1)에 2개의 납부순서(ex: 1, 2)를 등록한다.', verbose_name='납부순서')),
                ('pay_name', models.CharField(db_index=True, max_length=20, verbose_name='납부회차 명')),
                ('alias_name', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='회차 별칭')),
                ('pay_amt', models.PositiveIntegerField(blank=True, help_text='약정금이 차수, 타입/층수에 관계 없이 정액인 경우 설정 (예: 세대별 업무대행비)', null=True, verbose_name='납부 약정금액')),
                ('pay_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='분양가 대비 납부비율, 계약금 항목인 경우 Downpayment \n                                    테이블 데이터 우선, 잔금 항목인 경우 분양가와 비교 차액 데이터 우선', max_digits=5, null=True, verbose_name='회당 납부비율(%)')),
                ('pay_due_date', models.DateField(blank=True, help_text='특정일자를 납부기한으로 지정할 경우', null=True, verbose_name='냡부 약정일')),
                ('days_since_prev', models.PositiveSmallIntegerField(blank=True, help_text='전 회차(예: 계약일)로부터 __일 이내 형식으로 납부기한을 지정할 경우 해당 일수', null=True, verbose_name='전회 기준 경과일수')),
                ('is_prep_discount', models.BooleanField(default=False, verbose_name='선납할인 적용 여부')),
                ('prep_discount_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='선납할인율(%)')),
                ('prep_ref_date', models.DateField(blank=True, help_text='선납 할인 기준은 납부 약정일이 원칙이나 이 값이 있는 경우 선납 기준일로 우선 적용한다.', null=True, verbose_name='선납 기준일')),
                ('is_late_penalty', models.BooleanField(default=False, verbose_name='연체가산 적용 여부')),
                ('late_penalty_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='연체가산율(%)')),
                ('extra_due_date', models.DateField(blank=True, help_text='연체료 계산 기준은 납부 약정일이 원칙이나 이 값이 있는 경우 연체 기준일로 우선 적용한다.', null=True, verbose_name='연체 기준일')),
                ('calculation_method', models.CharField(choices=[('auto', '자동 (기존 우선순위)'), ('ratio', '분양가 × 납부비율'), ('downpayment', 'DownPayment 우선')], default='auto', help_text='계약금(pay_sort=1) 항목의 계산 방식 선택. 다른 납부 항목에는 적용되지 않음', max_length=20, verbose_name='계약금 계산 방식')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '01. 납입회차 관리',
                'verbose_name_plural': '01. 납입회차 관리',
                'ordering': ['-project', 'pay_code', 'pay_time'],
            },
        ),
        migrations.CreateModel(
            name='OverDueRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_start', models.IntegerField(blank=True, help_text='비어 있을 경우 최대 음수', null=True, verbose_name='최소연체(선납)일')),
                ('term_end', models.IntegerField(blank=True, help_text='비어 있을 경우 최대 양수', null=True, verbose_name='최대연체(선납)일')),
                ('rate_year', models.DecimalField(decimal_places=2, help_text='연체일이 0 또는 음수 구간인 경우 할인 적용', max_digits=4, verbose_name='연체(할인)이율')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '06. 선납할인/연체이율 관리',
                'verbose_name_plural': '06. 선납할인/연체이율 관리',
                'ordering': ('-project', 'term_start', 'term_end'),
            },
        ),
        migrations.CreateModel(
            name='SalesPriceByGT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_build', models.PositiveIntegerField(blank=True, null=True, verbose_name='건물가')),
                ('price_land', models.PositiveIntegerField(blank=True, null=True, verbose_name='대지가')),
                ('price_tax', models.PositiveIntegerField(blank=True, null=True, verbose_name='부가세')),
                ('price', models.PositiveIntegerField(verbose_name='기준공급가')),
                ('order_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.ordergroup', verbose_name='차수')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트')),
                ('unit_floor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.unitfloortype', verbose_name='층별타입')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.unittype', verbose_name='타입')),
            ],
            options={
                'verbose_name': '02. 기준 공급가격',
                'verbose_name_plural': '02. 기준 공급가격',
                'ordering': ('order_group', 'unit_type', 'unit_floor_type', 'project'),
                'unique_together': {('project', 'order_group', 'unit_type', 'unit_floor_type')},
            },
        ),
        migrations.CreateModel(
            name='SpecialDownPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.PositiveIntegerField(help_text='차수 및 타입별 고정 납부 계약금액, 납부 회수는 납부 회차 모델에서 별도 등록/설정', verbose_name='회차별 계약금액')),
                ('payment_remain', models.IntegerField(default=0, verbose_name='나머지 계약금액')),
                ('order_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.ordergroup', verbose_name='차수정보')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.unittype', verbose_name='타입정보')),
            ],
            options={
                'verbose_name': '08. 특별 회차별 납입금',
                'verbose_name_plural': '08. 특별 회차별 납입금',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SpecialOverDueRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_start', models.IntegerField(blank=True, help_text='비어 있을 경우 최대 음수', null=True, verbose_name='최소연체(선납)일')),
                ('term_end', models.IntegerField(blank=True, help_text='비어 있을 경우 최대 양수', null=True, verbose_name='최대연체(선납)일')),
                ('rate_year', models.DecimalField(decimal_places=2, help_text='연체일이 0 또는 음수 구간인 경우 할인 적용', max_digits=4, verbose_name='연체(할인)이율')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '09. 특별 선납할인/연체이율',
                'verbose_name_plural': '09. 특별 선납할인/연체이율',
                'ordering': ('-project', 'term_start', 'term_end'),
            },
        ),
        migrations.CreateModel(
            name='SpecialPaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_sort', models.CharField(choices=[('1', '계약금'), ('2', '중도금'), ('3', '잔금'), ('4', '계약금 정산'), ('5', '미납 연체료'), ('6', '기타 부담금'), ('7', '제세 공과금'), ('8', '후불 이자'), ('9', '업무 대행비')], default='1', max_length=1, verbose_name='종류')),
                ('pay_code', models.PositiveSmallIntegerField(help_text='프로젝트 내에서 모든 납부회차를 고유 순서대로 숫자로 부여한다.', verbose_name='납입회차 코드')),
                ('pay_time', models.PositiveSmallIntegerField(help_text='동일 납부회차에 2가지 항목을 별도로 납부하여야 하는 경우(ex: 분담금 + 업무대행료)\n                                                하나의 납입회차 코드(ex: 1)에 2개의 납부순서(ex: 1, 2)를 등록한다.', verbose_name='납부순서')),
                ('pay_name', models.CharField(max_length=20, verbose_name='납부회차 명')),
                ('alias_name', models.CharField(blank=True, max_length=20, verbose_name='회차 별칭')),
                ('days_since_prev', models.PositiveSmallIntegerField(blank=True, help_text='전 회차(예: 계약일)로부터 __일 이내 형식으로 납부기한을 지정할 경우 해당 일수', null=True, verbose_name='전회 기준 경과일수')),
                ('is_prep_discount', models.BooleanField(default=False, verbose_name='선납할인 적용 여부')),
                ('is_late_penalty', models.BooleanField(default=False, verbose_name='연체가산 적용 여부')),
                ('pay_due_date', models.DateField(blank=True, help_text='특정일자를 납부기한으로 지정할 경우', null=True, verbose_name='지정 납부기한')),
                ('extra_due_date', models.DateField(blank=True, help_text='연체료 계산 기준은 지정 납부기한이 원칙이나 이 값이 있는 경우 납부유예일을 연체료 계산 기준으로 한다.', null=True, verbose_name='납부유예일')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '07. 특별 납입회차',
                'verbose_name_plural': '07. 특별 납입회차',
                'ordering': ['-project', 'pay_code'],
            },
        ),
        migrations.CreateModel(
            name='DownPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.PositiveIntegerField(help_text='동호 미지정 계약 등 차수 및 타입별 각 계약금 회차 고정 납부 계약금. 미지정 시 공급가격 * 회차별 납부비율 적용', verbose_name='회차별 계약금액')),
                ('order_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.ordergroup', verbose_name='차수정보')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.unittype', verbose_name='타입정보')),
            ],
            options={
                'verbose_name': '04. 타입별 일괄 계약금',
                'verbose_name_plural': '04. 타입별 일괄 계약금',
                'ordering': ('id',),
                'unique_together': {('project', 'order_group', 'unit_type')},
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payment_mismatch', models.BooleanField(default=False, help_text='연결된 회계분개의 is_payment=False인 경우 True로 표시', verbose_name='결제계정 불일치')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('accounting_entry', models.OneToOneField(help_text='ProjectAccountingEntry와 1:1 연결 (is_payment=True인 분개)', on_delete=django.db.models.deletion.CASCADE, related_name='contract_payment', to='ledger.projectaccountingentry', verbose_name='회계 분개')),
                ('contract', models.ForeignKey(blank=True, help_text='분양 계약 (베이스 인스턴스 생성 시 선택사항)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract', verbose_name='계약')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트')),
                ('installment_order', models.ForeignKey(blank=True, help_text='분할 납부 회차 정보', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.installmentpaymentorder', verbose_name='납부회차')),
            ],
            options={
                'verbose_name': '05. 분양 대금 납부',
                'verbose_name_plural': '05. 분양 대금 납부',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['installment_order', 'created_at'], name='payment_con_install_e362d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentPerInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='일반 납부회차의 경우 기준 공급가 * 회당 납부비율을 적용 하나,\n                                         이 데이터 등록 시 예외적으로 이 데이터를 우선 적용함', verbose_name='납부 약정금액')),
                ('pay_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_installments', to='payment.installmentpaymentorder', verbose_name='납부 회차')),
                ('sales_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.salespricebygt', verbose_name='기준 공급가격')),
            ],
            options={
                'verbose_name': '03. 특별 약정금액',
                'verbose_name_plural': '03. 특별 약정금액',
                'ordering': ('sales_price__order_group', 'pay_order', 'sales_price__unit_type'),
                'unique_together': {('sales_price', 'pay_order')},
            },
        ),
    ]
