# Generated by Django 6.0 on 2025-12-30 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpayment',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='분양 계약 (베이스 인스턴스 생성 시 선택사항)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contract.contract', verbose_name='계약'),
        ),
    ]
