# Generated by Django 6.0.6 on 2026-07-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installmentpaymentorder',
            options={'ordering': ['project', 'pay_code', 'pay_time'], 'verbose_name': '01. 납입회차 관리', 'verbose_name_plural': '01. 납입회차 관리'},
        ),
        migrations.AlterModelOptions(
            name='overduerule',
            options={'ordering': ('project', 'term_start', 'term_end'), 'verbose_name': '06. 선납할인/연체이율 관리', 'verbose_name_plural': '06. 선납할인/연체이율 관리'},
        ),
        migrations.AlterField(
            model_name='installmentpaymentorder',
            name='pay_due_date',
            field=models.DateField(blank=True, help_text='특정일자를 납부기한으로 지정할 경우', null=True, verbose_name='납부 약정일'),
        ),
    ]
