# Generated by Django 6.0 on 2025-12-31 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_initial'),
        ('ledger', '0005_remove_companybanktransaction_is_balanced_and_more'),
        ('payment', '0002_alter_contractpayment_contract'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractpayment',
            options={'ordering': ['-deal_date', '-created_at'], 'verbose_name': '05. 분양 대금 납부', 'verbose_name_plural': '05. 분양 대금 납부'},
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='deal_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='거래일자'),
        ),
        migrations.AddIndex(
            model_name='contractpayment',
            index=models.Index(fields=['project', 'deal_date'], name='payment_con_project_5e291f_idx'),
        ),
        migrations.AddIndex(
            model_name='contractpayment',
            index=models.Index(fields=['contract', 'deal_date'], name='payment_con_contrac_ced2a1_idx'),
        ),
        migrations.AddIndex(
            model_name='contractpayment',
            index=models.Index(fields=['deal_date', 'installment_order'], name='payment_con_deal_da_bd2217_idx'),
        ),
    ]
