# Generated by Django 6.0 on 2026-01-01 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_initial'),
        ('payment', '0003_alter_contractpayment_options_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpayment',
            name='contract',
            field=models.ForeignKey(blank=True, editable=False, help_text='⚠️ accounting_entry.contract에서 자동 동기화 (직접 수정 불가)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contract.contract', verbose_name='계약'),
        ),
        migrations.AlterField(
            model_name='contractpayment',
            name='deal_date',
            field=models.DateField(blank=True, db_index=True, editable=False, help_text='⚠️ related_transaction.deal_date에서 자동 동기화 (직접 수정 불가)', null=True, verbose_name='거래일자'),
        ),
        migrations.AlterField(
            model_name='contractpayment',
            name='project',
            field=models.ForeignKey(editable=False, help_text='⚠️ accounting_entry.project에서 자동 동기화 (직접 수정 불가)', on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트'),
        ),
    ]
