# Generated by Django 6.0.2 on 2026-05-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_contract_unit_type'),
        ('payment', '0004_alter_contractpayment_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpaymentorder',
            name='excluded_order_groups',
            field=models.ManyToManyField(blank=True, help_text='특정 차수에서 이 회차를 건너뛸 경우(잔금 이월 등) 해당 차수를 선택하세요.', related_name='excluded_payments', to='contract.ordergroup', verbose_name='제외 차수'),
        ),
    ]
