apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}-config
  labels:
    {{- include "web.labels" . | nindent 4 }}
data:
  DATABASE_TYPE: "{{ .Values.global.dbType }}"
  DATABASE_NAME: "{{ .Release.Name }}"
  DATABASE_USER: "{{ .Release.Name }}"
  DOMAIN_HOST: "{{ .Values.global.domainHost }}"
  EMAIL_HOST: "{{ .Values.global.emailHost }}"
  EMAIL_HOST_USER: "{{ .Values.global.emailHostUser }}"
  DEFAULT_FROM_EMAIL: "{{ .Values.global.defaultFromEmail }}"
  NAMESPACE: "{{ .Release.Namespace }}"

  {{- with .Values.imageConfigMaps }}
  DJANGO_SETTINGS_MODULE: "{{ .djangoSettingsModule }}"
  {{- if .awsStorageBucketName }}
  AWS_STORAGE_BUCKET_NAME: "{{ .awsStorageBucketName }}"
  {{- end }}
  {{- if .imageSecrets.awsAccessKeyId }}
  AWS_S3_ACCESS_KEY_ID: "{{ .imageSecrets.awsAccessKeyId }}"
  {{- end }}
  {{- if .imageSecrets.awsSecretAccessKey }}
  AWS_S3_SECRET_ACCESS_KEY: "{{ .imageSecrets.awsSecretAccessKey }}"
  {{- end }}
  {{- if .awsS3EndpointUrl }}
  AWS_S3_ENDPOINT_URL: "{{ .awsS3EndpointUrl }}"
  {{- end }}
  {{- if .awsRegion }}
  AWS_REGION: "{{ .awsRegion }}"
  {{- end }}
  {{- if .awsQuerystringExpire }}
  AWS_QUERYSTRING_EXPIRE: "{{ .awsQuerystringExpire }}"
  {{- end }}
  {{- end }}
