apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}-config
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-10"
  labels:
    {{- include "web.labels" . | nindent 4 }}
data:
  DATABASE_TYPE: "{{ .Values.global.dbType }}"
  DATABASE_NAME: "{{ .Values.global.databaseName | default .Release.Name }}"
  DATABASE_USER: "{{ .Values.global.databaseUser | default .Release.Name }}"
  NAMESPACE: "{{ .Release.Namespace }}"
  DJANGO_SETTINGS_MODULE: "_config.settings"
