# Generated by Django 6.0 on 2025-12-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='동(건물)이름')),
            ],
            options={
                'verbose_name': '04. 동수',
                'verbose_name_plural': '04. 동수',
                'ordering': ('-project', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HouseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=5, verbose_name='호수')),
                ('bldg_line', models.PositiveSmallIntegerField(verbose_name='라인')),
                ('floor_no', models.SmallIntegerField(verbose_name='층수')),
                ('is_hold', models.BooleanField(default=False, verbose_name='홀딩 여부')),
                ('hold_reason', models.CharField(blank=True, max_length=100, verbose_name='홀딩 사유')),
            ],
            options={
                'verbose_name': '05. 호수',
                'verbose_name_plural': '05. 호수',
                'ordering': ['-building_unit__project', 'building_unit', '-floor_no', 'bldg_line'],
            },
        ),
        migrations.CreateModel(
            name='KeyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(db_index=True, max_length=8, verbose_name='코드번호')),
            ],
            options={
                'verbose_name': '03. 계약 유닛',
                'verbose_name_plural': '03. 계약 유닛',
                'ordering': ['id', '-project'],
            },
        ),
        migrations.CreateModel(
            name='OptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='품목코드')),
                ('opt_name', models.CharField(db_index=True, max_length=100, verbose_name='품목이름')),
                ('opt_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='세부옵션')),
                ('opt_maker', models.CharField(blank=True, max_length=20, null=True, verbose_name='제조사')),
                ('opt_price', models.PositiveIntegerField(verbose_name='옵션가격')),
                ('opt_deposit', models.PositiveIntegerField(blank=True, null=True, verbose_name='계약금')),
                ('opt_balance', models.PositiveIntegerField(blank=True, null=True, verbose_name='잔금')),
            ],
            options={
                'verbose_name': '06. 옵션 품목',
                'verbose_name_plural': '06. 옵션 품목',
            },
        ),
        migrations.CreateModel(
            name='UnitFloorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('1', '공동주택'), ('2', '오피스텔'), ('3', '숙박시설'), ('4', '지식산업센터'), ('5', '근린생활시설'), ('6', '기타')], max_length=1, verbose_name='타입종류')),
                ('start_floor', models.SmallIntegerField(verbose_name='시작 층')),
                ('end_floor', models.SmallIntegerField(verbose_name='종료 층')),
                ('extra_cond', models.CharField(blank=True, help_text='동일범위의 층범위를 방향/위치 등으로 구분해야 할 필요가 있는 경우 입력', max_length=20, verbose_name='방향/위치')),
                ('alias_name', models.CharField(db_index=True, max_length=20, verbose_name='층별 범위 명칭')),
            ],
            options={
                'verbose_name': '02. 층별 조건',
                'verbose_name_plural': '02. 층별 조건',
                'ordering': ['-project', 'sort', '-end_floor'],
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_or_sub', models.CharField(choices=[('1', '메인유닛'), ('2', '부대시설')], default='1', max_length=1, verbose_name='종류')),
                ('sort', models.CharField(choices=[('1', '공동주택'), ('2', '오피스텔'), ('3', '숙박시설'), ('4', '지식산업센터'), ('5', '근린생활시설'), ('6', '기타')], max_length=1, verbose_name='타입종류')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='타입명칭')),
                ('color', models.CharField(max_length=20, verbose_name='타입색상')),
                ('actual_area', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='전용면적(㎡)')),
                ('supply_area', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='공급면적(㎡)')),
                ('contract_area', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='계약면적(㎡)')),
                ('average_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='평균가격')),
                ('price_setting', models.CharField(choices=[('1', '타입별 설정'), ('2', '층타입별 설정'), ('3', '호별 설정')], default='2', max_length=1, verbose_name='공급가 설정 옵션')),
                ('num_unit', models.PositiveSmallIntegerField(verbose_name='세대수')),
            ],
            options={
                'verbose_name': '01. 타입 정보',
                'verbose_name_plural': '01. 타입 정보',
                'ordering': ['id'],
            },
        ),
    ]
