# Generated by Django 6.0 on 2025-12-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingunit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='building_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.buildingunit', verbose_name='동수'),
        ),
        migrations.AddField(
            model_name='keyunit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='key_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.keyunit', verbose_name='계약유닛'),
        ),
        migrations.AddField(
            model_name='optionitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='unitfloortype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='floor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.unitfloortype', verbose_name='층범위 타입'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='optionitem',
            name='types',
            field=models.ManyToManyField(to='items.unittype', verbose_name='타입구분'),
        ),
        migrations.AddField(
            model_name='keyunit',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.unittype', verbose_name='타입'),
        ),
        migrations.AddField(
            model_name='houseunit',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.unittype', verbose_name='타입'),
        ),
    ]
