# Generated by Django 6.1.1 on 2026-09-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionitem',
            options={'ordering': ['-project', 'id'], 'verbose_name': '06. 옵션 품목', 'verbose_name_plural': '06. 옵션 품목'},
        ),
    ]
