# Generated by Django 6.0.7 on 2026-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyunit',
            options={'ordering': ['-project', 'id'], 'verbose_name': '03. 계약 유닛', 'verbose_name_plural': '03. 계약 유닛'},
        ),
        migrations.AlterModelOptions(
            name='unitfloortype',
            options={'ordering': ['-project__id', 'sort', '-end_floor'], 'verbose_name': '02. 층별 조건', 'verbose_name_plural': '02. 층별 조건'},
        ),
        migrations.AlterField(
            model_name='optionitem',
            name='opt_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='품목코드'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optionitem',
            name='opt_desc',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='세부옵션'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optionitem',
            name='opt_maker',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='제조사'),
            preserve_default=False,
        ),
    ]
