# Generated by Django 6.1.1 on 2026-09-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_optionitem_options'),
        ('project', '0002_alter_project_options_alter_projectincbudget_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyunit',
            unique_together={('project', 'unit_code')},
        ),
    ]
