# Generated by Django 6.1 on 2026-08-23 17:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocScrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='스크랩 타이틀')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='보관일')),
            ],
            options={
                'verbose_name': '문서 스크랩',
                'verbose_name_plural': '문서 스크랩',
            },
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.TextField(unique=True, verbose_name='FCM 등록 토큰')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='기기 고유 식별자')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], default='android', max_length=10, verbose_name='플랫폼')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': 'FCM 기기 토큰',
                'verbose_name_plural': 'FCM 기기 토큰 목록',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='알림 제목')),
                ('body', models.TextField(verbose_name='알림 내용')),
                ('category', models.CharField(choices=[('work', '업무'), ('meeting', '회의'), ('notice', '공지'), ('approval', '전자결재'), ('chat', '채팅')], default='work', max_length=20, verbose_name='카테고리')),
                ('target_type', models.CharField(blank=True, help_text='issue, meeting, notice 등', max_length=50, verbose_name='대상 유형')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='대상 식별자')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='추가 페이로드')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생일시')),
            ],
            options={
                'verbose_name': '사용자 알림',
                'verbose_name_plural': '사용자 알림 목록',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='토큰')),
                ('expired', models.PositiveIntegerField(blank=True, default=600, null=True, verbose_name='만료시간(초)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
            ],
        ),
        migrations.CreateModel(
            name='PostScrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='스크랩 타이틀')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='보관일')),
            ],
            options={
                'verbose_name': '게시글 스크랩',
                'verbose_name_plural': '게시글 스크랩',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='성명')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('cell_phone', models.CharField(blank=True, max_length=13, verbose_name='휴대폰')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='프로필 이미지')),
                ('auto_watch_created', models.BooleanField(default=True, verbose_name='내가 생성한 업무 자동 모니터링')),
                ('auto_watch_assigned', models.BooleanField(default=True, verbose_name='나에게 할당된 업무 자동 모니터링')),
                ('meeting_created_notification', models.BooleanField(default=True, verbose_name='회의록 등록 시 알림 수신')),
                ('meeting_confirmed_notification', models.BooleanField(default=True, verbose_name='회의록 확정 시 알림 수신')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='할일내용')),
                ('completed', models.BooleanField(default=False, verbose_name='완료여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
                ('soft_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('work_manager', models.BooleanField(default=False, help_text='업무(redmine) 시스템 관리자인지 여부.', verbose_name='업무시스템 관리자')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
