# Generated by Django 6.0 on 2025-12-29 12:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocScrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='스크랩 타이틀')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='보관일')),
            ],
            options={
                'verbose_name': '문서 스크랩',
                'verbose_name_plural': '문서 스크랩',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='토큰')),
                ('expired', models.PositiveIntegerField(blank=True, default=600, null=True, verbose_name='만료시간(초)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
            ],
        ),
        migrations.CreateModel(
            name='PostScrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='스크랩 타이틀')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='보관일')),
            ],
            options={
                'verbose_name': '게시글 스크랩',
                'verbose_name_plural': '게시글 스크랩',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='성명')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('cell_phone', models.CharField(blank=True, max_length=13, verbose_name='휴대폰')),
                ('image', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='프로필 이미지')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StaffAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False, help_text='외부 관계자가 아닌 본사 직원(관리자)일 경우 선택', verbose_name='본사 관리자')),
                ('is_project_staff', models.BooleanField(default=False, help_text='본사 직원 외 프로젝트 관리 직원(관리자)일 경우 선택', verbose_name='프로젝트 관리자')),
                ('contract', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='분양 계약 관리')),
                ('payment', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='분양 수납 관리')),
                ('notice', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='고객 고지 관리')),
                ('project_ledger', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='PR 회계 관리')),
                ('project_docs', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='PR 문서 관리')),
                ('project', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='신규 프로젝트')),
                ('project_site', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='사업 부지 관리')),
                ('company_ledger', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='본사 회계 관리')),
                ('company_docs', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='본사 문서 관리')),
                ('human_resource', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='본사 인사 관리')),
                ('company_settings', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='회사 관련설정')),
                ('auth_manage', models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='권한 설정 관리')),
            ],
            options={
                'verbose_name': '스태프 권한',
                'verbose_name_plural': '스태프 권한',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='할일내용')),
                ('completed', models.BooleanField(default=False, verbose_name='완료여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
                ('soft_deleted', models.BooleanField(default=False, verbose_name='삭제여부')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('work_manager', models.BooleanField(default=False, help_text='업무(redmine) 시스템 관리자인지 여부.', verbose_name='업무 시스템 관리자')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
