# Generated by Django 6.0 on 2025-12-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('board', '0001_initial'),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docscrape',
            name='docs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.document'),
        ),
        migrations.AddField(
            model_name='docscrape',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postscrape',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post'),
        ),
        migrations.AddField(
            model_name='postscrape',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='blame_comments',
            field=models.ManyToManyField(blank=True, related_name='comment_blames', to='board.comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blame_posts',
            field=models.ManyToManyField(blank=True, related_name='post_blames', to='board.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='like_comments',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to='board.comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='board.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
