# Generated by Django 6.0.6 on 2026-06-25 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postscrape',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.post'),
        ),
        migrations.AddField(
            model_name='postscrape',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='blame_comments',
            field=models.ManyToManyField(blank=True, related_name='comment_blames', to='forum.comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='blame_posts',
            field=models.ManyToManyField(blank=True, related_name='post_blames', to='forum.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='like_comments',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to='forum.comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='forum.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
