# Generated by Django 6.0 on 2025-12-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('company', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffauth',
            name='allowed_projects',
            field=models.ManyToManyField(blank=True, help_text='사용자가 조회 및 관리할 수 있는 프로젝트들을 선택합니다.', related_name='allowed_projects', to='project.project', verbose_name='허용 프로젝트'),
        ),
        migrations.AddField(
            model_name='staffauth',
            name='assigned_project',
            field=models.ForeignKey(blank=True, help_text='선택한 프로젝트를 사용자의 각 화면에서 기본 프로젝트로 보여줍니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='담당 메인 프로젝트'),
        ),
        migrations.AddField(
            model_name='staffauth',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='회사정보'),
        ),
        migrations.AddField(
            model_name='staffauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
