# Generated by Django 6.1 on 2026-08-17 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.TextField(unique=True, verbose_name='FCM 등록 토큰')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='기기 고유 식별자')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], default='android', max_length=10, verbose_name='플랫폼')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': 'FCM 기기 토큰',
                'verbose_name_plural': 'FCM 기기 토큰 목록',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='알림 제목')),
                ('body', models.TextField(verbose_name='알림 내용')),
                ('category', models.CharField(choices=[('work', '업무'), ('meeting', '회의'), ('notice', '공지'), ('approval', '전자결재'), ('chat', '채팅')], default='work', max_length=20, verbose_name='카테고리')),
                ('target_type', models.CharField(blank=True, help_text='issue, meeting, notice 등', max_length=50, verbose_name='대상 유형')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='대상 식별자')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='추가 페이로드')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
            ],
            options={
                'verbose_name': '사용자 알림',
                'verbose_name_plural': '사용자 알림 목록',
                'ordering': ('-created_at',),
            },
        ),
    ]
