# Generated by Django 6.0.5 on 2026-05-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffauth',
            options={'ordering': ('-id',), 'verbose_name': '사용자 정의 권한', 'verbose_name_plural': '사용자 정의 권한'},
        ),
    ]
