# Generated by Django 6.1 on 2026-08-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docscrape',
            options={'verbose_name': '03. 문서 스크랩', 'verbose_name_plural': '03. 문서 스크랩'},
        ),
        migrations.AlterModelOptions(
            name='fcmdevice',
            options={'ordering': ('-updated_at',), 'verbose_name': '07. FCM 기기 토큰', 'verbose_name_plural': '07. FCM 기기 토큰 목록'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': '08. 사용자 알림', 'verbose_name_plural': '08. 사용자 알림 목록'},
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'ordering': ('-updated',), 'verbose_name': '06. 패스워드 리셋토큰', 'verbose_name_plural': '06. 패스워드 리셋토큰'},
        ),
        migrations.AlterModelOptions(
            name='postscrape',
            options={'verbose_name': '04. 게시글 스크랩', 'verbose_name_plural': '04. 게시글 스크랩'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-id',), 'verbose_name': '02. 사용자 프로필', 'verbose_name_plural': '02. 사용자 프로필'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('id',), 'verbose_name': '05. 할일 목록', 'verbose_name_plural': '05. 할일 목록'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',), 'verbose_name': '01. 사용자', 'verbose_name_plural': '01. 사용자'},
        ),
    ]
