# Generated by Django 6.0.6 on 2026-06-29 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
