# Generated by Django 6.0.7 on 2026-07-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffAuth',
        ),
    ]
