# Generated by Django 6.0.4 on 2026-05-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_staffauth_project_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffauth',
            name='project_ledger',
            field=models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='회계 자금 관리'),
        ),
    ]
