# Generated by Django 6.0.7 on 2026-07-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='meeting_notification',
        ),
        migrations.AddField(
            model_name='profile',
            name='meeting_confirmed_notification',
            field=models.BooleanField(default=True, verbose_name='회의록 확정 시 알림 수신'),
        ),
        migrations.AddField(
            model_name='profile',
            name='meeting_created_notification',
            field=models.BooleanField(default=True, verbose_name='회의록 등록 시 알림 수신'),
        ),
    ]
