# Generated by Django 6.1 on 2026-08-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_docscrape_options_alter_fcmdevice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_system',
            field=models.BooleanField(default=False, help_text='시스템 공지/알림/봇 전용 계정 여부. 일반 구성원 선택 목록에서 제외됩니다.', verbose_name='시스템 계정'),
        ),
    ]
