# Generated by Django 6.0.6 on 2026-07-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_watch_assigned',
            field=models.BooleanField(default=True, verbose_name='나에게 할당된 업무 자동 모니터링'),
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_watch_created',
            field=models.BooleanField(default=True, verbose_name='내가 생성한 업무 자동 모니터링'),
        ),
        migrations.AddField(
            model_name='profile',
            name='meeting_notification',
            field=models.BooleanField(default=True, verbose_name='회의록 참석 시 알림 수신'),
        ),
    ]
