# Generated by Django 6.0.6 on 2026-06-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_staffauth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffauth',
            old_name='assigned_project',
            new_name='default_project',
        ),
        migrations.RenameField(
            model_name='staffauth',
            old_name='is_staff',
            new_name='is_hq_staff',
        ),
    ]
