# Generated by Django 6.1 on 2026-09-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sign_image',
            field=models.ImageField(blank=True, help_text='전자결재 승인 시 결재란에 날인될 서명 또는 인장 이미지 (배경 투명 PNG 권장)', null=True, upload_to='users/signs/', verbose_name='결재 서명/인장 이미지'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sign_type',
            field=models.CharField(choices=[('STAMP', '도장(인장)'), ('SIGN', '서명(사인)')], default='STAMP', max_length=10, verbose_name='서명 유형'),
        ),
    ]
