# Generated by Django 6.0.4 on 2026-05-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_staffauth_project_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffauth',
            name='project_docs',
            field=models.CharField(choices=[('0', '권한없음'), ('1', '읽기권한'), ('2', '쓰기권한')], default='0', max_length=1, verbose_name='문서 소송 관리'),
        ),
    ]
