# Generated by Django 6.0.6 on 2026-07-09 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_auto_watch_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffauth',
            name='company',
        ),
    ]
