# Generated by Django 6.0.7 on 2026-07-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_meeting_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_manager',
            field=models.BooleanField(default=False, help_text='업무(redmine) 시스템 관리자인지 여부.', verbose_name='업무시스템 관리자'),
        ),
    ]
