# Generated by Django 6.0.6 on 2026-06-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_assigned_project_staffauth_default_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffauth',
            old_name='is_project_staff',
            new_name='is_pjt_staff',
        ),
        migrations.AlterField(
            model_name='staffauth',
            name='is_hq_staff',
            field=models.BooleanField(default=False, help_text='외부 관계자가 아닌 본사 직원(관리자)일 경우 선택', verbose_name='본사 근무 직원'),
        ),
    ]
