{{- if .Values.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ include "postgresql.v1.primary.fullname" . }}-{{ .Values.global.appMode }}-backup-pvc
spec:
  storageClassName: dump-backup-{{ .Values.global.appMode }}
  accessModes:
  {{- range .Values.volumes.backupAccessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.backupPvcStorage }}
{{- end }}
