services:

  postgres:
    container_name: ibs-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: my-db-name # 실제 데이터로 수정
      POSTGRES_USER: my-db-user # 실제 데이터로 수정
      POSTGRES_PASSWORD: my-db-password # 실제 데이터로 수정
      TZ: Asia/Seoul
    volumes:
      - ../volume/data:/var/lib/postgresql/data
      - ../volume/backups:/var/backups
      - ../volume/initdb/postgres:/docker-entrypoint-initdb.d

  mariadb:
    container_name: ibs-mariadb
    image: mariadb
    restart: always
    command: [ "--character-set-server=utf8", "--collation-server=utf8_unicode_ci" ]
    environment:
      MYSQL_DATABASE: my-db-name # 실제 데이터로 수정
      MYSQL_USER: my-db-user # 실제 데이터로 수정
      MYSQL_PASSWORD: my-db-password # 실제 데이터로 수정
      MYSQL_ROOT_PASSWORD: my-db-root-password # 실제 데이터로 수정
      TZ: Asia/Seoul
    volumes:
      - ../volume/mysql:/var/lib/mysql
      - ../volume/backups:/var/backups
      - ../volume/initdb/mariadb:/docker-entrypoint-initdb.d
  
  nginx:
    container_name: ibs-nginx
    build: docker/nginx
    image: dokube/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ../app/django/static:/django/static
      - ../app/django/media:/django/media
    depends_on:
      - web

  web:
    container_name: ibs-web
    build: docker/python
    image: dokube/django
    volumes:
      - ../app:/app
    environment:
      DATABASE_TYPE: mariadb  # mariadb | postgres (default: mariadb)
      DATABASE_PORT: 3306  # default: 3306
      DATABASE_NAME: my-db-name # 실제 데이터로 수정
      DATABASE_USER: my-db-user # 실제 데이터로 수정
      DATABASE_PASSWORD: my-db-password # 실제 데이터로 수정
      # AWS_STORAGE_BUCKET_NAME: aws-s3-bucket-name # 실제 데이터로 수정
      # AWS_ACCESS_KEY_ID: aws-access-key-id # 실제 데이터로 수정
      # AWS_SECRET_ACCESS_KEY: aws-secret-access-key # 실제 데이터로 수정
      DOMAIN_NAME: https://abc.com/ # 실제 데이터로 수정
      EMAIL_HOST: your-smtp-server.com # 실제 데이터로 수정
      EMAIL_PORT: 587   # 기본값은 587, 기본값과 다를 경우 실제 데이터로 수정
      EMAIL_HOST_USER: # your accessId or accessEmail # 실제 데이터로 수정
      EMAIL_HOST_PASSWORD: your-email-password # 실제 데이터로 수정
      EMAIL_DEFAULT_SENDER: sender name <your@djangoapp.com> # 실제 데이터로 수정
      DJANGO_SETTINGS_MODULE: _config.settings.local # Django settings 모드 지정 (.local or .prod)
