# Default values for IBS.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  appMode: prod
  dbType: "postgres"
  dbPassword: "{{ randAlphaNum 5 }}"
  nfsServerHost: "nfs-server-host"
  nfsPath: "nfs-path" # nfs volume path
  cicdServerHost: "cicd-server-host"
  cicdPath: "cicd-path" # cicd server path
  domainHost: "http://abc.com/"
  emailHost: "smtp-server.com" # your-smtp-server.com
  emailHostUser: "email@example.com" # 'your-email@example.com
  emailHostPassword: "{{ randAlphaNum 5 }}" # your-email-password
  defaultFromEmail: "email@example.com"

mariadb:
  enabled: false

postgres:
  enabled: true

  volumes:
    backupPvStorage: 200Mi
    backupPvcStorage: 200Mi

nginx:
  service:
    port: 8880