# Default values for IBS.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  appMode: prod
  dbType: "postgres" # postgres | mariadb
  dbPassword: "my-secret"
  nfsServerHost: "nfs-server-host"
  nfsPath: "nfs-path" # nfs volume path
  cicdServerHost: "cicd-server-host"
  cicdPath: "cicd-path" # cicd server path
  domainHost: "http://abc.com/"
  emailHost: "smtp-server.com" # your-smtp-server.com
  emailHostUser: "email@example.com" # 'your-email@example.com
  emailHostPassword: "my-email-host-secret" # your-email-password
  defaultFromEmail: "email@example.com"

mariadb:
  enabled: false

postgres:
  enabled: true

  auth:
    postgresPassword: "my-secret"
    password: "my-secret"
    replicationPassword: "my-secret"

  volumes:
    backupPvStorage: 200Mi
    backupPvcStorage: 200Mi

nginx:
  service:
    port: 8880

  ingress:
    hosts:
      - host: my-host.com # Host address
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: web-devbox-kr-cert
        hosts:
          - my-host.com
