# Generated by Django 6.1 on 2026-08-23 11:44

import _utils.file_upload
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='회사명')),
                ('tax_number', models.CharField(max_length=12, verbose_name='사업자등록번호')),
                ('ceo', models.CharField(max_length=20, verbose_name='대표자명')),
                ('org_number', models.CharField(max_length=14, verbose_name='법인등록번호')),
                ('business_cond', models.CharField(blank=True, max_length=20, verbose_name='업태')),
                ('business_even', models.CharField(blank=True, max_length=20, verbose_name='종목')),
                ('es_date', models.DateField(blank=True, null=True, verbose_name='설립일자')),
                ('op_date', models.DateField(blank=True, null=True, verbose_name='개업일자')),
                ('zipcode', models.CharField(blank=True, max_length=5, verbose_name='우편번호')),
                ('address1', models.CharField(blank=True, max_length=35, verbose_name='주소')),
                ('address2', models.CharField(blank=True, max_length=50, verbose_name='상세주소')),
                ('address3', models.CharField(blank=True, max_length=30, verbose_name='참고항목')),
                ('is_default', models.BooleanField(default=False, verbose_name='메인 회사 여부')),
            ],
            options={
                'verbose_name': '01. 회사 정보',
                'verbose_name_plural': '01. 회사 정보',
            },
        ),
        migrations.CreateModel(
            name='DutyTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='예: CEO, DIV_HEAD, HQ_HEAD, TEAM_LEADER 등', max_length=20, verbose_name='직책 코드')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='직책')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='설명')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='company.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '05. 직책 정보',
                'verbose_name_plural': '05. 직책 정보',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='예: E1, E2, E3 등', max_length=10, verbose_name='직위 코드')),
                ('name', models.CharField(db_index=True, help_text='예: 이사, 상무, 전무, 부사장, 사장, 부회장, 회장', max_length=20, verbose_name='임원 직위명')),
                ('rank_order', models.PositiveSmallIntegerField(default=1, help_text='낮을수록 상위 서열 또는 정렬 순서', verbose_name='서열 순서')),
                ('role_desc', models.CharField(blank=True, help_text='주요 역할 및 관장 부문 요약', max_length=255, verbose_name='역할/관장 설명')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_ranks', to='company.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '06. 임원 직위 정보',
                'verbose_name_plural': '06. 임원 직위 정보',
                'ordering': ['rank_order', 'id'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='직급 코드')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='역할')),
                ('promotion_criteria', models.TextField(blank=True, verbose_name='승급 기준')),
                ('min_promotion_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='최소 근속기간(년)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='company.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '03. 직급 정보',
                'verbose_name_plural': '03. 직급 정보',
                'ordering': ['id'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_logo', models.ImageField(help_text='4.5:1 ~ 5:1 크기 추천', null=True, upload_to=_utils.file_upload.get_company_image_path, verbose_name='일반 로고')),
                ('dark_logo', models.ImageField(help_text='4.5:1 ~ 5:1 크기 추천', null=True, upload_to=_utils.file_upload.get_company_image_path, verbose_name='다크 로고')),
                ('simple_logo', models.ImageField(help_text='1:1 크기 추천', null=True, upload_to=_utils.file_upload.get_company_image_path, verbose_name='심플 로고')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='직위')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='설명')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='company.company', verbose_name='회사')),
                ('grades', models.ManyToManyField(related_name='positions', to='company.jobgrade', verbose_name='직책')),
            ],
            options={
                'verbose_name': '04. 직위 정보',
                'verbose_name_plural': '04. 직위 정보',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_years', models.PositiveSmallIntegerField(default=3, help_text='승급 심사 대상이 되기 위한 최소 근속 년수', verbose_name='최소 체류기간(년)')),
                ('min_avg_grade_point', models.DecimalField(blank=True, decimal_places=2, help_text='최근 평가 평균 점수 기준 (예: 80.00)', max_digits=4, null=True, verbose_name='최소 평가 평점')),
                ('required_eval_grade', models.CharField(blank=True, help_text='예: 최근 2개년 평균 B+ 이상', max_length=20, verbose_name='최소 평가 등급 요건')),
                ('required_credentials', models.CharField(blank=True, help_text='예: 필수 교육 이수, 어학 기준, 관련 자격증 등', max_length=255, verbose_name='필수 역량/자격 요건')),
                ('disqualification_conditions', models.CharField(blank=True, help_text='예: 최근 1년 내 징계 처분 이력 등', max_length=255, verbose_name='승급 결격 사유')),
                ('description', models.TextField(blank=True, verbose_name='세부 기준 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_policies', to='company.company', verbose_name='회사')),
                ('current_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_policies_from', to='company.jobgrade', verbose_name='현재 직급')),
                ('target_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_policies_to', to='company.jobgrade', verbose_name='승급 대상 직급')),
            ],
            options={
                'verbose_name': '10. 직급 승급 정책',
                'verbose_name_plural': '10. 직급 승급 정책',
                'ordering': ['current_grade__id', 'target_grade__id'],
                'unique_together': {('company', 'current_grade', 'target_grade')},
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('1', '임원'), ('2', '직원')], default='1', max_length=1, verbose_name='구분')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='직원 성명')),
                ('id_number', models.CharField(max_length=14, verbose_name='주민등록번호')),
                ('personal_phone', models.CharField(max_length=13, verbose_name='휴대전화')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('date_join', models.DateField(verbose_name='입사일')),
                ('status', models.CharField(choices=[('1', '재직'), ('2', '휴직'), ('3', '퇴직신청'), ('4', '퇴직')], default='1', max_length=1, verbose_name='상태')),
                ('date_leave', models.DateField(blank=True, null=True, verbose_name='퇴사일')),
                ('is_hq_financial_officer', models.BooleanField(default=False, help_text='본사 프로젝트의 상세 자금 흐름을 열람할 수 있는 권한입니다. Django Admin 에서만 제어 합니다.', verbose_name='본사 금융 관리 권한')),
                ('is_hq_hr_officer', models.BooleanField(default=False, help_text='본사 프로젝트의 인사 관리 흐름을 열람할 수 있는 권한입니다. Django Admin 에서만 제어 합니다.', verbose_name='본사 인사 관리 권한')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='company.company', verbose_name='회사')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.jobgrade', verbose_name='직급 정보')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.position', verbose_name='직위 정보')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='유저 정보')),
            ],
            options={
                'verbose_name': '07. 직원 정보',
                'verbose_name_plural': '07. 직원 정보',
                'ordering': ['-date_join'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_year', models.PositiveSmallIntegerField(verbose_name='심사 연도')),
                ('tenure_years', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='현 직급 체류 년수')),
                ('avg_eval_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='평가 평균 점수')),
                ('status', models.CharField(choices=[('candidate', '심사 대상'), ('recommended', '부서 추천'), ('approved', '승진 확정'), ('rejected', '심사 탈락'), ('hold', '심사 보류')], default='candidate', max_length=15, verbose_name='심사 상태')),
                ('committee_review', models.TextField(blank=True, verbose_name='인사위원회 심의 의견')),
                ('promoted_date', models.DateField(blank=True, null=True, verbose_name='승진 발령일')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_candidates', to='company.company', verbose_name='회사')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='company.promotionpolicy', verbose_name='적용 승급 정책')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='company.staff', verbose_name='승급 대상자')),
            ],
            options={
                'verbose_name': '12. 승급 심사 및 발령',
                'verbose_name_plural': '12. 승급 심사 및 발령',
                'ordering': ['-eval_year', 'policy__current_grade__id', 'staff__name'],
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_type', models.CharField(choices=[('inside', '사내이사'), ('outside', '사외이사'), ('non_standing_director', '기타비상무이사'), ('auditor', '감사'), ('advisor', '고문/자문')], default='unregistered', max_length=25, verbose_name='상법상 지위')),
                ('is_registered', models.BooleanField(default=False, help_text='법인 등기부등본 등기 여부', verbose_name='등기 여부')),
                ('is_standing', models.BooleanField(default=True, help_text='상근 또는 비상근', verbose_name='상근 여부')),
                ('represent_type', models.CharField(choices=[('none', '해당없음'), ('sole', '단독대표'), ('joint', '공동대표'), ('each', '각자대표')], default='none', help_text='대표권 보유 형태', max_length=10, verbose_name='대표권 구분')),
                ('term_start', models.DateField(blank=True, null=True, verbose_name='임기 시작일(취임일)')),
                ('term_end', models.DateField(blank=True, null=True, verbose_name='임기 만료일')),
                ('appointed_date', models.DateField(blank=True, null=True, verbose_name='최초 선임일')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='비고')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='company.company', verbose_name='회사')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executives', to='company.executiverank', verbose_name='임원 직위')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executive', to='company.staff', verbose_name='임원')),
            ],
            options={
                'verbose_name': '08. 임원 등기/재임 정보',
                'verbose_name_plural': '08. 임원 등기/재임 정보',
                'ordering': ['rank__rank_order', 'staff__date_join', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='부서 간 상하 소속 관계에 의한 단계, 최상위 부서인 경우 1단계 이후 각 뎁스 마다 1씩 증가', verbose_name='레벨')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='부서')),
                ('task', models.CharField(blank=True, max_length=255, null=True, verbose_name='주요 업무')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company', verbose_name='회사')),
                ('upper_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departs', to='company.department', verbose_name='상위 부서')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departs', to='company.staff', verbose_name='책임자')),
            ],
            options={
                'verbose_name': '02. 부서 정보',
                'verbose_name_plural': '02. 부서 정보',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='기본 소속 여부 (직원당 1개만 True)', verbose_name='주 부서/보직 여부')),
                ('assigned_tasks', models.CharField(blank=True, help_text='예: 재무회계/인사/총무 총괄, 개발사업성 검토 등', max_length=255, verbose_name='담당 업무 요약')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='company.company', verbose_name='회사')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='company.department', verbose_name='소속 부서')),
                ('duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.dutytitle', verbose_name='직책')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='company.staff', verbose_name='직원')),
            ],
            options={
                'verbose_name': '09. 직원 보직/겸직 정보',
                'verbose_name_plural': '09. 직원 보직/겸직 목록',
                'ordering': ['-is_primary', 'id'],
                'unique_together': {('staff', 'department', 'duty')},
            },
        ),
        migrations.CreateModel(
            name='StaffEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_year', models.PositiveSmallIntegerField(verbose_name='평가 연도')),
                ('eval_period', models.CharField(choices=[('yearly', '연간'), ('1H', '상반기'), ('2H', '하반기')], default='yearly', max_length=10, verbose_name='평가 주기')),
                ('grade', models.CharField(choices=[('S', 'S (탁월)'), ('A', 'A (우수)'), ('B', 'B (보통)'), ('C', 'C (미흡)'), ('D', 'D (불량)')], max_length=5, verbose_name='평가 등급')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='100점 만점 환산 점수', max_digits=5, null=True, verbose_name='평가 점수')),
                ('achievement_summary', models.TextField(blank=True, verbose_name='주요 업적 요약')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='종합 의견')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='company.company', verbose_name='회사')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_staffs', to='company.staff', verbose_name='1차 평가자')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staffs', to='company.staff', verbose_name='2차 평가자/확인자')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='company.staff', verbose_name='피평가자')),
            ],
            options={
                'verbose_name': '11. 직원 인사 평가',
                'verbose_name_plural': '11. 직원 인사 평가',
                'ordering': ['-eval_year', 'eval_period', 'staff__name'],
                'unique_together': {('staff', 'eval_year', 'eval_period')},
            },
        ),
    ]
