# Generated by Django 6.0 on 2025-12-29 12:02

import company.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='회사명')),
                ('tax_number', models.CharField(max_length=12, verbose_name='사업자등록번호')),
                ('ceo', models.CharField(max_length=20, verbose_name='대표자명')),
                ('org_number', models.CharField(max_length=14, verbose_name='법인등록번호')),
                ('business_cond', models.CharField(blank=True, max_length=20, verbose_name='업태')),
                ('business_even', models.CharField(blank=True, max_length=20, verbose_name='종목')),
                ('es_date', models.DateField(blank=True, null=True, verbose_name='설립일자')),
                ('op_date', models.DateField(blank=True, null=True, verbose_name='개업일자')),
                ('zipcode', models.CharField(blank=True, max_length=5, verbose_name='우편번호')),
                ('address1', models.CharField(blank=True, max_length=35, verbose_name='주소')),
                ('address2', models.CharField(blank=True, max_length=50, verbose_name='상세주소')),
                ('address3', models.CharField(blank=True, max_length=30, verbose_name='참고항목')),
            ],
            options={
                'verbose_name': '01. 회사 정보',
                'verbose_name_plural': '01. 회사 정보',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='부서 간 상하 소속 관계에 의한 단계, 최상위 부서인 경우 1단계 이후 각 뎁스 마다 1씩 증가', verbose_name='레벨')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='부서')),
                ('task', models.CharField(blank=True, max_length=255, null=True, verbose_name='주요 업무')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company', verbose_name='회사')),
                ('upper_depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departs', to='company.department', verbose_name='상위 부서')),
            ],
            options={
                'verbose_name': '02. 부서 정보',
                'verbose_name_plural': '02. 부서 정보',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DutyTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=5, verbose_name='직책')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='설명')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='company.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '05. 직책 정보',
                'verbose_name_plural': '05. 직책 정보',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='직급')),
                ('promotion_period', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='승급표준년수')),
                ('criteria_new', models.CharField(blank=True, max_length=50, null=True, verbose_name='신입부여 기준')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='company.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '03. 직급 정보',
                'verbose_name_plural': '03. 직급 정보',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_logo', models.ImageField(help_text='4.5:1 ~ 5:1 크기 추천', null=True, upload_to=company.models.get_image_filename, verbose_name='일반 로고')),
                ('dark_logo', models.ImageField(help_text='4.5:1 ~ 5:1 크기 추천', null=True, upload_to=company.models.get_image_filename, verbose_name='다크 로고')),
                ('simple_logo', models.ImageField(help_text='1:1 크기 추천', null=True, upload_to=company.models.get_image_filename, verbose_name='심플 로고')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='직위')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='설명')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='company.company', verbose_name='회사')),
                ('grades', models.ManyToManyField(related_name='positions', to='company.jobgrade', verbose_name='직책')),
            ],
            options={
                'verbose_name': '04. 직위 정보',
                'verbose_name_plural': '04. 직위 정보',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('1', '임원'), ('2', '직원')], default='1', max_length=1, verbose_name='구분')),
                ('name', models.CharField(db_index=True, max_length=10, verbose_name='직원 성명')),
                ('id_number', models.CharField(max_length=14, verbose_name='주민등록번호')),
                ('personal_phone', models.CharField(max_length=13, verbose_name='휴대전화')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('date_join', models.DateField(verbose_name='입사일')),
                ('status', models.CharField(choices=[('1', '근무 중'), ('2', '휴직 중'), ('3', '퇴직신청'), ('4', '퇴사처리')], default='1', max_length=1, verbose_name='상태')),
                ('date_leave', models.DateField(blank=True, null=True, verbose_name='퇴사일')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='company.company', verbose_name='회사')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='company.department', verbose_name='부서 정보')),
                ('duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.dutytitle', verbose_name='직책 정보')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.jobgrade', verbose_name='직급 정보')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.position', verbose_name='직위 정보')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='유저 정보')),
            ],
            options={
                'verbose_name': '06. 직원 정보',
                'verbose_name_plural': '06. 직원 정보',
                'ordering': ['-date_join'],
            },
        ),
    ]
