# Generated by Django 6.1 on 2026-08-24 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotioncandidate',
            options={'ordering': ['-eval_year', 'policy__current_grade__id', 'staff__name'], 'verbose_name': '16. 승급 심사 및 발령', 'verbose_name_plural': '16. 승급 심사 및 발령'},
        ),
        migrations.AlterModelOptions(
            name='promotionpolicy',
            options={'ordering': ['current_grade__id', 'target_grade__id'], 'verbose_name': '14. 직급 승급 정책', 'verbose_name_plural': '14. 직급 승급 정책'},
        ),
        migrations.AlterModelOptions(
            name='staffevaluation',
            options={'ordering': ['-eval_year', 'eval_period', 'staff__name'], 'verbose_name': '15. 직원 인사 평가', 'verbose_name_plural': '15. 직원 인사 평가'},
        ),
        migrations.AddField(
            model_name='staff',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='계약직/파견직/위촉직의 계약 만료 예정일', null=True, verbose_name='계약 만료일'),
        ),
        migrations.AddField(
            model_name='staff',
            name='employment_type',
            field=models.CharField(choices=[('regular', '정규직'), ('contract', '계약직/기간제'), ('dispatched', '파견직'), ('commissioned', '위촉직/자문'), ('intern', '인턴/수습'), ('part_time', '파트타임/일용')], default='regular', max_length=20, verbose_name='고용 형태'),
        ),
        migrations.AddField(
            model_name='staff',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='수습 만료일'),
        ),
        migrations.CreateModel(
            name='PersonnelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('10', '채용/신규입사'), ('20', '승진/승급'), ('30', '부서이동(전보)'), ('40', '보직임면/겸직'), ('50', '휴직'), ('51', '복직'), ('60', '파견/전적'), ('70', '포상/표창'), ('80', '징계/문책'), ('90', '퇴사/면직')], max_length=2, verbose_name='발령 구분')),
                ('order_date', models.DateField(verbose_name='발령 일자(시행일)')),
                ('effective_end_date', models.DateField(blank=True, help_text='휴직/파견/겸직 등의 종료 예정일', null=True, verbose_name='종료 일자')),
                ('order_no', models.CharField(blank=True, max_length=50, verbose_name='발령 호수/문서번호')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='발령 사유/세부 내용')),
                ('is_processed', models.BooleanField(default=True, help_text='발령 저장 시 Staff 및 StaffAssignment 현재 상태 자동 갱신 여부', verbose_name='현상태 자동반영 여부')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_orders', to='company.company', verbose_name='회사')),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_orders', to='company.department', verbose_name='발령 부서')),
                ('new_duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_orders', to='company.dutytitle', verbose_name='발령 직책')),
                ('new_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_orders', to='company.jobgrade', verbose_name='발령 직급')),
                ('new_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_orders', to='company.position', verbose_name='발령 직위')),
                ('prev_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_orders', to='company.department', verbose_name='이전 부서')),
                ('prev_duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_orders', to='company.dutytitle', verbose_name='이전 직책')),
                ('prev_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_orders', to='company.jobgrade', verbose_name='이전 직급')),
                ('prev_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_orders', to='company.position', verbose_name='이전 직위')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='company.staff', verbose_name='대상 직원')),
            ],
            options={
                'verbose_name': '10. 인사 발령 이력',
                'verbose_name_plural': '10. 인사 발령 이력',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='근무처/기관명')),
                ('department_name', models.CharField(blank=True, max_length=50, verbose_name='부서/조직명')),
                ('position_title', models.CharField(blank=True, max_length=30, verbose_name='직위/직급')),
                ('assigned_tasks', models.CharField(blank=True, max_length=255, verbose_name='담당 업무')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('recognized_ratio', models.PositiveSmallIntegerField(default=100, help_text='호봉/승진 연수 인정 비율', verbose_name='경력 인정률(%)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='비고/퇴사사유')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_careers', to='company.company', verbose_name='회사')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='company.staff', verbose_name='직원')),
            ],
            options={
                'verbose_name': '11. 직원 경력 사항',
                'verbose_name_plural': '11. 직원 경력 사항',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='자격/면허명')),
                ('grade', models.CharField(blank=True, help_text='예: 특급기술자, 1급, 공인중개사 등', max_length=30, verbose_name='등급/급수')),
                ('cert_number', models.CharField(blank=True, max_length=50, verbose_name='자격/등록 번호')),
                ('issuer', models.CharField(blank=True, max_length=50, verbose_name='발급 기관')),
                ('acquired_date', models.DateField(verbose_name='취득일자')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='만료/갱신일자')),
                ('has_allowance', models.BooleanField(default=False, verbose_name='자격 수당 지급 여부')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='비고')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_certificates', to='company.company', verbose_name='회사')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='company.staff', verbose_name='직원')),
            ],
            options={
                'verbose_name': '12. 직원 자격/면허',
                'verbose_name_plural': '12. 직원 자격/면허',
                'ordering': ['-acquired_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffRewardPunishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.CharField(choices=[('reward', '포상/표창'), ('punish', '징계/문책')], default='reward', max_length=10, verbose_name='구분')),
                ('type_name', models.CharField(help_text='예: 우수사원상, 견책, 감봉, 정직 등', max_length=50, verbose_name='포상/징계 항목명')),
                ('action_date', models.DateField(verbose_name='처분/수여 일자')),
                ('expire_date', models.DateField(blank=True, help_text='승진 결격 효력 기간 등', null=True, verbose_name='징계 효력 만료일')),
                ('reason', models.TextField(verbose_name='사유/근거')),
                ('organization', models.CharField(blank=True, max_length=50, verbose_name='수여/처분 기관(부서)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='비고')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_rewards_punishments', to='company.company', verbose_name='회사')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards_punishments', to='company.staff', verbose_name='직원')),
            ],
            options={
                'verbose_name': '13. 직원 상벌 이력',
                'verbose_name_plural': '13. 직원 상벌 이력',
                'ordering': ['-action_date', '-id'],
            },
        ),
    ]
