# Generated by Django 6.0.7 on 2026-07-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_hq_financial_officer',
            field=models.BooleanField(default=False, help_text='본사 프로젝트의 상세 자금 흐름을 열람할 수 있는 은밀한 권한입니다. Django Admin에서만 제어합니다.', verbose_name='본사 금융 총괄 권한'),
        ),
    ]
