# Generated by Django 6.0.6 on 2026-07-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='기본 회사 여부'),
        ),
    ]
