# Generated by Django 6.0.6 on 2026-07-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='메인 회사 여부'),
        ),
    ]
