# Generated by Django 6.0.7 on 2026-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_staff_is_hq_financial_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_hq_financial_officer',
            field=models.BooleanField(default=False, help_text='본사 프로젝트의 상세 자금 흐름을 열람할 수 있는 권한입니다. Django Admin 에서만 제어 합니다.', verbose_name='본사 금융 관리 권한'),
        ),
    ]
