# Generated by Django 6.1 on 2026-08-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_hq_hr_officer',
            field=models.BooleanField(default=False, help_text='본사 프로젝트의 인사 관리 흐름을 열람할 수 있는 권한입니다. Django Admin 에서만 제어 합니다.', verbose_name='본사 인사 관리 권한'),
        ),
    ]
