# Generated by Django 6.1 on 2026-08-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_standardize_form_template_choices'),
        ('company', '0002_alter_promotioncandidate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeaveUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', '연차 (1일)'), ('half_am', '오전 반차 (0.5일)'), ('half_pm', '오후 반차 (0.5일)'), ('quarter', '반반차 (0.25일)'), ('official', '공가/예비군 (차감 없음)'), ('sick', '병가'), ('condolence', '경조 휴가 (차감 없음)'), ('reward', '포상 휴가'), ('substitute', '대체 휴가'), ('other', '기타 휴가')], default='annual', max_length=20, verbose_name='휴가 구분')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('deduction_days', models.DecimalField(decimal_places=2, default=1.0, help_text='연차에서 실제 차감되는 일수 (예: 1.0, 0.5, 0.25, 0.0)', max_digits=4, verbose_name='차감 일수')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='휴가 사유')),
                ('is_cancelled', models.BooleanField(default=False, help_text='결재 취소/반려 시 차감 복구용', verbose_name='취소 여부')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approval_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_usages', to='approval.approvaldocument', verbose_name='연관 전자결재 문서')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_usages', to='company.company', verbose_name='회사')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_usages', to='company.staff', verbose_name='직원')),
            ],
            options={
                'verbose_name': '15. 직원 휴가/연차 사용 기록',
                'verbose_name_plural': '15. 직원 휴가/연차 사용 기록',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffLeaveQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True, verbose_name='대상 연도')),
                ('granted_days', models.DecimalField(decimal_places=2, default=15.0, help_text='근로기준법 기준 연차 발생 일수', max_digits=4, verbose_name='기본 발생 연차')),
                ('carry_over_days', models.DecimalField(decimal_places=2, default=0.0, help_text='전년도 이월 또는 수동 조정 일수', max_digits=4, verbose_name='이월/조정 연차')),
                ('reward_days', models.DecimalField(decimal_places=2, default=0.0, help_text='장기근속 가산 또는 포상 부여 일수', max_digits=4, verbose_name='포상/가산 연차')),
                ('valid_start', models.DateField(verbose_name='사용 가능 시작일')),
                ('valid_end', models.DateField(verbose_name='사용 가능 만료일')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='비고')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_quotas', to='company.company', verbose_name='회사')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_quotas', to='company.staff', verbose_name='직원')),
            ],
            options={
                'verbose_name': '14. 직원 연차 부여/잔여',
                'verbose_name_plural': '14. 직원 연차 부여/잔여',
                'ordering': ['-year', 'staff'],
                'unique_together': {('staff', 'year')},
            },
        ),
    ]
