# Generated by Django 6.1 on 2026-08-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_staffleaveusage_staffleavequota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executive',
            options={'ordering': ['rank__rank_order', 'staff__date_join', 'id'], 'verbose_name': '09. 임원 등기/재임 정보', 'verbose_name_plural': '09. 임원 등기/재임 정보'},
        ),
        migrations.AlterModelOptions(
            name='promotioncandidate',
            options={'ordering': ['-eval_year', 'policy__current_grade__id', 'staff__name'], 'verbose_name': '18. 승급 심사 및 발령', 'verbose_name_plural': '18. 승급 심사 및 발령'},
        ),
        migrations.AlterModelOptions(
            name='promotionpolicy',
            options={'ordering': ['current_grade__id', 'target_grade__id'], 'verbose_name': '17. 직급 승급 정책', 'verbose_name_plural': '17. 직급 승급 정책'},
        ),
        migrations.AlterModelOptions(
            name='staffassignment',
            options={'ordering': ['-is_primary', 'id'], 'verbose_name': '08. 직원 보직/겸직 정보', 'verbose_name_plural': '08. 직원 보직/겸직 목록'},
        ),
        migrations.AlterModelOptions(
            name='staffevaluation',
            options={'ordering': ['-eval_year', 'eval_period', 'staff__name'], 'verbose_name': '16. 직원 인사 평가', 'verbose_name_plural': '16. 직원 인사 평가'},
        ),
    ]
