# Generated by Django 6.1 on 2026-08-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_staff_is_hq_hr_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='기본 소속 여부 (직원당 1개만 True)', verbose_name='주 부서/보직 여부')),
                ('assigned_tasks', models.CharField(blank=True, help_text='예: 재무회계/인사/총무 총괄, 개발사업성 검토 등', max_length=255, verbose_name='담당 업무 요약')),
                ('represent_type', models.CharField(blank=True, choices=[('sole', '단독대표'), ('joint', '공동대표'), ('each', '각자대표')], help_text='대표이사 직책인 경우 대표권 형태', max_length=10, null=True, verbose_name='대표권 구분')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='company.company', verbose_name='회사')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='company.department', verbose_name='소속 부서')),
                ('duty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.dutytitle', verbose_name='직책')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.position', verbose_name='직위')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='company.staff', verbose_name='직원')),
            ],
            options={
                'verbose_name': '07. 직원 보직/겸직 정보',
                'verbose_name_plural': '07. 직원 보직/겸직 목록',
                'ordering': ['-is_primary', 'id'],
                'unique_together': {('staff', 'department', 'duty')},
            },
        ),
    ]
