# Generated by Django 6.1 on 2026-08-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_staffassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='duty',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
    ]
