# Generated by Django 6.1 on 2026-08-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_executive_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_hq_financial_officer',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_hq_hr_officer',
        ),
    ]
