# Generated by Django 6.1 on 2026-08-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_staff_department_remove_staff_duty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobgrade',
            name='criteria_new',
        ),
        migrations.RemoveField(
            model_name='jobgrade',
            name='promotion_period',
        ),
        migrations.AddField(
            model_name='jobgrade',
            name='code',
            field=models.CharField(default='c1', max_length=10, verbose_name='코드'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobgrade',
            name='min_promotion_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='최소 체류기간(년)'),
        ),
        migrations.AddField(
            model_name='jobgrade',
            name='promotion_criteria',
            field=models.TextField(blank=True, verbose_name='승급 기준'),
        ),
        migrations.AddField(
            model_name='jobgrade',
            name='role',
            field=models.CharField(blank=True, max_length=100, verbose_name='역할'),
        ),
    ]
