# Generated by Django 6.1 on 2026-09-04 11:49

import _utils.file_upload
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_staff_is_hq_financial_officer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_type', models.CharField(choices=[('CORP_SEAL', '법인인감 (대표이사 직인)'), ('USAGE_SEAL', '사용인감'), ('DEPT_SEAL', '부서인감/직인'), ('SIGN', '대표자/부서장 서명'), ('OMIT', '직인생략')], default='USAGE_SEAL', max_length=20, verbose_name='인장 종류')),
                ('name', models.CharField(help_text='예: 대표이사 법인인감, 분양계약 전용 사용인감 1호', max_length=50, verbose_name='인장 명칭')),
                ('seal_image', models.ImageField(blank=True, help_text='배경이 투명한 PNG 권장 (정방형)', null=True, upload_to=_utils.file_upload.get_company_image_path, verbose_name='인장 이미지')),
                ('manager', models.CharField(blank=True, default='', max_length=50, verbose_name='관리 책임자/부서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seals', to='company.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '03. 회사 인장',
                'verbose_name_plural': '03. 회사 인장',
                'ordering': ['-is_active', 'seal_type', 'created'],
            },
        ),
    ]
