# Generated by Django 6.1 on 2026-08-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_jobgrade_criteria_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobgrade',
            name='min_promotion_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='최소 근속기간(년)'),
        ),
    ]
