# Generated by Django 6.1 on 2026-08-20 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_jobgrade_min_promotion_years'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobgrade',
            unique_together={('company', 'code')},
        ),
    ]
