# Generated by Django 6.1 on 2026-09-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='en_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='영문명'),
        ),
    ]
