# Generated by Django 6.1 on 2026-09-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_en_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='en_name',
            field=models.CharField(blank=True, default='', help_text='영문 회사명', max_length=50, verbose_name='영문명'),
        ),
    ]
