# Generated by Django 6.1 on 2026-08-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_jobgrade_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobgrade',
            name='name',
        ),
        migrations.AlterField(
            model_name='jobgrade',
            name='code',
            field=models.CharField(max_length=10, verbose_name='직급 코드'),
        ),
    ]
