# Generated by Django 6.1 on 2026-08-20 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_jobgrade_name_alter_jobgrade_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-date_join'], 'verbose_name': '07. 직원 정보', 'verbose_name_plural': '07. 직원 정보'},
        ),
        migrations.AlterModelOptions(
            name='staffassignment',
            options={'ordering': ['-is_primary', 'id'], 'verbose_name': '09. 직원 보직/겸직 정보', 'verbose_name_plural': '09. 직원 보직/겸직 목록'},
        ),
        migrations.RemoveField(
            model_name='staffassignment',
            name='position',
        ),
        migrations.RemoveField(
            model_name='staffassignment',
            name='represent_type',
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.position', verbose_name='직위 정보'),
        ),
        migrations.CreateModel(
            name='ExecutiveRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='예: E1, E2, E3 등', max_length=10, verbose_name='직위 코드')),
                ('name', models.CharField(db_index=True, help_text='예: 이사, 상무, 전무, 부사장, 사장, 부회장, 회장', max_length=20, verbose_name='임원 직위명')),
                ('rank_order', models.PositiveSmallIntegerField(default=1, help_text='낮을수록 상위 서열 또는 정렬 순서', verbose_name='서열 순서')),
                ('role_desc', models.CharField(blank=True, help_text='주요 역할 및 관장 부문 요약', max_length=255, verbose_name='역할/관장 설명')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_ranks', to='company.company', verbose_name='회사')),
            ],
            options={
                'verbose_name': '06. 임원 직위 정보',
                'verbose_name_plural': '06. 임원 직위 정보',
                'ordering': ['rank_order', 'id'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_type', models.CharField(choices=[('inside', '사내이사'), ('outside', '사외이사'), ('non_standing_director', '기타비상무이사'), ('auditor', '감사'), ('unregistered', '미등기임원'), ('advisor', '고문/자문')], default='unregistered', max_length=25, verbose_name='상법상 지위')),
                ('is_registered', models.BooleanField(default=False, help_text='법인 등기부등본 등기 여부', verbose_name='등기 여부')),
                ('is_standing', models.BooleanField(default=True, help_text='상근 또는 비상근', verbose_name='상근 여부')),
                ('represent_type', models.CharField(choices=[('none', '해당없음'), ('sole', '단독대표'), ('joint', '공동대표'), ('each', '각자대표')], default='none', help_text='대표권 보유 형태', max_length=10, verbose_name='대표권 구분')),
                ('term_start', models.DateField(blank=True, null=True, verbose_name='임기 시작일(취임일)')),
                ('term_end', models.DateField(blank=True, null=True, verbose_name='임기 만료일')),
                ('appointed_date', models.DateField(blank=True, null=True, verbose_name='최초 선임일')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='비고')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='company.company', verbose_name='회사')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executive', to='company.staff', verbose_name='임원')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executives', to='company.executiverank', verbose_name='임원 직위')),
            ],
            options={
                'verbose_name': '08. 임원 등기/재임 정보',
                'verbose_name_plural': '08. 임원 등기/재임 정보',
                'ordering': ['rank__rank_order', 'staff__date_join', 'id'],
            },
        ),
    ]
