# Generated by Django 6.1 on 2026-09-10 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_company_en_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executive',
            options={'ordering': ['rank__sort_order', 'staff__date_join', 'id'], 'verbose_name': '09. 임원 등기/재임 정보', 'verbose_name_plural': '09. 임원 등기/재임 정보'},
        ),
        migrations.AlterModelOptions(
            name='executiverank',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '06. 임원 직위 정보', 'verbose_name_plural': '06. 임원 직위 정보'},
        ),
        migrations.AlterUniqueTogether(
            name='executiverank',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='executive',
            name='director_type',
        ),
        migrations.AddField(
            model_name='executive',
            name='executive_type',
            field=models.CharField(choices=[('inside', '사내이사'), ('outside', '사외이사'), ('non_standing', '기타비상무이사'), ('auditor', '감사'), ('advisor', '고문')], default='inside', help_text='임원의 법적·조직적 구분', max_length=25, verbose_name='임원 구분'),
        ),
        migrations.AddField(
            model_name='executiverank',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='정렬 순서'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='appointed_date',
            field=models.DateField(blank=True, null=True, verbose_name='최초 임원 선임일'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='rank',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='executives', to='company.executiverank', verbose_name='임원 직위'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executive',
            name='represent_type',
            field=models.CharField(choices=[('none', '대표권 없음'), ('sole', '단독대표'), ('joint', '공동대표'), ('each', '각자대표')], default='none', help_text='대표권 보유 형태', max_length=10, verbose_name='대표권 구분'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='term_end',
            field=models.DateField(blank=True, null=True, verbose_name='현재 임기 만료일'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='term_start',
            field=models.DateField(blank=True, null=True, verbose_name='현재 임기 시작일(취임일)'),
        ),
        migrations.AlterField(
            model_name='executiverank',
            name='code',
            field=models.CharField(help_text='예: E1, E2, E3.., A01, V01', max_length=10, verbose_name='직위 코드'),
        ),
        migrations.AlterField(
            model_name='executiverank',
            name='name',
            field=models.CharField(db_index=True, help_text='예: 회장, 부회장, 사장, 상무, 이사, 감사, 고문', max_length=20, verbose_name='임원 직위명'),
        ),
        migrations.AddConstraint(
            model_name='executiverank',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_executive_rank_name'),
        ),
        migrations.AddConstraint(
            model_name='executiverank',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_executive_rank_code'),
        ),
        migrations.RemoveField(
            model_name='executiverank',
            name='rank_order',
        ),
    ]
