# Generated by Django 6.1 on 2026-08-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_staff_options_alter_staffassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_years', models.PositiveSmallIntegerField(default=3, help_text='승급 심사 대상이 되기 위한 최소 근속 년수', verbose_name='최소 체류기간(년)')),
                ('min_avg_grade_point', models.DecimalField(blank=True, decimal_places=2, help_text='최근 평가 평균 점수 기준 (예: 80.00)', max_digits=4, null=True, verbose_name='최소 평가 평점')),
                ('required_eval_grade', models.CharField(blank=True, help_text='예: 최근 2개년 평균 B+ 이상', max_length=20, verbose_name='최소 평가 등급 요건')),
                ('required_credentials', models.CharField(blank=True, help_text='예: 필수 교육 이수, 어학 기준, 관련 자격증 등', max_length=255, verbose_name='필수 역량/자격 요건')),
                ('disqualification_conditions', models.CharField(blank=True, help_text='예: 최근 1년 내 징계 처분 이력 등', max_length=255, verbose_name='승급 결격 사유')),
                ('description', models.TextField(blank=True, verbose_name='세부 기준 설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_policies', to='company.company', verbose_name='회사')),
                ('current_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_policies_from', to='company.jobgrade', verbose_name='현재 직급')),
                ('target_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_policies_to', to='company.jobgrade', verbose_name='승급 대상 직급')),
            ],
            options={
                'verbose_name': '10. 직급 승급 정책',
                'verbose_name_plural': '10. 직급 승급 정책',
                'ordering': ['current_grade__id', 'target_grade__id'],
                'unique_together': {('company', 'current_grade', 'target_grade')},
            },
        ),
        migrations.CreateModel(
            name='PromotionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_year', models.PositiveSmallIntegerField(verbose_name='심사 연도')),
                ('tenure_years', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='현 직급 체류 년수')),
                ('avg_eval_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='평가 평균 점수')),
                ('status', models.CharField(choices=[('candidate', '심사 대상'), ('recommended', '부서 추천'), ('approved', '승진 확정'), ('rejected', '심사 탈락'), ('hold', '심사 보류')], default='candidate', max_length=15, verbose_name='심사 상태')),
                ('committee_review', models.TextField(blank=True, verbose_name='인사위원회 심의 의견')),
                ('promoted_date', models.DateField(blank=True, null=True, verbose_name='승진 발령일')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_candidates', to='company.company', verbose_name='회사')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='company.staff', verbose_name='승급 대상자')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='company.promotionpolicy', verbose_name='적용 승급 정책')),
            ],
            options={
                'verbose_name': '12. 승급 심사 및 발령',
                'verbose_name_plural': '12. 승급 심사 및 발령',
                'ordering': ['-eval_year', 'policy__current_grade__id', 'staff__name'],
            },
        ),
        migrations.CreateModel(
            name='StaffEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_year', models.PositiveSmallIntegerField(verbose_name='평가 연도')),
                ('eval_period', models.CharField(choices=[('yearly', '연간'), ('1H', '상반기'), ('2H', '하반기')], default='yearly', max_length=10, verbose_name='평가 주기')),
                ('grade', models.CharField(choices=[('S', 'S (탁월)'), ('A', 'A (우수)'), ('B', 'B (보통)'), ('C', 'C (미흡)'), ('D', 'D (불량)')], max_length=5, verbose_name='평가 등급')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='100점 만점 환산 점수', max_digits=5, null=True, verbose_name='평가 점수')),
                ('achievement_summary', models.TextField(blank=True, verbose_name='주요 업적 요약')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='종합 의견')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='company.company', verbose_name='회사')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_staffs', to='company.staff', verbose_name='1차 평가자')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staffs', to='company.staff', verbose_name='2차 평가자/확인자')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='company.staff', verbose_name='피평가자')),
            ],
            options={
                'verbose_name': '11. 직원 인사 평가',
                'verbose_name_plural': '11. 직원 인사 평가',
                'ordering': ['-eval_year', 'eval_period', 'staff__name'],
                'unique_together': {('staff', 'eval_year', 'eval_period')},
            },
        ),
    ]
