# Generated by Django 6.1 on 2026-09-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_executive_options_alter_executiverank_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='연락처(직접입력)'),
        ),
        migrations.AddField(
            model_name='executive',
            name='name',
            field=models.CharField(blank=True, help_text='시스템 계정(Staff)이 없는 경우 필수', max_length=100, null=True, verbose_name='이름(직접입력)'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executive', to='company.staff', verbose_name='임원'),
        ),
    ]
