# Generated by Django 6.1 on 2026-09-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_executive_contact_executive_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='연락처(직접입력)'),
        ),
        migrations.AlterField(
            model_name='executive',
            name='name',
            field=models.CharField(blank=True, default='', help_text='시스템 계정(Staff)이 없는 경우 필수', max_length=100, verbose_name='이름(직접입력)'),
        ),
    ]
