# Generated by Django 6.1 on 2026-08-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_promotionpolicy_promotioncandidate_staffevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutytitle',
            name='code',
            field=models.CharField(blank=True, help_text='예: CEO, DIV_HEAD, HQ_HEAD, TEAM_LEADER 등', max_length=20, verbose_name='직책 코드'),
        ),
        migrations.AlterField(
            model_name='dutytitle',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='직책'),
        ),
    ]
