# Generated by Django 6.1 on 2026-09-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_executive_contact_alter_executive_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='direct_fax',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='직장팩스'),
        ),
        migrations.AddField(
            model_name='staff',
            name='direct_phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='직장전화'),
        ),
    ]
