# Generated by Django 6.1 on 2026-08-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_dutytitle_code_alter_dutytitle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='director_type',
            field=models.CharField(choices=[('inside', '사내이사'), ('outside', '사외이사'), ('non_standing_director', '기타비상무이사'), ('auditor', '감사'), ('advisor', '고문/자문')], default='unregistered', max_length=25, verbose_name='상법상 지위'),
        ),
    ]
