# Generated by Django 6.1 on 2026-09-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_staff_direct_fax_staff_direct_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='대표이메일'),
        ),
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='대표팩스'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='대표전화'),
        ),
    ]
