# Generated by Django 6.1 on 2026-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_alter_executive_director_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('1', '재직'), ('2', '휴직'), ('3', '퇴직신청'), ('4', '퇴직')], default='1', max_length=1, verbose_name='상태'),
        ),
    ]
