# Generated by Django 6.1 on 2026-09-11 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_company_email_company_fax_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyseal',
            name='final_approval_duty',
            field=models.ForeignKey(blank=True, help_text='이 인장을 날인하기 위한 최소 최종 전결 직책 (미지정 시 대표이사까지 상신)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.dutytitle', verbose_name='전결 직책 자격'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='final_dept_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='예: 1=본부장 전결, 2=팀장/소장 전결 가능 (미지정 시 대표이사까지 상신)', null=True, verbose_name='전결 부서 레벨'),
        ),
    ]
