# Generated by Django 6.1.1 on 2026-09-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_companyseal_final_approval_duty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyseal',
            name='seal_type',
            field=models.CharField(choices=[('CORP_SEAL', '법인인감 (대표이사 직인)'), ('USAGE_SEAL', '사용인감'), ('DEPT_SEAL', '부서인감/직인'), ('OMIT', '직인생략')], default='USAGE_SEAL', max_length=20, verbose_name='인장 종류'),
        ),
    ]
