# Generated by Django 6.1.1 on 2026-09-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_alter_companyseal_seal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyseal',
            name='manager',
        ),
        migrations.AddField(
            model_name='companyseal',
            name='custodian',
            field=models.CharField(blank=True, default='', help_text='예: 본사 재경팀 금고, (주)고성개발컨설팅 김실장', max_length=100, verbose_name='실물 보관처 / 수임자'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='custody_type',
            field=models.CharField(choices=[('internal', '사내 보관 (본사/현장)'), ('external', '외부 교부 (용역사/대행사/법무사 등)')], default='internal', help_text='사내 금고 보관 또는 외부 협력사(토지용역사, 분양대행사 등) 교부', max_length=15, verbose_name='보관 장소 구분'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='description',
            field=models.TextField(blank=True, default='', help_text='교부 사유, 회수 이력 등', verbose_name='관리 비고/이력'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='internal_manager',
            field=models.ForeignKey(blank=True, help_text='외부 교부 시에도 본사에서 교부/회수를 총괄하는 사내 책임 임직원', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_seals', to='company.staff', verbose_name='사내 총괄 관리책임자'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='purpose',
            field=models.CharField(blank=True, default='', help_text='예: 토지매매계약 체결 전용, 인허가 관공서 제출용, 분양계약 체결 전용', max_length=200, verbose_name='지정 용도/사용 범위'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='valid_from',
            field=models.DateField(blank=True, null=True, verbose_name='교부/유효 시작일'),
        ),
        migrations.AddField(
            model_name='companyseal',
            name='valid_until',
            field=models.DateField(blank=True, help_text='용역 계약 만료 등에 따른 회수 예정일 (미지정 시 무기한)', null=True, verbose_name='교부 만료일 / 사용 기한'),
        ),
        migrations.AlterField(
            model_name='companyseal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='사용 가능 여부'),
        ),
        migrations.AlterField(
            model_name='companyseal',
            name='name',
            field=models.CharField(help_text='예: 대표이사 법인인감, 분양계약 전용 사용인감 1호, 토지매매계약 전용 사용인감', max_length=50, verbose_name='인장 명칭'),
        ),
        migrations.AlterField(
            model_name='companyseal',
            name='seal_type',
            field=models.CharField(choices=[('CORP_SEAL', '법인인감 (대표이사 직인)'), ('USAGE_SEAL', '사용인감'), ('DEPT_SEAL', '부서/현장 직인'), ('OMIT', '직인생략')], default='USAGE_SEAL', max_length=20, verbose_name='인장 종류'),
        ),
    ]
