# Generated by Django 6.1.1 on 2026-09-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_remove_companyseal_manager_companyseal_custodian_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyseal',
            options={'ordering': ['-is_active', 'seal_type', 'created'], 'verbose_name': '02. 회사 인장', 'verbose_name_plural': '02. 회사 인장'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id'], 'verbose_name': '03. 부서 정보', 'verbose_name_plural': '03. 부서 정보'},
        ),
        migrations.AlterModelOptions(
            name='dutytitle',
            options={'ordering': ['id'], 'verbose_name': '07. 직책 정보', 'verbose_name_plural': '07. 직책 정보'},
        ),
        migrations.AlterModelOptions(
            name='jobgrade',
            options={'ordering': ['id'], 'verbose_name': '04. 직급 정보', 'verbose_name_plural': '04. 직급 정보'},
        ),
        migrations.AlterModelOptions(
            name='personnelorder',
            options={'ordering': ['-order_date', '-id'], 'verbose_name': '11. 인사 발령 이력', 'verbose_name_plural': '11. 인사 발령 이력'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['id'], 'verbose_name': '05. 직위 정보', 'verbose_name_plural': '05. 직위 정보'},
        ),
        migrations.AlterModelOptions(
            name='promotioncandidate',
            options={'ordering': ['-eval_year', 'policy__current_grade__id', 'staff__name'], 'verbose_name': '19. 승급 심사 및 발령', 'verbose_name_plural': '19. 승급 심사 및 발령'},
        ),
        migrations.AlterModelOptions(
            name='promotionpolicy',
            options={'ordering': ['current_grade__id', 'target_grade__id'], 'verbose_name': '18. 직급 승급 정책', 'verbose_name_plural': '18. 직급 승급 정책'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-date_join'], 'verbose_name': '08. 직원 정보', 'verbose_name_plural': '08. 직원 정보'},
        ),
        migrations.AlterModelOptions(
            name='staffassignment',
            options={'ordering': ['-is_primary', 'id'], 'verbose_name': '10. 직원 보직/겸직 정보', 'verbose_name_plural': '10. 직원 보직/겸직 목록'},
        ),
        migrations.AlterModelOptions(
            name='staffcareer',
            options={'ordering': ['-start_date', '-id'], 'verbose_name': '12. 직원 경력 사항', 'verbose_name_plural': '12. 직원 경력 사항'},
        ),
        migrations.AlterModelOptions(
            name='staffcertificate',
            options={'ordering': ['-acquired_date', '-id'], 'verbose_name': '13. 직원 자격/면허', 'verbose_name_plural': '13. 직원 자격/면허'},
        ),
        migrations.AlterModelOptions(
            name='staffevaluation',
            options={'ordering': ['-eval_year', 'eval_period', 'staff__name'], 'verbose_name': '17. 직원 인사 평가', 'verbose_name_plural': '17. 직원 인사 평가'},
        ),
        migrations.AlterModelOptions(
            name='staffleavequota',
            options={'ordering': ['-year', 'staff'], 'verbose_name': '15. 직원 연차 부여/잔여', 'verbose_name_plural': '15. 직원 연차 부여/잔여'},
        ),
        migrations.AlterModelOptions(
            name='staffleaveusage',
            options={'ordering': ['-start_date', '-id'], 'verbose_name': '16. 직원 휴가/연차 사용 기록', 'verbose_name_plural': '16. 직원 휴가/연차 사용 기록'},
        ),
        migrations.AlterModelOptions(
            name='staffrewardpunishment',
            options={'ordering': ['-action_date', '-id'], 'verbose_name': '14. 직원 상벌 이력', 'verbose_name_plural': '14. 직원 상벌 이력'},
        ),
    ]
