# Generated by Django 6.1.1 on 2026-09-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_update_document_type_abbreviation_codes'),
        ('company', '0018_alter_companyseal_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyseal',
            name='route_template',
            field=models.ForeignKey(blank=True, help_text='부서/현장 직인(DEPT_SEAL)을 전자결재 공문에 사용하기 위해 연동할 수동 결재선 템플릿', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_seals', to='approval.routetemplate', verbose_name='연동 전결 결재선 템플릿'),
        ),
    ]
