# Generated by Django 6.1 on 2026-09-06 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0003_initial'),
        ('items', '0002_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_pay', models.PositiveIntegerField(default=0, verbose_name='기본급/일비')),
                ('contract_count', models.PositiveIntegerField(default=0, verbose_name='계약 건수')),
                ('commission_amount', models.PositiveBigIntegerField(default=0, verbose_name='계약 인센티브 합계')),
                ('bonus_amount', models.PositiveIntegerField(default=0, verbose_name='보너스/활동비')),
                ('deduction_amount', models.PositiveIntegerField(default=0, verbose_name='공제/환수액')),
                ('gross_amount', models.PositiveBigIntegerField(default=0, help_text='기본급 + 인센티브 + 보너스 - 공제액', verbose_name='총 지급액 (세전)')),
                ('income_tax', models.PositiveIntegerField(default=0, verbose_name='사업소득세 (3%)')),
                ('local_income_tax', models.PositiveIntegerField(default=0, verbose_name='지방소득세 (0.3%)')),
                ('total_tax', models.PositiveIntegerField(default=0, verbose_name='원천징수 합계 (3.3%)')),
                ('net_amount', models.PositiveBigIntegerField(default=0, verbose_name='실지급액 (세후)')),
                ('pay_status', models.CharField(choices=[('1', '대기'), ('2', '승인'), ('3', '지급 완료'), ('4', '지급 보류')], default='1', max_length=2, verbose_name='지급 상태')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='실제 지급일')),
                ('bank_name', models.CharField(blank=True, default='', max_length=30, verbose_name='입금 은행')),
                ('account_number', models.CharField(blank=True, default='', max_length=50, verbose_name='입금 계좌')),
                ('account_holder', models.CharField(blank=True, default='', max_length=50, verbose_name='예금주')),
                ('note', models.TextField(blank=True, default='', verbose_name='비고/정산 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '07. 수수료 지급 명세',
                'verbose_name_plural': '07. 수수료 지급 명세 목록',
                'ordering': ['period', 'sales_person__duty', 'sales_person__name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 84A 정규 분양 수수료 기준', max_length=100, verbose_name='정책명')),
                ('agent_fee', models.PositiveIntegerField(default=0, verbose_name='상담사 건당 수수료 (원)')),
                ('leader_fee', models.PositiveIntegerField(default=0, verbose_name='팀장 건당 수수료 (원)')),
                ('director_fee', models.PositiveIntegerField(default=0, verbose_name='본부장 건당 수수료 (원)')),
                ('agency_fee', models.PositiveIntegerField(default=0, verbose_name='대행사 건당 수수료 (원)')),
                ('pay_condition', models.CharField(choices=[('1', '계약금 100% 완납 시 전액 지급'), ('2', '계약금 1차 납부 시 50%, 2차 완납 시 50% 분할 지급'), ('3', '공급계약 체결 시 지급'), ('4', '청약/가계약금 납부 시 선지급')], default='1', max_length=2, verbose_name='지급 조건')),
                ('start_date', models.DateField(verbose_name='적용 시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='적용 종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('order_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.ordergroup', verbose_name='차수')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_policies', to='project.project', verbose_name='프로젝트')),
                ('unit_type', models.ForeignKey(blank=True, help_text='미지정 시 해당 차수/프로젝트 전체 공통 적용', null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.unittype', verbose_name='타입')),
            ],
            options={
                'verbose_name': '04. 수수료 정책',
                'verbose_name_plural': '04. 수수료 정책 목록',
                'ordering': ['project', '-start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PayoutContractDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('agent', '상담사 인센티브'), ('leader', '팀장 인센티브'), ('director', '본부장 인센티브'), ('mgm', 'MGM 수수료')], default='agent', max_length=10, verbose_name='지급 구분')),
                ('unit_fee', models.PositiveIntegerField(default=0, verbose_name='지급 수수료 (원)')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_payout_details', to='contract.contract', verbose_name='분양 계약')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_details', to='sales.commissionpayout', verbose_name='수수료 지급 명세')),
            ],
            options={
                'verbose_name': '08. 지급 대상 계약 상세',
                'verbose_name_plural': '08. 지급 대상 계약 상세 목록',
                'ordering': ['payout', 'contract'],
            },
        ),
        migrations.CreateModel(
            name='SalesAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='대행사명')),
                ('is_direct_managed', models.BooleanField(default=True, help_text='자체 직영 분양팀인 경우 체크', verbose_name='직영 여부')),
                ('business_number', models.CharField(blank=True, default='', max_length=20, verbose_name='사업자등록번호')),
                ('ceo_name', models.CharField(blank=True, default='', max_length=50, verbose_name='대표자명')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='대표 전화')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_agencies', to='project.project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '01. 분양 대행사',
                'verbose_name_plural': '01. 분양 대행사 목록',
                'ordering': ['project', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='성명')),
                ('duty', models.CharField(choices=[('1', '분양상담사'), ('2', '팀장'), ('3', '본부장'), ('4', '총괄본부장'), ('5', '지원/기타')], default='1', max_length=2, verbose_name='직책')),
                ('status', models.CharField(choices=[('1', '재직 (활동 중)'), ('2', '휴직'), ('3', '해촉 (퇴사)')], default='1', max_length=2, verbose_name='상태')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('id_number', models.CharField(blank=True, default='', help_text='원천세 신고용 (앞자리 또는 마스킹 식별번호)', max_length=20, verbose_name='주민등록번호')),
                ('tax_type', models.CharField(choices=[('1', '3.3% 사업소득 (프리랜서)'), ('2', '근로소득'), ('3', '사업자 (세금계산서)'), ('4', '기타')], default='1', max_length=2, verbose_name='소득 구분')),
                ('bank_name', models.CharField(blank=True, default='', max_length=30, verbose_name='정산 은행')),
                ('account_number', models.CharField(blank=True, default='', max_length=50, verbose_name='계좌번호')),
                ('account_holder', models.CharField(blank=True, default='', max_length=50, verbose_name='예금주')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='위촉/입사일')),
                ('quit_date', models.DateField(blank=True, null=True, verbose_name='해촉/퇴사일')),
                ('notes', models.TextField(blank=True, default='', verbose_name='비고/특이사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(blank=True, help_text='로그인 계정이 부여된 경우 연동', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_profiles', to=settings.AUTH_USER_MODEL, verbose_name='시스템 연동 계정')),
            ],
            options={
                'verbose_name': '03. 영업 인력',
                'verbose_name_plural': '03. 영업 인력 목록',
                'ordering': ['team', 'duty', 'name'],
            },
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='sales.salesperson', verbose_name='영업 인력'),
        ),
        migrations.CreateModel(
            name='CommissionClawback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='환수 금액 (원)')),
                ('reason', models.CharField(default='계약 해지에 따른 수수료 환수', max_length=200, verbose_name='환수 사유')),
                ('is_settled', models.BooleanField(default=False, verbose_name='차기 정산 상계 완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='환수 등록일시')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_clawbacks', to='contract.contract', verbose_name='해지 계약')),
                ('settled_payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_clawbacks', to='sales.commissionpayout', verbose_name='상계 처리된 정산 명세')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clawbacks', to='sales.salesperson', verbose_name='환수 대상자')),
            ],
            options={
                'verbose_name': '09. 수수료 환수 관리',
                'verbose_name_plural': '09. 수수료 환수 관리 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='조직/팀명')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='sales.salesagency', verbose_name='분양 대행사')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_teams', to='sales.salesteam', verbose_name='상위 조직 (본부)')),
            ],
            options={
                'verbose_name': '02. 영업 조직/팀',
                'verbose_name_plural': '02. 영업 조직/팀 목록',
                'ordering': ['agency', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='salesperson',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='sales.salesteam', verbose_name='소속 팀'),
        ),
        migrations.CreateModel(
            name='ContractSalesAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='영업 성과 인정일')),
                ('mgm_name', models.CharField(blank=True, default='', max_length=50, verbose_name='MGM/중개사 성명')),
                ('mgm_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='MGM 연락처')),
                ('mgm_fee', models.PositiveIntegerField(default=0, verbose_name='MGM 지급 수수료 (원)')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_agent_mapping', to='contract.contract', verbose_name='분양 계약')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_mappings', to='sales.commissionpolicy', verbose_name='적용 수수료 정책')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_mappings', to='sales.salesperson', verbose_name='담당 영업직원 (상담사)')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_mappings', to='sales.salesteam', verbose_name='소속 팀')),
            ],
            options={
                'verbose_name': '05. 계약 영업 매핑',
                'verbose_name_plural': '05. 계약 영업 매핑 목록',
                'ordering': ['-contract_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SettlementPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='예: 2026년 9월 1회차 수수료 정산', max_length=100, verbose_name='정산 회차명')),
                ('start_date', models.DateField(verbose_name='정산 대상 시작일')),
                ('end_date', models.DateField(verbose_name='정산 대상 종료일')),
                ('payout_date', models.DateField(blank=True, null=True, verbose_name='지급 예정일')),
                ('status', models.CharField(choices=[('1', '정산 작성 중'), ('2', '정산 확정 (승인 대기)'), ('3', '지급 완료')], default='1', max_length=2, verbose_name='정산 상태')),
                ('total_contracts', models.PositiveIntegerField(default=0, verbose_name='정산 계약 건수')),
                ('total_gross_amount', models.PositiveBigIntegerField(default=0, verbose_name='총 지급액 (세전)')),
                ('total_tax_amount', models.PositiveBigIntegerField(default=0, verbose_name='총 원천세 (3.3%)')),
                ('total_net_amount', models.PositiveBigIntegerField(default=0, verbose_name='총 실지급액 (세후)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_periods', to='project.project', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '06. 수수료 정산 회차',
                'verbose_name_plural': '06. 수수료 정산 회차 목록',
                'ordering': ['project', '-start_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='sales.settlementperiod', verbose_name='정산 회차'),
        ),
        migrations.AlterUniqueTogether(
            name='commissionpayout',
            unique_together={('period', 'sales_person')},
        ),
    ]
