# Generated by Django 6.1.1 on 2026-09-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salespersondocument',
            options={'ordering': ['sales_person', 'doc_type', '-created_at'], 'verbose_name': '12. 영업 인력 제출 서류', 'verbose_name_plural': '12. 영업 인력 제출 서류 목록'},
        ),
        migrations.AlterField(
            model_name='commissionpayout',
            name='pay_status',
            field=models.CharField(choices=[('1', '대기'), ('2', '승인'), ('3', '지급 완료'), ('4', '지급 보류')], db_index=True, default='1', max_length=2, verbose_name='지급 상태'),
        ),
        migrations.AlterField(
            model_name='commissionpolicy',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='적용 시작일'),
        ),
        migrations.AlterField(
            model_name='contractsalesagent',
            name='contract_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='영업 성과 인정일'),
        ),
        migrations.AlterField(
            model_name='contractsalesagent',
            name='is_settlement_approved',
            field=models.BooleanField(db_index=True, default=True, help_text='서류 완비 및 완납 확인 후 승인 시 정산 대상에 포함', verbose_name='수수료 정산 승인'),
        ),
    ]
