# Generated by Django 6.1 on 2026-09-06 11:37

import django.db.models.deletion
import sales.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('1', '주민등록등본/초본'), ('2', '통장 사본 (계좌 사본)'), ('3', '신분증 사본'), ('4', '영업 위촉계약서'), ('5', '각종 서약서/각서'), ('9', '기타 증빙서류')], default='1', max_length=2, verbose_name='서류 구분')),
                ('title', models.CharField(blank=True, default='', help_text='서류 세부 명칭 (예: 보안서약서, 청렴각서, 사업자등록증 등. 미입력 시 서류 구분이 기본 적용됩니다)', max_length=100, verbose_name='서류 세부 명칭')),
                ('file', models.FileField(upload_to=sales.models.get_sales_docs_upload_path, verbose_name='첨부 파일')),
                ('file_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='파일명')),
                ('file_type', models.CharField(blank=True, max_length=80, verbose_name='파일 타입')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='파일 크기')),
                ('is_verified', models.BooleanField(default=False, help_text='관리자가 서류 유효성을 확인한 경우 체크', verbose_name='서류 검증 여부')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='검증일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.salesperson', verbose_name='영업 인력')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sales_docs', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sales_docs', to=settings.AUTH_USER_MODEL, verbose_name='검증자')),
            ],
            options={
                'verbose_name': '10. 영업 인력 제출 서류',
                'verbose_name_plural': '10. 영업 인력 제출 서류 목록',
                'ordering': ['sales_person', 'doc_type', '-created_at'],
            },
        ),
    ]
