# Generated by Django 6.1 on 2026-09-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_initial'),
        ('sales', '0002_salespersondocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_count', models.PositiveIntegerField(default=0, verbose_name='계약 건수')),
                ('agency_fee_sum', models.PositiveBigIntegerField(default=0, help_text='CommissionPolicy.agency_fee × 계약 건수', verbose_name='대행사 수수료 합계 (VAT 제외)')),
                ('vat_amount', models.PositiveBigIntegerField(default=0, verbose_name='부가가치세 (10%)')),
                ('total_amount', models.PositiveBigIntegerField(default=0, help_text='agency_fee_sum + vat_amount', verbose_name='총 지급액 (VAT 포함)')),
                ('pay_status', models.CharField(choices=[('1', '대기'), ('2', '승인'), ('3', '지급 완료'), ('4', '지급 보류')], default='1', max_length=2, verbose_name='지급 상태')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='실제 지급일')),
                ('business_number', models.CharField(blank=True, default='', max_length=20, verbose_name='사업자등록번호')),
                ('bank_name', models.CharField(blank=True, default='', max_length=30, verbose_name='입금 은행')),
                ('account_number', models.CharField(blank=True, default='', max_length=50, verbose_name='입금 계좌')),
                ('account_holder', models.CharField(blank=True, default='', max_length=50, verbose_name='예금주')),
                ('note', models.TextField(blank=True, default='', verbose_name='비고/정산 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='sales.salesagency', verbose_name='분양 대행사')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_payouts', to='sales.settlementperiod', verbose_name='정산 회차')),
            ],
            options={
                'verbose_name': '10. 대행사 수수료 지급 명세',
                'verbose_name_plural': '10. 대행사 수수료 지급 명세 목록',
                'ordering': ['period', 'agency'],
                'unique_together': {('period', 'agency')},
            },
        ),
        migrations.CreateModel(
            name='AgencyPayoutContractDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_fee', models.PositiveIntegerField(default=0, verbose_name='대행사 건당 수수료 (원)')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agency_payout_details', to='contract.contract', verbose_name='분양 계약')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_details', to='sales.agencypayout', verbose_name='대행사 지급 명세')),
            ],
            options={
                'verbose_name': '11. 대행사 지급 대상 계약 상세',
                'verbose_name_plural': '11. 대행사 지급 대상 계약 상세 목록',
                'ordering': ['payout', 'contract'],
            },
        ),
    ]
