# Generated by Django 6.1 on 2026-09-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_agency_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementperiod',
            name='agency_fee_total',
            field=models.PositiveBigIntegerField(default=0, verbose_name='대행사 수수료(차지) 합계'),
        ),
        migrations.AddField(
            model_name='settlementperiod',
            name='billing_supply_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='시행사 청구 공급가액 (VAT 별도)'),
        ),
        migrations.AddField(
            model_name='settlementperiod',
            name='billing_total_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='시행사 총 청구금액 (VAT 포함)'),
        ),
        migrations.AddField(
            model_name='settlementperiod',
            name='billing_vat',
            field=models.PositiveBigIntegerField(default=0, verbose_name='시행사 청구 부가가치세 (10%)'),
        ),
    ]
