# Generated by Django 6.1 on 2026-09-07 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_settlement_period_billing_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsalesagent',
            name='approval_note',
            field=models.CharField(blank=True, default='', help_text='보류 사유 예: 계약금 2차 미납, 인감증명서 미징구 등', max_length=255, verbose_name='정산 승인/보류 사유'),
        ),
        migrations.AddField(
            model_name='contractsalesagent',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승인일시'),
        ),
        migrations.AddField(
            model_name='contractsalesagent',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='승인 관리자'),
        ),
        migrations.AddField(
            model_name='contractsalesagent',
            name='is_settlement_approved',
            field=models.BooleanField(default=True, help_text='서류 완비 및 완납 확인 후 승인 시 정산 대상에 포함', verbose_name='수수료 정산 승인'),
        ),
    ]
