# Generated by Django 6.1 on 2026-09-08 14:23

import django.db.models.deletion
from django.db import migrations, models


def populate_agency(apps, schema_editor):
    ContractSalesAgent = apps.get_model('sales', 'ContractSalesAgent')
    for m in ContractSalesAgent.objects.select_related('team__agency', 'sales_person__team__agency').all():
        agency = None
        if m.team and m.team.agency:
            agency = m.team.agency
        elif m.sales_person and m.sales_person.team and m.sales_person.team.agency:
            agency = m.sales_person.team.agency
        if agency:
            m.agency = agency
            m.save(update_fields=['agency'])


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_contract_agent_settlement_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsalesagent',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_mappings', to='sales.salesagency', verbose_name='분양 대행사'),
        ),
        migrations.AlterField(
            model_name='contractsalesagent',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_mappings', to='sales.salesperson', verbose_name='담당 영업직원 (상담사)'),
        ),
        migrations.AlterField(
            model_name='contractsalesagent',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract_mappings', to='sales.salesteam', verbose_name='소속 팀'),
        ),
        migrations.RunPython(populate_agency, reverse_code=migrations.RunPython.noop),
    ]

