# Generated by Django 6.1 on 2026-09-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_contractsalesagent_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypayout',
            name='unallocated_fee',
            field=models.PositiveBigIntegerField(default=0, help_text='직영 운영 시 팀장/본부장 부재로 인해 상위 조직에 귀속된 fee 합계. 실제 지급 금액이 아닌 시행사(또는 직영 대행사) 귀속 이익으로 표시.', verbose_name='귀속 이익 (미지급 fee 합계)'),
        ),
    ]
