{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-config
data:
  USER: "{{ .Release.Name }}"
  DATABASE: "{{ .Release.Name }}"
  TZ: "Asia/Seoul"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}-replica-cm
data:
  primary.cnf: |
    [mariadb]
    log-bin                     # enable binary logging
    log-basename=ibs           # used to be independent of hostname changes (otherwise is in data/mysql)
    binlog_expire_logs_seconds=432000  # 5일(5*24*60*60 초) 동안 보관 후 삭제

  replica.cnf: |
    [mariadb]
    log-basename=ibs           # used to be independent of hostname changes (otherwise is in data/mysql)

  primary.sql: |
    CREATE USER '{{ .Release.Name }}'@'%' IDENTIFIED BY '{{ .Values.global.dbPassword }}';
    GRANT REPLICATION REPLICA ON *.* TO '{{ .Release.Name }}'@'%';
    GRANT ALL PRIVILEGES ON *.* TO '{{ .Release.Name }}'@'%';
    CREATE DATABASE {{ .Release.Name }};

  secondary.sql: |
    # We have to know name of sts (`mariadb`) and service `mariadb-service` in advance as an FQDN.No need to use master_port
    CHANGE MASTER TO
    MASTER_HOST='{{ include "mariadb.fullname" . }}-0.{{ .Values.global.dbServiceName }}.{{ .Release.Namespace }}.svc.cluster.local', # mariadb-0.<headless service name>.<namespace name>.svc.cluster.local
    MASTER_USER='{{ .Release.Name }}',
    MASTER_PASSWORD='{{ .Values.global.dbPassword }}',
    MASTER_CONNECT_RETRY=10;
{{- end }}