apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ include "mariadb.fullname" . }}-{{ .Values.global.appMode }}-data-pvc
spec:
  storageClassName: mysql-data-{{ .Values.global.appMode }}
  accessModes:
  {{- range .Values.volumes.dataAccessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.dataPvcStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ include "mariadb.fullname" . }}-{{ .Values.global.appMode }}-sql-pvc
spec:
  storageClassName: init-sql-{{ .Values.global.appMode }}
  accessModes:
  {{- range .Values.volumes.sqlAccessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.sqlPvcStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ include "mariadb.fullname" . }}-{{ .Values.global.appMode }}-backup-pvc
spec:
  storageClassName: dump-backup-{{ .Values.global.appMode }}
  accessModes:
  {{- range .Values.volumes.backupAccessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.volumes.backupPvcStorage }}
