{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mariadb.serviceAccountName" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nfs-client-provisioner
{{- end }}
{{- end }}
