# Generated by Django 6.1 on 2026-08-23 17:04

import _utils.file_upload
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 500만원 이하 (팀장 전결), 5,000만원 초과 (대표이사 결재)', max_length=50, verbose_name='정책명')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=0, help_text='이상 (미입력 시 제한 없음)', max_digits=15, null=True, verbose_name='최소 금액')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=0, help_text='이하 (미입력 시 제한 없음)', max_digits=15, null=True, verbose_name='최대 금액')),
                ('final_dept_level', models.PositiveSmallIntegerField(blank=True, help_text='해당 금액 구간의 전결 부서 레벨 (예: 1=본부장 전결)', null=True, verbose_name='전결 부서 레벨')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='숫자가 작을수록 우선 평가', verbose_name='우선순위')),
            ],
            options={
                'verbose_name': '01-1. 조건부 전결 정책',
                'verbose_name_plural': '01-1. 조건부 전결 정책 목록',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField(verbose_name='결재 순서')),
                ('role_label', models.CharField(max_length=50, verbose_name='결재 단계명')),
                ('condition', models.CharField(choices=[('AND', '전원 승인 (AND)'), ('OR', '1인 승인 (OR)')], default='AND', max_length=3, verbose_name='결재 조건')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '반려'), ('skipped', '건너뜀')], default='pending', max_length=10, verbose_name='단계 상태')),
            ],
            options={
                'verbose_name': '04. 결재 단계',
                'verbose_name_plural': '04. 결재 단계 목록',
                'ordering': ['document', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='DocCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리명')),
                ('code', models.CharField(help_text='영문 대문자 (예: HR, FINANCE, CONTRACT, PROJECT, COMMON)', max_length=30, unique=True, verbose_name='코드')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='설명')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
            ],
            options={
                'verbose_name': '00. 결재 카테고리',
                'verbose_name_plural': '00. 결재 카테고리 목록',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='문서 유형명')),
                ('code', models.CharField(help_text='영문 대문자/언더스코어 (예: BIZ_APPROVAL)', max_length=30, unique=True, verbose_name='유형 코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('route_type', models.CharField(choices=[('organization', '조직도 기반 자동 결재선 (직속 부서장 → 상위 부서장 → 전결/대표이사)'), ('template', '수동 고정 템플릿 결재선')], default='organization', help_text='조직도 기반: 기안자의 부서 조직도를 탐색하여 자동 결재선 구성 / 템플릿: 지정된 결재선 템플릿 사용', max_length=15, verbose_name='결재선 생성 방식')),
                ('final_dept_level', models.PositiveSmallIntegerField(blank=True, help_text='예: 1로 설정 시 본부(1레벨) 부서장까지만 승인 후 완료 (대표이사 생략)', null=True, verbose_name='기본 전결 부서 레벨')),
                ('form_template_key', models.CharField(choices=[('GENERAL', '일반 업무 품의서 (GENERAL)'), ('OFFICIAL_LETTER', '공문 발신 / 대외 발송 (OFFICIAL_LETTER)'), ('LEAVE', '휴가 / 연차 신청서 (LEAVE)'), ('LEAVE_APPLICATION', '휴가 / 연차 신청서 (LEAVE_APPLICATION)'), ('BUSINESS_TRIP', '출장 신청서 (BUSINESS_TRIP)'), ('OVERTIME', '연장 / 휴일근무 신청서 (OVERTIME)'), ('HR_APPOINTMENT', '인사발령 품의서 (HR_APPOINTMENT)'), ('HR_REQUEST', '인사 제반 신청서 (HR_REQUEST)'), ('PURCHASE', '구매 / 자재 품의서 (PURCHASE)'), ('PURCHASE_ORDER', '구매 / 자재 품의서 (PURCHASE_ORDER)'), ('EXPENSE', '지출 결의서 (EXPENSE)'), ('EXPENSE_REPORT', '지출 결의서 (EXPENSE_REPORT)'), ('EXPENSE_SETTLEMENT', '경비 정산서 (EXPENSE_SETTLEMENT)'), ('ADVANCE', '선급금 / 가지급금 신청서 (ADVANCE)'), ('CONTRACT', '계약 체결 품의서 (CONTRACT)'), ('CONTRACT_CHANGE', '계약 변경 / 해지 품의서 (CONTRACT_CHANGE)'), ('LEGAL_REVIEW', '법무 검토서 (LEGAL_REVIEW)'), ('BUSINESS_REVIEW', '사업 검토서 (BUSINESS_REVIEW)'), ('BUSINESS_APPROVAL', '사업추진 승인서 (BUSINESS_APPROVAL)'), ('PROJECT_DECISION', '프로젝트 주요 의사결정서 (PROJECT_DECISION)')], default='GENERAL', help_text='매칭할 전자결재 양식 템플릿 (웹/모바일 공통 적용)', max_length=50, verbose_name='결재 양식 템플릿')),
                ('default_security_level', models.CharField(choices=[('1', '1등급 (비공개 / 결재선 및 참조자)'), ('2', '2등급 (부서공개 / 소속 부서)'), ('3', '3등급 (전사공개 / 회사 전체)')], default='2', help_text='1등급: 비공개(결재선/참조자만), 2등급: 부서공개, 3등급: 전사공개', max_length=1, verbose_name='기본 보안 등급')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '01. 결재 문서 유형',
                'verbose_name_plural': '01. 결재 문서 유형 목록',
                'ordering': ['category__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RouteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField(default=1, verbose_name='결재 순서')),
                ('role_label', models.CharField(help_text='예: 팀장 검토, 부서장 승인, 대표이사 최종', max_length=50, verbose_name='결재 단계명')),
                ('condition', models.CharField(choices=[('AND', '전원 승인 (AND)'), ('OR', '1인 승인 (OR)')], default='AND', help_text='AND: 전원 승인 필요 / OR: 1인 승인으로 진행', max_length=3, verbose_name='결재 조건')),
            ],
            options={
                'verbose_name': '02. 결재선 단계 템플릿',
                'verbose_name_plural': '02. 결재선 단계 템플릿 목록',
                'ordering': ['doc_type', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', '승인'), ('rejected', '반려'), ('commented', '의견')], max_length=15, verbose_name='결재 행동')),
                ('comment', models.TextField(blank=True, verbose_name='의견/반려 사유')),
                ('content_hash', models.CharField(blank=True, help_text='결재 시점의 문서 SHA-256 해시값 (위변조 검증용)', max_length=64, verbose_name='문서 해시')),
                ('is_delegated', models.BooleanField(default=False, verbose_name='대결 여부')),
                ('acted_at', models.DateTimeField(auto_now_add=True, verbose_name='결재일시')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='결재자')),
                ('delegated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_actions', to=settings.AUTH_USER_MODEL, verbose_name='원 결재권자 (위임자)')),
            ],
            options={
                'verbose_name': '05. 결재 행동 이력',
                'verbose_name_plural': '05. 결재 행동 이력 목록',
                'ordering': ['acted_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=_utils.file_upload.get_approval_file_path, verbose_name='첨부파일')),
                ('file_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='파일명')),
                ('file_type', models.CharField(blank=True, max_length=80, verbose_name='파일 타입')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='파일 크기')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '06. 결재 첨부파일',
                'verbose_name_plural': '06. 결재 첨부파일 목록',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='위임 시작일')),
                ('end_date', models.DateField(verbose_name='위임 종료일')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='위임 사유 (부재 사유)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('delegatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL, verbose_name='수임자 (대결자)')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL, verbose_name='위임자 (원 결재권자)')),
            ],
            options={
                'verbose_name': '07. 결재 권한 위임 (대결)',
                'verbose_name_plural': '07. 결재 권한 위임 (대결) 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, default=None, help_text='승인 후 자동 채번 (예: BIZ-2026-0001)', max_length=30, null=True, unique=True, verbose_name='문서 번호')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('content', models.JSONField(default=dict, help_text='문서 유형의 form_template_key에 따른 결재 양식 데이터', verbose_name='결재 내용')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=_utils.file_upload.get_approval_file_path, verbose_name='대표 첨부파일')),
                ('security_level', models.CharField(choices=[('1', '1등급 (비공개 / 결재선 및 참조자)'), ('2', '2등급 (부서공개 / 소속 부서)'), ('3', '3등급 (전사공개 / 회사 전체)')], db_index=True, default='2', help_text='1등급: 비공개(결재선/참조자만), 2등급: 부서공개, 3등급: 전사공개', max_length=1, verbose_name='보안 등급')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('pending', '결재 진행 중'), ('approved', '최종 승인'), ('rejected', '반려'), ('cancelled', '취소')], default='draft', max_length=15, verbose_name='결재 상태')),
                ('current_step', models.PositiveSmallIntegerField(default=0, verbose_name='현재 결재 단계')),
                ('content_hash', models.CharField(blank=True, help_text='상신 시 SHA-256으로 생성. 위변조 검증용.', max_length=64, verbose_name='문서 해시')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='approval/pdf/%Y/%m/', verbose_name='PDF 보관 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기안일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='상신일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('drafter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafted_documents', to=settings.AUTH_USER_MODEL, verbose_name='기안자')),
                ('drafter_assignment', models.ForeignKey(blank=True, help_text='기안 당시 선택한 소속 부서 및 직책', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_documents', to='company.staffassignment', verbose_name='기안 보직')),
                ('observers', models.ManyToManyField(blank=True, help_text='결재 진행 및 완료 시 열람 권한 및 알림을 수신하는 참조자', related_name='observed_approval_documents', to=settings.AUTH_USER_MODEL, verbose_name='참조자 목록')),
            ],
            options={
                'verbose_name': '03. 결재 문서',
                'verbose_name_plural': '03. 결재 문서 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
