# Generated by Django 6.1 on 2026-08-17 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0007_alter_projectbookmark_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='문서 유형명')),
                ('code', models.CharField(help_text='영문 대문자/언더스코어 (예: BIZ_APPROVAL)', max_length=30, unique=True, verbose_name='유형 코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('form_schema', models.JSONField(blank=True, default=list, help_text='동적 양식 필드 정의 (JSON Schema). 예: [{"key":"purpose","label":"목적","type":"text","required":true}]', verbose_name='양식 스키마')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '01. 결재 문서 유형',
                'verbose_name_plural': '01. 결재 문서 유형 목록',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_number', models.CharField(blank=True, help_text='승인 후 자동 채번 (예: BIZ-2026-0001)', max_length=30, unique=True, verbose_name='문서 번호')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('content', models.JSONField(default=dict, help_text='문서 유형의 form_schema에 따른 동적 양식 데이터', verbose_name='결재 내용')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='approval/attachments/%Y/%m/', verbose_name='첨부파일')),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('pending', '결재 진행 중'), ('approved', '최종 승인'), ('rejected', '반려'), ('cancelled', '취소')], default='draft', max_length=15, verbose_name='결재 상태')),
                ('current_step', models.PositiveSmallIntegerField(default=0, verbose_name='현재 결재 단계')),
                ('content_hash', models.CharField(blank=True, help_text='상신 시 SHA-256으로 생성. 위변조 검증용.', max_length=64, verbose_name='문서 해시')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='approval/pdf/%Y/%m/', verbose_name='PDF 보관 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기안일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='상신일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('drafter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafted_documents', to=settings.AUTH_USER_MODEL, verbose_name='기안자')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_documents', to='work.issueproject', verbose_name='워크스페이스')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='approval.documenttype', verbose_name='문서 유형')),
            ],
            options={
                'verbose_name': '03. 결재 문서',
                'verbose_name_plural': '03. 결재 문서 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField(verbose_name='결재 순서')),
                ('role_label', models.CharField(max_length=50, verbose_name='결재 단계명')),
                ('condition', models.CharField(choices=[('AND', '전원 승인 (AND)'), ('OR', '1인 승인 (OR)')], default='AND', max_length=3, verbose_name='결재 조건')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '반려'), ('skipped', '건너뜀')], default='pending', max_length=10, verbose_name='단계 상태')),
                ('approvers', models.ManyToManyField(related_name='approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='결재자 목록')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approval.approvaldocument', verbose_name='결재 문서')),
            ],
            options={
                'verbose_name': '04. 결재 단계',
                'verbose_name_plural': '04. 결재 단계 목록',
                'ordering': ['document', 'step_order'],
                'unique_together': {('document', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', '승인'), ('rejected', '반려'), ('commented', '의견')], max_length=15, verbose_name='결재 행동')),
                ('comment', models.TextField(blank=True, verbose_name='의견/반려 사유')),
                ('content_hash', models.CharField(blank=True, help_text='결재 시점의 문서 SHA-256 해시값 (위변조 검증용)', max_length=64, verbose_name='문서 해시')),
                ('acted_at', models.DateTimeField(auto_now_add=True, verbose_name='결재일시')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL, verbose_name='결재자')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approval.approvalstep', verbose_name='결재 단계')),
            ],
            options={
                'verbose_name': '05. 결재 행동 이력',
                'verbose_name_plural': '05. 결재 행동 이력 목록',
                'ordering': ['acted_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveSmallIntegerField(default=1, verbose_name='결재 순서')),
                ('role_label', models.CharField(help_text='예: 팀장 검토, 부서장 승인, 대표이사 최종', max_length=50, verbose_name='결재 단계명')),
                ('condition', models.CharField(choices=[('AND', '전원 승인 (AND)'), ('OR', '1인 승인 (OR)')], default='AND', help_text='AND: 전원 승인 필요 / OR: 1인 승인으로 진행', max_length=3, verbose_name='결재 조건')),
                ('approvers', models.ManyToManyField(help_text='병렬 결재(공동대표 등)의 경우 복수 지정 가능', related_name='approval_route_templates', to=settings.AUTH_USER_MODEL, verbose_name='결재자 목록')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_templates', to='approval.documenttype', verbose_name='문서 유형')),
            ],
            options={
                'verbose_name': '02. 결재선 단계 템플릿',
                'verbose_name_plural': '02. 결재선 단계 템플릿 목록',
                'ordering': ['doc_type', 'step_order'],
                'unique_together': {('doc_type', 'step_order')},
            },
        ),
    ]
