# Generated by Django 6.1 on 2026-08-23 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval', '0001_initial'),
        ('company', '0001_initial'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldocument',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_documents', to='work.issueproject', verbose_name='워크스페이스'),
        ),
        migrations.AddField(
            model_name='approvalattachment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='approval.approvaldocument', verbose_name='결재 문서'),
        ),
        migrations.AddField(
            model_name='approvalpolicyrule',
            name='final_approval_duty',
            field=models.ForeignKey(blank=True, help_text='해당 금액 구간의 전결 직책', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.dutytitle', verbose_name='전결 직책'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='approvers',
            field=models.ManyToManyField(related_name='approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='결재자 목록'),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approval.approvaldocument', verbose_name='결재 문서'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approval.approvalstep', verbose_name='결재 단계'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, help_text='지정된 부서 소속만 기안 가능 (비어있으면 전사 공통)', related_name='allowed_doc_types', to='company.department', verbose_name='기안 가능 부서'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='allowed_duties',
            field=models.ManyToManyField(blank=True, help_text='지정된 직책 보유자만 기안 가능 (비어있으면 전체 직책)', related_name='allowed_doc_types', to='company.dutytitle', verbose_name='기안 가능 직책'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='allowed_positions',
            field=models.ManyToManyField(blank=True, help_text='지정된 직위 보유자만 기안 가능 (비어있으면 전체 직위)', related_name='allowed_doc_types', to='company.position', verbose_name='기안 가능 직위'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types', to='approval.doccategory', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='final_approval_duty',
            field=models.ForeignKey(blank=True, help_text='기본 전결 직책 (예: 팀장 전결, 본부장 전결). 미지정 시 대표이사까지 상신.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.dutytitle', verbose_name='기본 전결 직책'),
        ),
        migrations.AddField(
            model_name='approvalpolicyrule',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_rules', to='approval.documenttype', verbose_name='문서 유형'),
        ),
        migrations.AddField(
            model_name='approvaldocument',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='approval.documenttype', verbose_name='문서 유형'),
        ),
        migrations.AddField(
            model_name='routetemplate',
            name='approvers',
            field=models.ManyToManyField(help_text='병렬 결재(공동대표 등)의 경우 복수 지정 가능', related_name='approval_route_templates', to=settings.AUTH_USER_MODEL, verbose_name='결재자 목록'),
        ),
        migrations.AddField(
            model_name='routetemplate',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_templates', to='approval.documenttype', verbose_name='문서 유형'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('document', 'step_order')},
        ),
        migrations.AlterUniqueTogether(
            name='routetemplate',
            unique_together={('doc_type', 'step_order')},
        ),
    ]
