# Generated by Django 6.1 on 2026-08-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldocument',
            name='doc_number',
            field=models.CharField(blank=True, default=None, help_text='승인 후 자동 채번 (예: BIZ-2026-0001)', max_length=30, null=True, unique=True, verbose_name='문서 번호'),
        ),
    ]
