# Generated by Django 6.1 on 2026-08-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_alter_approvaldocument_doc_number'),
        ('company', '0004_staffassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldocument',
            name='drafter_assignment',
            field=models.ForeignKey(blank=True, help_text='기안 당시 선택한 소속 부서 및 직책', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafted_documents', to='company.staffassignment', verbose_name='기안 보직'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='final_approval_duty',
            field=models.ForeignKey(blank=True, help_text='해당 직책자 승인 시 최종 완료 처리 (예: 팀장 전결, 본부장 전결). 미지정 시 대표이사까지 상신.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.dutytitle', verbose_name='전결 직책'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='final_dept_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='예: 1로 설정 시 본부(1레벨) 부서장까지만 승인 후 완료 (대표이사 생략)', null=True, verbose_name='전결 부서 레벨'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='route_type',
            field=models.CharField(choices=[('organization', '조직도 기반 자동 결재선 (직속 부서장 → 상위 부서장 → 전결/대표이사)'), ('template', '수동 고정 템플릿 결재선')], default='organization', help_text='조직도 기반: 기안자의 부서 조직도를 탐색하여 자동 결재선 구성 / 템플릿: 지정된 결재선 템플릿 사용', max_length=15, verbose_name='결재선 생성 방식'),
        ),
    ]
