# Generated by Django 6.1.1 on 2026-09-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_initial'),
        ('docs', '0005_officialletter_parent_inbound_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldocument',
            name='related_inbound_letter',
            field=models.ForeignKey(blank=True, help_text='수신공문 처리 보고 및 대응 품의인 경우 해당 수신공문 연결', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_documents', to='docs.inboundletter', verbose_name='연동 수신공문'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='target_doc_category',
            field=models.ForeignKey(blank=True, help_text='최종 승인 완료 시 결재 완료본 PDF가 일반 문서 자료실의 지정 카테고리로 자동 등재됩니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_archive_doc_types', to='docs.category', verbose_name='승인 후 자동 보관 카테고리'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='form_template_key',
            field=models.CharField(choices=[('GENERAL', '일반 업무 품의서 (GENERAL)'), ('OFFICIAL_LETTER', '공문 발신 / 대외 발송 (OFFICIAL_LETTER)'), ('LEAVE', '휴가 / 연차 신청서 (LEAVE)'), ('BUSINESS_TRIP', '출장 신청서 (BUSINESS_TRIP)'), ('OVERTIME', '연장 / 휴일근무 신청서 (OVERTIME)'), ('HR_APPOINTMENT', '인사발령 품의서 (HR_APPOINTMENT)'), ('HR_REQUEST', '인사 제반 신청서 (HR_REQUEST)'), ('PURCHASE', '구매 / 자재 품의서 (PURCHASE)'), ('EXPENSE', '지출 결의서 (EXPENSE)'), ('EXPENSE_SETTLEMENT', '경비 정산서 (EXPENSE_SETTLEMENT)'), ('ADVANCE', '선급금 / 가지급금 신청서 (ADVANCE)'), ('CONTRACT', '계약 체결 품의서 (CONTRACT)'), ('CONTRACT_CHANGE', '계약 변경 / 해지 품의서 (CONTRACT_CHANGE)'), ('LEGAL_REVIEW', '법무 검토서 (LEGAL_REVIEW)'), ('BUSINESS_REVIEW', '사업 검토서 (BUSINESS_REVIEW)'), ('BUSINESS_APPROVAL', '사업추진 승인서 (BUSINESS_APPROVAL)'), ('PROJECT_DECISION', '프로젝트 주요 의사결정서 (PROJECT_DECISION)'), ('INBOUND_REPORT', '수신 공문 처리 보고 / 품의 (INBOUND_REPORT)')], default='GENERAL', help_text='매칭할 전자결재 양식 템플릿 (웹/모바일 공통 적용)', max_length=50, verbose_name='결재 양식 템플릿'),
        ),
    ]
