# Generated by Django 6.1 on 2026-08-25 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_initial'),
        ('company', '0002_alter_promotioncandidate_options_and_more'),
        ('work', '0002_role_is_for_dev_project_tracker_is_for_dev_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='연도')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='마지막 채번')),
            ],
            options={
                'verbose_name': '08. 문서 채번 시퀀스',
                'verbose_name_plural': '08. 문서 채번 시퀀스 목록',
            },
        ),
        migrations.AlterField(
            model_name='approvaldocument',
            name='doc_number',
            field=models.CharField(blank=True, default=None, help_text='승인 후 자동 채번 (예: BIZ-2026-0001). DocNumberSequence를 통해 원자적으로 발급.', max_length=30, null=True, verbose_name='문서 번호'),
        ),
        migrations.AddConstraint(
            model_name='approvaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('doc_number__isnull', False)), fields=('doc_number',), name='unique_doc_number_when_not_null'),
        ),
        migrations.AddField(
            model_name='docnumbersequence',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_sequences', to='approval.documenttype', verbose_name='문서 유형'),
        ),
        migrations.AlterUniqueTogether(
            name='docnumbersequence',
            unique_together={('doc_type', 'year')},
        ),
    ]
