# Generated by Django 6.1 on 2026-08-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_add_doc_number_sequence_and_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='form_template_key',
            field=models.CharField(choices=[('GENERAL', '일반 업무 품의서 (GENERAL)'), ('OFFICIAL_LETTER', '공문 발신 / 대외 발송 (OFFICIAL_LETTER)'), ('LEAVE', '휴가 / 연차 신청서 (LEAVE)'), ('BUSINESS_TRIP', '출장 신청서 (BUSINESS_TRIP)'), ('OVERTIME', '연장 / 휴일근무 신청서 (OVERTIME)'), ('HR_APPOINTMENT', '인사발령 품의서 (HR_APPOINTMENT)'), ('HR_REQUEST', '인사 제반 신청서 (HR_REQUEST)'), ('PURCHASE', '구매 / 자재 품의서 (PURCHASE)'), ('EXPENSE', '지출 결의서 (EXPENSE)'), ('EXPENSE_SETTLEMENT', '경비 정산서 (EXPENSE_SETTLEMENT)'), ('ADVANCE', '선급금 / 가지급금 신청서 (ADVANCE)'), ('CONTRACT', '계약 체결 품의서 (CONTRACT)'), ('CONTRACT_CHANGE', '계약 변경 / 해지 품의서 (CONTRACT_CHANGE)'), ('LEGAL_REVIEW', '법무 검토서 (LEGAL_REVIEW)'), ('BUSINESS_REVIEW', '사업 검토서 (BUSINESS_REVIEW)'), ('BUSINESS_APPROVAL', '사업추진 승인서 (BUSINESS_APPROVAL)'), ('PROJECT_DECISION', '프로젝트 주요 의사결정서 (PROJECT_DECISION)')], default='GENERAL', help_text='매칭할 전자결재 양식 템플릿 (웹/모바일 공통 적용)', max_length=50, verbose_name='결재 양식 템플릿'),
        ),
    ]
