# Generated by Django 6.1 on 2026-08-19 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_approvaldocument_drafter_assignment_and_more'),
        ('company', '0004_staffassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리명')),
                ('code', models.CharField(help_text='영문 대문자 (예: HR, FINANCE, CONTRACT, PROJECT, COMMON)', max_length=30, unique=True, verbose_name='코드')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='설명')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
            ],
            options={
                'verbose_name': '00. 결재 카테고리',
                'verbose_name_plural': '00. 결재 카테고리 목록',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['category__order', 'id'], 'verbose_name': '01. 결재 문서 유형', 'verbose_name_plural': '01. 결재 문서 유형 목록'},
        ),
        migrations.AddField(
            model_name='documenttype',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, help_text='지정된 부서 소속만 기안 가능 (비어있으면 전사 공통)', related_name='allowed_doc_types', to='company.department', verbose_name='기안 가능 부서'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='allowed_duties',
            field=models.ManyToManyField(blank=True, help_text='지정된 직책 보유자만 기안 가능 (비어있으면 전체 직책)', related_name='allowed_doc_types', to='company.dutytitle', verbose_name='기안 가능 직책'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='allowed_positions',
            field=models.ManyToManyField(blank=True, help_text='지정된 직위 보유자만 기안 가능 (비어있으면 전체 직위)', related_name='allowed_doc_types', to='company.position', verbose_name='기안 가능 직위'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='final_approval_duty',
            field=models.ForeignKey(blank=True, help_text='기본 전결 직책 (예: 팀장 전결, 본부장 전결). 미지정 시 대표이사까지 상신.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.dutytitle', verbose_name='기본 전결 직책'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='final_dept_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='예: 1로 설정 시 본부(1레벨) 부서장까지만 승인 후 완료 (대표이사 생략)', null=True, verbose_name='기본 전결 부서 레벨'),
        ),
        migrations.CreateModel(
            name='ApprovalPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 500만원 이하 (팀장 전결), 5,000만원 초과 (대표이사 결재)', max_length=50, verbose_name='정책명')),
                ('min_amount', models.DecimalField(blank=True, decimal_places=0, help_text='이상 (미입력 시 제한 없음)', max_digits=15, null=True, verbose_name='최소 금액')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=0, help_text='이하 (미입력 시 제한 없음)', max_digits=15, null=True, verbose_name='최대 금액')),
                ('final_dept_level', models.PositiveSmallIntegerField(blank=True, help_text='해당 금액 구간의 전결 부서 레벨 (예: 1=본부장 전결)', null=True, verbose_name='전결 부서 레벨')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='숫자가 작을수록 우선 평가', verbose_name='우선순위')),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_rules', to='approval.documenttype', verbose_name='문서 유형')),
                ('final_approval_duty', models.ForeignKey(blank=True, help_text='해당 금액 구간의 전결 직책', null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.dutytitle', verbose_name='전결 직책')),
            ],
            options={
                'verbose_name': '01-1. 조건부 전결 정책',
                'verbose_name_plural': '01-1. 조건부 전결 정책 목록',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='documenttype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types', to='approval.doccategory', verbose_name='카테고리'),
        ),
    ]
