# Generated by Django 6.1 on 2026-08-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_doccategory_alter_documenttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='form_template_key',
            field=models.CharField(blank=True, help_text='STATIC 양식일 때 매칭할 Vue 컴포넌트 식별자 (예: LEAVE_APPLICATION, EXPENSE_REPORT, PURCHASE_ORDER 등)', max_length=50, verbose_name='전용 폼 컴포넌트 키'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='form_type',
            field=models.CharField(choices=[('DYNAMIC', '동적 양식 (JSON Schema)'), ('STATIC', '전용 정적 양식 (Vue 컴포넌트 매칭)')], default='DYNAMIC', help_text='DYNAMIC: 관리자 정의 JSON Schema 기반 / STATIC: 전용 Vue 폼 컴포넌트 매칭', max_length=10, verbose_name='양식 유형'),
        ),
    ]
