# Generated by Django 6.1 on 2026-08-19 18:02

import _utils.file_upload
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_documenttype_form_template_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldocument',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=_utils.file_upload.get_approval_file_path, verbose_name='대표 첨부파일'),
        ),
        migrations.CreateModel(
            name='ApprovalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=_utils.file_upload.get_approval_file_path, verbose_name='첨부파일')),
                ('file_name', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='파일명')),
                ('file_type', models.CharField(blank=True, max_length=80, verbose_name='파일 타입')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='파일 크기')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='approval.approvaldocument', verbose_name='결재 문서')),
            ],
            options={
                'verbose_name': '06. 결재 첨부파일',
                'verbose_name_plural': '06. 결재 첨부파일 목록',
                'ordering': ['id'],
            },
        ),
    ]
