# Generated by Django 6.1 on 2026-08-19 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0006_alter_approvaldocument_attachment_approvalattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldocument',
            name='observers',
            field=models.ManyToManyField(blank=True, help_text='결재 진행 및 완료 시 열람 권한 및 알림을 수신하는 참조자', related_name='observed_approval_documents', to=settings.AUTH_USER_MODEL, verbose_name='참조자 목록'),
        ),
    ]
