# Generated by Django 6.1 on 2026-08-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0007_approvaldocument_observers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='form_schema',
            field=models.JSONField(blank=True, default=list, help_text='동적 양식 필드 정의 (JSON Schema). 예: [{"key":"purpose","label":"목적","type":"text","required":true}]', verbose_name='양식 스키마 (동적 양식용)'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='form_template_key',
            field=models.CharField(blank=True, choices=[('LEAVE', '휴가 / 연차 신청서 (LEAVE)'), ('LEAVE_APPLICATION', '휴가 / 연차 신청서 (LEAVE_APPLICATION)'), ('EXPENSE', '지출 결의서 (EXPENSE)'), ('EXPENSE_REPORT', '지출 결의서 (EXPENSE_REPORT)'), ('PURCHASE', '구매 / 자재 품의서 (PURCHASE)'), ('PURCHASE_ORDER', '구매 / 자재 품의서 (PURCHASE_ORDER)'), ('OFFICIAL_LETTER', '공문 발신 / 대외 발송 (OFFICIAL_LETTER)'), ('GENERAL', '일반 업무 품의서 (GENERAL)'), ('BUSINESS_TRIP', '출장 신청서 (BUSINESS_TRIP)'), ('OVERTIME', '연장 / 휴일근무 신청서 (OVERTIME)'), ('HR_APPOINTMENT', '인사발령 품의서 (HR_APPOINTMENT)'), ('HR_REQUEST', '인사 제반 신청서 (HR_REQUEST)'), ('EXPENSE_SETTLEMENT', '경비 정산서 (EXPENSE_SETTLEMENT)'), ('ADVANCE', '선급금 / 가지급금 신청서 (ADVANCE)'), ('CONTRACT', '계약 체결 품의서 (CONTRACT)'), ('CONTRACT_CHANGE', '계약 변경 / 해지 품의서 (CONTRACT_CHANGE)'), ('LEGAL_REVIEW', '법무 검토서 (LEGAL_REVIEW)'), ('BUSINESS_REVIEW', '사업 검토서 (BUSINESS_REVIEW)'), ('BUSINESS_APPROVAL', '사업추진 승인서 (BUSINESS_APPROVAL)'), ('PROJECT_DECISION', '프로젝트 주요 의사결정서 (PROJECT_DECISION)')], help_text='STATIC 양식일 때 매칭할 폼 컴포넌트 식별자', max_length=50, verbose_name='전용 폼 컴포넌트 키'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='form_type',
            field=models.CharField(choices=[('STATIC', '전용 정적 양식 (Vue 컴포넌트 매칭)'), ('DYNAMIC', '동적 양식 (JSON Schema)')], default='STATIC', help_text='STATIC: 전용 Vue 폼 컴포넌트 매칭 (권장) / DYNAMIC: 관리자 정의 JSON Schema 기반', max_length=10, verbose_name='양식 유형'),
        ),
    ]
