# Generated by Django 6.1 on 2026-08-22 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0009_remove_documenttype_form_schema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaction',
            name='delegated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_actions', to=settings.AUTH_USER_MODEL, verbose_name='원 결재권자 (위임자)'),
        ),
        migrations.AddField(
            model_name='approvalaction',
            name='is_delegated',
            field=models.BooleanField(default=False, verbose_name='대결 여부'),
        ),
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='위임 시작일')),
                ('end_date', models.DateField(verbose_name='위임 종료일')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='위임 사유 (부재 사유)')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('delegatee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL, verbose_name='수임자 (대결자)')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL, verbose_name='위임자 (원 결재권자)')),
            ],
            options={
                'verbose_name': '07. 결재 권한 위임 (대결)',
                'verbose_name_plural': '07. 결재 권한 위임 (대결) 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
