# Generated by Django 6.1 on 2026-08-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0010_approvalaction_delegated_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvaldocument',
            name='security_level',
            field=models.CharField(choices=[('1', '1등급 (비공개 / 결재선 및 참조자)'), ('2', '2등급 (부서공개 / 소속 부서)'), ('3', '3등급 (전사공개 / 회사 전체)')], db_index=True, default='2', help_text='1등급: 비공개(결재선/참조자만), 2등급: 부서공개, 3등급: 전사공개', max_length=1, verbose_name='보안 등급'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='default_security_level',
            field=models.CharField(choices=[('1', '1등급 (비공개 / 결재선 및 참조자)'), ('2', '2등급 (부서공개 / 소속 부서)'), ('3', '3등급 (전사공개 / 회사 전체)')], default='2', help_text='1등급: 비공개(결재선/참조자만), 2등급: 부서공개, 3등급: 전사공개', max_length=1, verbose_name='기본 보안 등급'),
        ),
    ]
