{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}-db-auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  PASSWORD: {{ tpl .Values.global.dbPassword . | b64enc }}
  mariadb-root-password: {{ tpl .Values.global.dbPassword . | b64enc }}
{{- end }}
