{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: mariadb-port
      protocol: TCP
  clusterIP: None
  selector:
    {{- include "mariadb.selectorLabels" . | nindent 4 }}
{{- end }}
