# Generated by Django 6.0 on 2025-12-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('ibs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='순서')),
                ('alias_name', models.CharField(db_index=True, max_length=20, verbose_name='계좌별칭')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='계좌번호')),
                ('holder', models.CharField(blank=True, max_length=20, verbose_name='예금주')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='개설일자')),
                ('note', models.CharField(blank=True, max_length=50, verbose_name='비고')),
                ('is_hide', models.BooleanField(default=False, verbose_name='숨기기 여부')),
                ('inactive', models.BooleanField(default=False, verbose_name='비활성 여부')),
            ],
            options={
                'verbose_name': '01. 본사 관리계좌',
                'verbose_name_plural': '01. 본사 관리계좌',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCashBookCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated', models.DateField(blank=True, null=True, verbose_name='정산일')),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('import', '가져오기'), ('export', '내보내기')], max_length=10, verbose_name='작업 유형')),
                ('resource_type', models.CharField(choices=[('cashbook', 'CashBook'), ('project_cashbook', 'ProjectCashBook')], max_length=20, verbose_name='리소스 유형')),
                ('file', models.FileField(blank=True, null=True, upload_to='import_jobs/', verbose_name='파일')),
                ('task_id', models.CharField(blank=True, max_length=255, verbose_name='태스크 ID')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('progress', models.IntegerField(default=0, verbose_name='진행률')),
                ('total_records', models.IntegerField(default=0, verbose_name='전체 레코드')),
                ('processed_records', models.IntegerField(default=0, verbose_name='처리된 레코드')),
                ('success_count', models.IntegerField(default=0, verbose_name='성공 건수')),
                ('error_count', models.IntegerField(default=0, verbose_name='오류 건수')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='export_results/', verbose_name='결과 파일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
            ],
            options={
                'verbose_name': '가져오기/내보내기 작업',
                'verbose_name_plural': '가져오기/내보내기 작업',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='순서')),
                ('alias_name', models.CharField(db_index=True, max_length=20, verbose_name='계좌별칭')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='계좌번호')),
                ('holder', models.CharField(blank=True, max_length=20, verbose_name='예금주')),
                ('open_date', models.DateField(blank=True, null=True, verbose_name='개설일자')),
                ('note', models.CharField(blank=True, max_length=50, verbose_name='비고')),
                ('is_hide', models.BooleanField(default=False, verbose_name='숨기기 여부')),
                ('inactive', models.BooleanField(default=False, verbose_name='비활성 여부')),
                ('directpay', models.BooleanField(default=False, verbose_name='용역비 직불 여부')),
                ('is_imprest', models.BooleanField(default=False, verbose_name='운영비 계좌 여부')),
            ],
            options={
                'verbose_name': '03. 프로젝트 관리계좌',
                'verbose_name_plural': '03. 프로젝트 관리계좌',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_separate', models.BooleanField(default=False, help_text='각기 다른 계정 항목이 1회에 같이 출금된 경우 이 항목을 체크', verbose_name='상세 분리기록 등록')),
                ('is_imprest', models.BooleanField(default=False, help_text='전도금 대체 후 해당 전도금(운영비) 항목을 상세 기록하는 경우 이 항목', verbose_name='운영비 항목 여부')),
                ('content', models.CharField(blank=True, default='', max_length=50, verbose_name='적요')),
                ('trader', models.CharField(blank=True, default='', help_text='분양대금(분담금) 수납 건인 경우 반드시 해당 계좌에 기재된 입금자를 기재', max_length=25, verbose_name='거래처')),
                ('income', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='입금액')),
                ('outlay', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='출금액')),
                ('evidence', models.CharField(blank=True, choices=[('0', '증빙 없음'), ('1', '세금계산서'), ('2', '계산서(면세)'), ('3', '카드전표/현금영수증'), ('4', '간이영수증'), ('5', '거래명세서'), ('6', '입금표'), ('7', '지출결의서')], max_length=1, null=True, verbose_name='지출증빙')),
                ('note', models.TextField(blank=True, default='', verbose_name='비고')),
                ('deal_date', models.DateField(verbose_name='거래일자')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
            ],
            options={
                'verbose_name': '04. 프로젝트 입출금거래',
                'verbose_name_plural': '04. 프로젝트 입출금거래',
                'ordering': ['-deal_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCashBookCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated', models.DateField(blank=True, null=True, verbose_name='정산일')),
            ],
        ),
        migrations.CreateModel(
            name='CashBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_return', models.BooleanField(default=False, help_text='관계회사(프로젝트) 대여금 반환 정산 여부', verbose_name='반환 정산 여부')),
                ('is_separate', models.BooleanField(default=False, help_text='각기 다른 계정 항목이 1회에 같이 출금된 경우 이 항목을 체크', verbose_name='상세 분리기록 등록')),
                ('content', models.CharField(blank=True, default='', max_length=50, verbose_name='적요')),
                ('trader', models.CharField(blank=True, default='', max_length=25, verbose_name='거래처')),
                ('income', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='입금액')),
                ('outlay', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='출금액')),
                ('evidence', models.CharField(blank=True, choices=[('0', '증빙 없음'), ('1', '세금계산서'), ('2', '계산서(면세)'), ('3', '카드전표/현금영수증'), ('4', '간이영수증'), ('5', '거래명세서'), ('6', '입금표'), ('7', '지출결의서')], max_length=1, null=True, verbose_name='지출증빙')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='비고')),
                ('deal_date', models.DateField(verbose_name='거래일자')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
                ('account_d1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.accountsubd1', verbose_name='계정대분류')),
                ('account_d2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.accountsubd2', verbose_name='계정중분류')),
                ('account_d3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.accountsubd3', verbose_name='세부계정')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='회사정보')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '02. 본사 입출금거래',
                'verbose_name_plural': '02. 본사 입출금거래',
                'ordering': ['-deal_date', '-id'],
            },
        ),
    ]
