# Generated by Django 6.0 on 2025-12-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('company', '0001_initial'),
        ('contract', '0002_initial'),
        ('ibs', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project', verbose_name='투입 프로젝트'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='separated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepItems', to='cash.cashbook', verbose_name='분할 계정'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ibs.accountsort', verbose_name='구분'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cashbooks', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='bankcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash.bankcode', verbose_name='거래은행'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='회사정보'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.department', verbose_name='관리부서'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash.companybankaccount', verbose_name='거래계좌'),
        ),
        migrations.AddField(
            model_name='companycashbookcalculation',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='회사'),
        ),
        migrations.AddField(
            model_name='companycashbookcalculation',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AddField(
            model_name='projectbankaccount',
            name='bankcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash.bankcode', verbose_name='은행코드'),
        ),
        migrations.AddField(
            model_name='projectbankaccount',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cash.projectbankaccount', verbose_name='거래계좌'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contract.contract', verbose_name='계약일련번호'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
    ]
