# Generated by Django 6.0 on 2025-12-29 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0002_initial'),
        ('contract', '0002_initial'),
        ('ibs', '0001_initial'),
        ('payment', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcashbook',
            name='installment_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.installmentpaymentorder', verbose_name='납부회차'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='project_account_d2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ibs.projectaccountd2', verbose_name='프로젝트 계정'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='project_account_d3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ibs.projectaccountd3', verbose_name='프로젝트 세부계정'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='refund_contractor',
            field=models.ForeignKey(blank=True, help_text='이 건 거래가 환불금 출금인 경우 이 건을 납부한 계약자를 선택', null=True, on_delete=django.db.models.deletion.PROTECT, to='contract.contractor', verbose_name='환불 계약자'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='separated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sepItems', to='cash.projectcashbook', verbose_name='분할 계정'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ibs.accountsort', verbose_name='구분'),
        ),
        migrations.AddField(
            model_name='projectcashbook',
            name='updator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_cashbooks', to=settings.AUTH_USER_MODEL, verbose_name='편집자'),
        ),
        migrations.AddField(
            model_name='projectcashbookcalculation',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='projectcashbookcalculation',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='프로젝트'),
        ),
        migrations.AddIndex(
            model_name='cashbook',
            index=models.Index(fields=['separated'], name='idx_cb_separated'),
        ),
        migrations.AddIndex(
            model_name='cashbook',
            index=models.Index(fields=['is_separate', 'deal_date'], name='idx_cb_issep_date'),
        ),
        migrations.AddIndex(
            model_name='projectcashbook',
            index=models.Index(fields=['separated'], name='idx_pcb_separated'),
        ),
        migrations.AddIndex(
            model_name='projectcashbook',
            index=models.Index(fields=['is_separate', 'deal_date'], name='idx_pcb_issep_date'),
        ),
    ]
