# Generated by Django 6.0 on 2025-12-30 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_initial'),
        ('contract', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcashbook',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract', verbose_name='계약일련번호'),
        ),
    ]
