{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-db-auth
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ tpl .Values.global.dbPassword . | b64enc }}
{{- end }}
