# Generated by Django 6.1 on 2026-08-29 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0003_permission_is_confidential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('channel', '워크스페이스 공용 채널'), ('group', '비공개 그룹 채팅방'), ('direct', '1:1 다이렉트 메시지 (DM)')], default='channel', max_length=20, verbose_name='대화방 유형')),
                ('title', models.CharField(blank=True, default='', max_length=150, verbose_name='대화방 이름')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='대화방 설명/주제')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='개설일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='최근 활동일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='개설자')),
                ('project', models.ForeignKey(blank=True, help_text='공용 채널인 경우 소속 워크스페이스 지정', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='work.issueproject', verbose_name='소속 워크스페이스')),
            ],
            options={
                'verbose_name': '대화방',
                'verbose_name_plural': '01. 대화방 목록',
                'db_table': 'chat_room',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', '일반 텍스트'), ('image', '사진/이미지'), ('file', '문서/도면 파일'), ('issue', '업무(Issue) 공유 카드'), ('meeting', '회의록(Meeting) 공유 카드'), ('approval', '전자결재(Approval) 공유 카드'), ('system', '시스템 알림 메시지')], default='text', max_length=20, verbose_name='메시지 유형')),
                ('content', models.TextField(blank=True, default='', verbose_name='메시지 내용')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/', verbose_name='첨부파일')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='원본 파일명')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='파일 크기 (Byte)')),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='연계 데이터 PK (Issue/Meeting/Approval)')),
                ('ref_title', models.CharField(blank=True, default='', max_length=255, verbose_name='연계 데이터 요약/제목')),
                ('ref_sub', models.CharField(blank=True, default='', max_length=100, verbose_name='연계 데이터 상태/부가정보')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='전송일시')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chatmessage', verbose_name='답장 대상 메시지')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='발신자')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='대화방')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '03. 채팅 메시지 내역',
                'db_table': 'chat_message',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='방장/관리자')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('is_muted', models.BooleanField(default=False, verbose_name='알림 끄기')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='참여일시')),
                ('last_read_message_id', models.PositiveBigIntegerField(default=0, verbose_name='마지막 읽은 메시지 ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '대화방 멤버',
                'verbose_name_plural': '02. 대화방 멤버 관리',
                'db_table': 'chat_room_member',
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='chat_rooms', through='chat.ChatRoomMember', to=settings.AUTH_USER_MODEL, verbose_name='참여 멤버'),
        ),
    ]
