# Generated by Django 6.1.1 on 2026-09-19 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('channel', '워크스페이스 공용 채널'), ('group', '비공개 그룹 채팅방'), ('direct', '1:1 다이렉트 메시지 (DM)'), ('self', '나와의 채팅')], default='channel', max_length=20, verbose_name='대화방 유형'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('room_type', 'self')), fields=('created_by',), name='unique_user_self_chat'),
        ),
    ]
