# Generated by Django 6.1 on 2026-08-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommember',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='목록에서 숨김(나가기)'),
        ),
    ]
