# Generated by Django 6.1 on 2026-09-06 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroommember_is_hidden'),
        ('work', '0011_alter_permission_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False), ('room_type', 'channel')), fields=('project',), name='unique_project_channel'),
        ),
    ]
