# Generated by Django 6.0.7 on 2026-07-19 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=2)),
            ],
            options={
                'verbose_name': '01. (공통) - 입출금 구분',
                'verbose_name_plural': '01. (공통) - 입출금 구분',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WiseSaying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saying_ko', models.CharField(max_length=300)),
                ('saying_en', models.CharField(max_length=300)),
                ('spoked_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': '오늘의 한마디',
                'verbose_name_plural': '오늘의 한마디',
            },
        ),
        migrations.CreateModel(
            name='AccountSubD1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('sorts', models.ManyToManyField(to='ibs.accountsort')),
            ],
            options={
                'verbose_name': '02. (공통) - 회계계정 과목',
                'verbose_name_plural': '02. (공통) - 회계계정 과목',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AccountSubD2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('d1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_d2s', to='ibs.accountsubd1')),
            ],
            options={
                'verbose_name': '03. 본사 계정',
                'verbose_name_plural': '03. 본사 계정',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AccountSubD3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('is_hide', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=50)),
                ('d2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_d3s', to='ibs.accountsubd2')),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibs.accountsort')),
            ],
            options={
                'verbose_name': '04. 본사 세부계정',
                'verbose_name_plural': '04. 본사 세부계정',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CalendarSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='일정 제목')),
                ('all_day', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='시작 일자')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료 일자')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAccountD2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('d1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_d2s', to='ibs.accountsubd1')),
            ],
            options={
                'verbose_name': '05. 프로젝트 계정',
                'verbose_name_plural': '05. 프로젝트 계정',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectAccountD3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('is_payment', models.BooleanField(default=False)),
                ('is_related_contract', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('d2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_d3s', to='ibs.projectaccountd2')),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ibs.accountsort')),
            ],
            options={
                'verbose_name': '06. 프로젝트 세부계정',
                'verbose_name_plural': '06. 프로젝트 세부계정',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserWidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layouts', models.JSONField(default=dict, help_text='브레이크포인트별(lg, md, sm 등) 위젯 배치 및 크기 정보', verbose_name='레이아웃 설정')),
                ('visible_widgets', models.JSONField(default=list, help_text='현재 활성화되어 화면에 노출되는 위젯 ID 리스트', verbose_name='표시 위젯 목록')),
                ('version', models.PositiveIntegerField(default=1, help_text='포맷 변경 시 하위 호환성 관리를 위한 버전 번호', verbose_name='데이터 버전')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '07. 대시보드 위젯 설정',
                'verbose_name_plural': '07. 대시보드 위젯 설정',
            },
        ),
    ]
