# Generated by Django 6.0.6 on 2026-06-15 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layouts', models.JSONField(default=dict, help_text='브레이크포인트별(lg, md, sm 등) 위젯 배치 및 크기 정보', verbose_name='레이아웃 설정')),
                ('visible_widgets', models.JSONField(default=list, help_text='현재 활성화되어 화면에 노출되는 위젯 ID 리스트', verbose_name='표시 위젯 목록')),
                ('version', models.PositiveIntegerField(default=1, help_text='포맷 변경 시 하위 호환성 관리를 위한 버전 번호', verbose_name='데이터 버전')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='편집일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '07. 대시보드 위젯 설정',
                'verbose_name_plural': '07. 대시보드 위젯 설정',
            },
        ),
    ]
