# Generated by Django 6.1.1 on 2026-09-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarschedule',
            options={'ordering': ['-id'], 'verbose_name': '08. 캘린더 일정', 'verbose_name_plural': '08. 캘린더 일정'},
        ),
        migrations.AlterModelOptions(
            name='wisesaying',
            options={'ordering': ['id'], 'verbose_name': '오늘의 한마디', 'verbose_name_plural': '오늘의 한마디'},
        ),
    ]
