# Generated by Django 6.1.1 on 2026-09-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0002_alter_calendarschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwidgetconfig',
            options={'ordering': ['-id'], 'verbose_name': '07. 대시보드 위젯 설정', 'verbose_name_plural': '07. 대시보드 위젯 설정'},
        ),
    ]
