# Generated by Django 6.0.7 on 2026-08-09 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingcategory',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='work.meetingcategory', verbose_name='카테고리'),
            preserve_default=False,
        ),
    ]
