# Generated by Django 6.0.6 on 2026-06-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-meeting_date', '-created'), 'verbose_name': '08. 회의록', 'verbose_name_plural': '08. 회의록'},
        ),
        migrations.AlterModelOptions(
            name='meetingcategory',
            options={'ordering': ('order', 'id'), 'verbose_name': '07. 회의록 카테고리', 'verbose_name_plural': '07. 회의록 카테고리'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('project', 'id'), 'verbose_name': '06. 단계', 'verbose_name_plural': '06. 단계'},
        ),
    ]
