# Generated by Django 6.0.6 on 2026-06-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='확정 여부'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('1', '준비'), ('2', '종료'), ('3', '취소')], default='1', max_length=1, verbose_name='회의 상태'),
        ),
    ]
