# Generated by Django 6.0.7 on 2026-07-27 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issueproject',
            options={'ordering': ('status', 'order', 'id'), 'verbose_name': '01. 프로젝트(업무)', 'verbose_name_plural': '01. 프로젝트(업무)'},
        ),
    ]
