# Generated by Django 6.0.7 on 2026-07-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='calendar',
            field=models.BooleanField(default=True, verbose_name='캘린더'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('project', '프로젝트'), ('meeting', '회의'), ('issue', '업무'), ('news', '공지'), ('docs', '문서'), ('forum', '게시판'), ('calendar', '캘린더')], db_index=True, max_length=10, verbose_name='모듈'),
        ),
    ]
