# Generated by Django 6.0.2 on 2026-05-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='branch',
            name='work_branch_name_2386fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='work_commit_repo_id_28832f_idx',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='work_commit_repo_id_5fbe04_idx',
        ),
        migrations.RemoveIndex(
            model_name='commit',
            name='work_commit_repo_id_1926c5_idx',
        ),
        migrations.RemoveConstraint(
            model_name='commit',
            name='unique_repo_commit_hash',
        ),
        migrations.RemoveIndex(
            model_name='repository',
            name='work_reposi_project_f79a21_idx',
        ),
        migrations.RemoveIndex(
            model_name='repository',
            name='work_reposi_slug_f121df_idx',
        ),
        migrations.RemoveField(
            model_name='module',
            name='gantt',
        ),
        migrations.RemoveField(
            model_name='module',
            name='repository',
        ),
        migrations.AlterField(
            model_name='activitylogentry',
            name='sort',
            field=models.CharField(choices=[('1', '업무'), ('2', '댓글'), ('4', '공지'), ('5', '문서'), ('6', '파일'), ('7', '위키편집'), ('8', '글'), ('9', '작업시간')], default='1', max_length=1, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='sort',
            field=models.CharField(choices=[('project', '프로젝트'), ('issue', '업무관리'), ('time', '시간추적'), ('news', '공지'), ('docs', '문서'), ('file', '파일'), ('wiki', '위키'), ('forum', '게시판'), ('calendar', '달력')], db_index=True, max_length=10, verbose_name='모듈'),
        ),
        migrations.RemoveField(
            model_name='commit',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='repo',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='project',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Commit',
        ),
        migrations.DeleteModel(
            name='Repository',
        ),
    ]
