# Generated by Django 6.0.6 on 2026-06-15 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='work.meeting', verbose_name='관련 회의'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True, default='', help_text='회의에서 논의할 주요 의제 (사전 공유용)', verbose_name='회의 의제'),
        ),
    ]
