# Generated by Django 6.0.6 on 2026-06-25 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='sort',
            new_name='module',
        ),
    ]
