# Generated by Django on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='체크 시 슈퍼유저(최고관리자)에게만 노출/부여되며 일반 관리자에게는 역할 목록 및 권한 설정이 은닉됩니다.', verbose_name='보안 격리 역할'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('work_core', '업무 관리'), ('ibs_pm_manage', '프로젝트 관리'), ('ibs_hq_manage', '본사 관리'), ('shared', '공통 모듈')], default='work_core', max_length=20, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='role',
            name='category',
            field=models.CharField(choices=[('work_core', '업무 관리'), ('ibs_pm_manage', '프로젝트 관리'), ('ibs_hq_manage', '본사 관리')], default='work_core', max_length=20, verbose_name='구분'),
        ),
    ]
