# Generated by Django 6.1 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_for_dev_project',
            field=models.BooleanField(default=False, help_text='체크 시 신규 부동산 개발 프로젝트(type=2) 생성 시 allowed_roles에 기본 포함됩니다.', verbose_name='부동산개발 프로젝트 기본 적용'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='is_for_dev_project',
            field=models.BooleanField(default=False, help_text='체크 시 신규 부동산 개발 프로젝트(type=2) 생성 시 trackers에 기본 포함됩니다.', verbose_name='부동산개발 프로젝트 기본 적용'),
        ),
    ]
