# Generated by Django 6.0.6 on 2026-07-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='expected_duration',
            field=models.CharField(blank=True, choices=[('0', '당일처리'), ('1', '익일처리'), ('3', '3일 이내'), ('5', '5일 이내'), ('10', '10일 이내'), ('30', '30일 이내'), ('90', '3개월 이내'), ('180', '6개월 이내'), ('365', '1년 이내'), ('366', '1년 이상')], default='0', help_text='시작 일자 기준 예상 처리기간', max_length=3, null=True, verbose_name='예상 처리기간'),
        ),
    ]
