# Generated by Django on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='체크 시 슈퍼유저(최고관리자)에게만 노출/부여되며 일반 관리자에게는 역할 목록 및 권한 설정이 은닉됩니다.', verbose_name='보안 격리 역할'),
        ),
        migrations.AlterField(
            model_name='role',
            name='category',
            field=models.CharField(choices=[('work_space', '워크스페이스'), ('ibs_hq_manage', '본사 관리'), ('ibs_pr_manage', '프로젝트 관리')], default='work_space', max_length=20, verbose_name='구분'),
        ),
        migrations.RemoveField(
            model_name='permission',
            name='category',
        ),
        migrations.AddField(
            model_name='permission',
            name='is_for_workspace',
            field=models.BooleanField(default=True, verbose_name='워크스페이스 적용'),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_for_hq',
            field=models.BooleanField(default=False, verbose_name='본사 관리 적용'),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_for_project',
            field=models.BooleanField(default=False, verbose_name='프로젝트 관리 적용'),
        ),
    ]
