# Generated by Django 6.0.7 on 2026-07-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueproject',
            name='order',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='정렬순서'),
        ),
    ]
