# Generated by Django 6.0.6 on 2026-06-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('1', '준비'), ('2', '종료'), ('3', '확정'), ('4', '취소')], default='1', max_length=1, verbose_name='회의 상태'),
        ),
    ]
