# Generated by Django 6.0.5 on 2026-05-25 18:03

import django.db.models.deletion
import work.models.meeting
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('work', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='sort',
            field=models.CharField(choices=[('project', '프로젝트'), ('meeting', '회의록'), ('issue', '업무관리'), ('time', '시간추적'), ('news', '공지'), ('docs', '문서'), ('forum', '게시판'), ('calendar', '달력')], db_index=True, max_length=10, verbose_name='모듈'),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='회의 제목')),
                ('content', models.TextField(blank=True, default='', verbose_name='회의 내용')),
                ('meeting_date', models.DateTimeField(blank=True, null=True, verbose_name='회의 일시')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('attendees', models.ManyToManyField(blank=True, related_name='meetings_attended', to=settings.AUTH_USER_MODEL, verbose_name='참석자')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='company.company', verbose_name='회사')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='work.issueproject', verbose_name='프로젝트')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_meetings', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': '15. 회의록',
                'verbose_name_plural': '15. 회의록',
                'ordering': ('-meeting_date', '-created'),
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='work.meeting', verbose_name='회의록'),
        ),
        migrations.CreateModel(
            name='MeetingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='색상')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='정렬')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_categories', to='company.company', verbose_name='회사')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_categories', to='work.issueproject', verbose_name='프로젝트')),
            ],
            options={
                'verbose_name': '14. 회의록 카테고리',
                'verbose_name_plural': '14. 회의록 카테고리',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='work.meetingcategory', verbose_name='카테고리'),
        ),
        migrations.CreateModel(
            name='MeetingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=work.models.meeting.get_meeting_file_path, verbose_name='파일')),
                ('file_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='파일명')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='타입')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='사이즈')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='부가설명')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('meeting', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='work.meeting', verbose_name='회의록')),
            ],
        ),
    ]
