# Generated by Django 6.0.6 on 2026-06-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_meeting_options_alter_meetingcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingcategory',
            options={'ordering': ('order', 'id'), 'verbose_name': '07. 회의 카테고리', 'verbose_name_plural': '07. 회의 카테고리'},
        ),
    ]
