# Generated by Django 6.1 on 2026-08-10 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_meetingcategory_description_alter_meeting_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500, verbose_name='링크 URL')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='부가설명')),
                ('hit', models.PositiveIntegerField(default=0, verbose_name='클릭수')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('issue', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='work.issue', verbose_name='업무')),
            ],
        ),
    ]
