# Generated by Django 6.0.5 on 2026-05-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_permission_sort_meeting_issue_meeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='other_attendees',
            field=models.CharField(blank=True, default='', help_text='사용자(멤버)가 아닌 외부 참석자 명단', max_length=255, verbose_name='기타 참석자'),
        ),
    ]
