# Generated by Django 6.0.5 on 2026-05-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_branch_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='file',
        ),
        migrations.RemoveField(
            model_name='module',
            name='wiki',
        ),
        migrations.RemoveField(
            model_name='search',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='search',
            name='wiki',
        ),
        migrations.RemoveField(
            model_name='version',
            name='wiki_page_title',
        ),
        migrations.AlterField(
            model_name='activitylogentry',
            name='sort',
            field=models.CharField(choices=[('1', '업무'), ('2', '댓글'), ('4', '공지'), ('5', '문서'), ('8', '글'), ('9', '작업시간')], default='1', max_length=1, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='sort',
            field=models.CharField(choices=[('project', '프로젝트'), ('issue', '업무관리'), ('time', '시간추적'), ('news', '공지'), ('docs', '문서'), ('forum', '게시판'), ('calendar', '달력')], db_index=True, max_length=10, verbose_name='모듈'),
        ),
    ]
