# Generated by Django 6.0.7 on 2026-07-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_issueproject_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('project', '프로젝트'), ('meeting', '회의'), ('issue', '업무'), ('news', '공지'), ('docs', '문서'), ('forum', '게시판'), ('calendar', '캘린더'), ('contract', '계약 관리'), ('payment', '수납 관리'), ('notice', '고지 관리'), ('ledger', '자금/원장 관리'), ('site', '사업 부지 관리'), ('hr_work', '인사 관리')], db_index=True, max_length=10, verbose_name='모듈'),
        ),
    ]
