# Generated by Django 6.0.7 on 2026-07-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_issueproject_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('work_core', '업무관리 중심'), ('ibs_global', '비즈니스 데이터 지원'), ('shared', '공통 공유 모듈')], default='work_core', max_length=15, verbose_name='구분'),
        ),
    ]
