# Generated by Django 6.0.6 on 2026-07-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_issue_expected_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='expected_duration',
            field=models.CharField(blank=True, choices=[('1', '당일 처리'), ('2', '2일 이내'), ('3', '3일 이내'), ('5', '5일 이내'), ('10', '10일 이내'), ('30', '30일 이내'), ('90', '3개월 이내'), ('180', '6개월 이내'), ('365', '1년 이내'), ('366', '1년 이상')], default='1', help_text='시작 일자 기준 예상 처리기간', max_length=3, null=True, verbose_name='예상 처리기간'),
        ),
    ]
