# Generated by Django 6.1 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_role_is_confidential_alter_permission_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='category',
        ),
        migrations.AddField(
            model_name='permission',
            name='is_for_workspace',
            field=models.BooleanField(default=True, verbose_name='워크스페이스 적용'),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_for_hq',
            field=models.BooleanField(default=False, verbose_name='본사 관리 적용'),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_for_project',
            field=models.BooleanField(default=False, verbose_name='프로젝트 관리 적용'),
        ),
    ]
