# Generated by Django 6.0.6 on 2026-07-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_meeting_is_confirmed_alter_meeting_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('id',), 'verbose_name': '06. 단계', 'verbose_name_plural': '06. 단계'},
        ),
        migrations.AlterField(
            model_name='role',
            name='assignable',
            field=models.BooleanField(default=True, verbose_name='업무할당 가능 여부'),
        ),
    ]
