# Generated by Django 6.0.7 on 2026-07-14 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('work', '0002_alter_module_calendar_alter_permission_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuecomment',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='관리자 잠금'),
        ),
    ]
