# Generated by Django 6.0.7 on 2026-07-15 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_add_project_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='검색양식 이름')),
                ('target_type', models.CharField(choices=[('issue', '업무'), ('project', '프로젝트'), ('calendar', '캘린더'), ('meeting', '회의록')], db_index=True, max_length=20, verbose_name='대상 모듈')),
                ('is_public', models.BooleanField(default=False, help_text='체크 시 프로젝트 멤버 전원이 사용할 수 있습니다.', verbose_name='공용 여부')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='필터 정보 JSON (예: {"status": 1, "is_confirmed": true})', verbose_name='필터 조건')),
                ('column_names', models.JSONField(blank=True, default=list, help_text='테이블 그리드에 표시할 필드 목록 JSON (주로 issue, project, meeting)', verbose_name='표시할 열')),
                ('sort_criteria', models.JSONField(blank=True, default=list, help_text='정렬 옵션 JSON (예: [["priority", "desc"], ["created", "desc"]])', verbose_name='정렬 기준')),
                ('group_by', models.CharField(blank=True, default='', help_text='데이터 그룹핑 필드명', max_length=50, verbose_name='그룹화 기준')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_queries', to='work.issueproject', verbose_name='프로젝트 범위')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_queries', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '16. 검색 양식',
                'verbose_name_plural': '16. 검색 양식',
                'ordering': ('target_type', 'name', '-created'),
            },
        ),
    ]
