# Generated by Django 6.0.6 on 2026-06-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_alter_issue_meeting_alter_meeting_agenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-is_important', '-created'), 'verbose_name': '14. 공지', 'verbose_name_plural': '14. 공지'},
        ),
        migrations.AddField(
            model_name='news',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='중요 공지'),
        ),
    ]
