# Generated by Django 6.1 on 2026-08-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_role_is_for_dev_project_tracker_is_for_dev_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='체크 시 슈퍼유저(최고관리자)에게만 노출되며 일반 관리자에게는 권한 목록 및 권한 설정이 은닉됩니다.', verbose_name='보안 격리 권한'),
        ),
    ]
