# Generated by Django 6.0.6 on 2026-06-18 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_news_options_news_is_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='meetingcategory',
            name='company',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='work.issueproject', verbose_name='프로젝트'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetingcategory',
            name='project',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_categories', to='work.issueproject', verbose_name='프로젝트'),
            preserve_default=False,
        ),
    ]
