# Generated by Django 6.1 on 2026-08-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_role_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('work_core', '업무 관리'), ('ibs_hq_manage', '본사 관리'), ('ibs_pm_manage', '프로젝트 관리'), ('shared', '공통 모듈')], default='work_core', max_length=20, verbose_name='구분'),
        ),
    ]
