# Generated by Django 6.0.6 on 2026-06-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_activitylogentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeissuepriority',
            options={'ordering': ('order', 'id'), 'verbose_name': '12. 업무 우선 순위', 'verbose_name_plural': '12. 업무 우선 순위'},
        ),
        migrations.AlterModelOptions(
            name='issuecategory',
            options={'ordering': ('-project', 'id'), 'verbose_name': '14. 업무 범주', 'verbose_name_plural': '14. 업무 범주'},
        ),
    ]
