# Generated by Django 6.1 on 2026-08-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_permission_is_confidential'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueproject',
            name='chat_channel_enabled',
            field=models.BooleanField(default=True, help_text='체크 시 이 워크스페이스 소속 멤버들을 위한 실시간 메신저 공용 대화방(#채널)을 개설합니다.', verbose_name='메신저 공용 채널 개설'),
        ),
    ]
