# Generated by Django 6.0.7 on 2026-07-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_customquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquery',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='customquery',
            name='target_type',
            field=models.CharField(choices=[('project', '프로젝트'), ('meeting', '회의록'), ('issue', '업무'), ('calendar', '캘린더')], db_index=True, max_length=20, verbose_name='대상 모듈'),
        ),
    ]
