# Generated by Django 6.0.7 on 2026-07-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_permission_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('work_core', '업무 관리'), ('ibs_global', '개발 사업'), ('shared', '공통 모듈')], default='work_core', max_length=15, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='role',
            name='category',
            field=models.CharField(choices=[('work_core', '업무 관리'), ('ibs_global', '개발 사업')], default='work_core', max_length=15, verbose_name='구분'),
        ),
    ]
