# Generated by Django 6.0.7 on 2026-07-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_permission_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_work_role',
            field=models.BooleanField(default=True, help_text='업무관리(이슈/회의) 전용 역할인지 여부. 체크 해제 시 IBS 건설데이터(계약/수납/회계/부지/인사 등) 관리 역할로 구분됩니다.', verbose_name='업무 전용 역할'),
        ),
    ]
