# Generated by Django 6.1 on 2026-08-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_remove_permission_category_permission_is_for_hq_permission_is_for_project_permission_is_for_workspace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('order', 'id'), 'verbose_name': '03. 역할', 'verbose_name_plural': '03. 역할'},
        ),
    ]
