# Generated by Django 6.0.6 on 2026-06-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_meetingcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='is_in_roadmap',
            field=models.BooleanField(default=True, verbose_name='로드맵에 표시'),
        ),
    ]
