# Generated by Django 6.0.6 on 2026-07-07 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_issue_expected_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issueproject',
            old_name='sort',
            new_name='type',
        ),
    ]
