# Generated by Django 6.1 on 2026-08-30 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_issueproject_chat_channel_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='work.meetingcategory', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='meetingcategory',
            name='project',
            field=models.ForeignKey(blank=True, help_text='미지정 시 전체 워크스페이스 공용 카테고리로 사용', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_categories', to='work.issueproject', verbose_name='프로젝트'),
        ),
    ]
