# Generated by Django 6.0.5 on 2026-05-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_module_meeting_alter_permission_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='issue',
            field=models.BooleanField(default=True, verbose_name='업무'),
        ),
        migrations.AlterField(
            model_name='module',
            name='time',
            field=models.BooleanField(default=True, verbose_name='소요시간'),
        ),
    ]
