# Generated by Django 6.0.7 on 2026-07-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_permission_category_alter_role_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ('id',), 'verbose_name': '04. 권한', 'verbose_name_plural': '04. 권한'},
        ),
    ]
