# Generated by Django 6.1 on 2026-08-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_meetinglink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuelink',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meetinglink',
            name='description',
        ),
        migrations.AddField(
            model_name='issuelink',
            name='name',
            field=models.CharField(default='link name', max_length=255, verbose_name='링크 이름(파일명)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetinglink',
            name='name',
            field=models.CharField(default='link name', max_length=255, verbose_name='링크 이름(파일명)'),
            preserve_default=False,
        ),
    ]
