# Generated by Django 6.0.6 on 2026-06-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_remove_meeting_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerelation',
            name='relation_type',
            field=models.CharField(choices=[('precedes', '선행 업무')], default='precedes', max_length=20, verbose_name='관계 유형'),
        ),
    ]
