# Generated by Django 6.1 on 2026-08-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_permission_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('order', 'id'), 'verbose_name': '03. 역할', 'verbose_name_plural': '03. 역할'},
        ),
    ]
