# Generated by Django 6.0.7 on 2026-07-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_add_is_work_role_to_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('order', 'id'), 'verbose_name': '03. 역할', 'verbose_name_plural': '03. 역할'},
        ),
    ]
