# Generated by Django 6.0.7 on 2026-07-16 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_customquery_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylogentry',
            options={'ordering': ('-id',), 'verbose_name': '15. 실행 기록', 'verbose_name_plural': '15. 실행 기록'},
        ),
        migrations.AlterModelOptions(
            name='customquery',
            options={'ordering': ('target_type', 'name', '-created'), 'verbose_name': '18. 검색 양식', 'verbose_name_plural': '18. 검색 양식'},
        ),
        migrations.AlterModelOptions(
            name='issuecategory',
            options={'ordering': ('-project', 'id'), 'verbose_name': '13. 업무 범주', 'verbose_name_plural': '13. 업무 범주'},
        ),
        migrations.AlterModelOptions(
            name='issuelogentry',
            options={'verbose_name': '16. 업무 로그', 'verbose_name_plural': '16. 업무 로그'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-is_important', '-created'), 'verbose_name': '17. 공지', 'verbose_name_plural': '17. 공지'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'verbose_name': '14. 업무 흐름', 'verbose_name_plural': '14. 업무 흐름'},
        ),
    ]
