# Generated by Django 6.0.7 on 2026-07-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_alter_role_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('work_core', '업무관리 중심'), ('ibs_global', '비즈니스 데이터 지원')], default='work_core', max_length=15, verbose_name='구분'),
        ),
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.CharField(choices=[('work_core', '업무관리 중심'), ('ibs_global', '비즈니스 데이터 지원')], default='work_core', max_length=15, verbose_name='구분'),
        ),
    ]
