# Generated by Django 6.0.7 on 2026-07-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_permission_category_role_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ('-category', 'module', 'id'), 'verbose_name': '04. 권한', 'verbose_name_plural': '04. 권한'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('-category', 'order', 'id'), 'verbose_name': '03. 역할', 'verbose_name_plural': '03. 역할'},
        ),
    ]
