# Generated by Django 6.1 on 2026-08-30 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_meeting_category_alter_meetingcategory_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='work.issueproject', verbose_name='워크스페이스'),
        ),
        migrations.AlterField(
            model_name='meetingcategory',
            name='project',
            field=models.ForeignKey(blank=True, help_text='미지정 시 전체 워크스페이스 공용 카테고리로 사용', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_categories', to='work.issueproject', verbose_name='워크스페이스'),
        ),
    ]
