# Generated by Django 6.1 on 2026-08-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_remove_issuelink_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issueproject',
            options={'ordering': ('status', 'order', 'id'), 'verbose_name': '01. 워크스페이스', 'verbose_name_plural': '01. 워크스페이스'},
        ),
    ]
