# Generated by Django 6.0.6 on 2026-06-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_issuerelation_relation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerelation',
            name='delay',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='대기일수'),
        ),
    ]
