# Generated by Django 6.0.7 on 2026-07-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_activitylogentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('order', '-id'), 'verbose_name': '03. 역할', 'verbose_name_plural': '03. 역할'},
        ),
    ]
