# Generated by Django 6.0.5 on 2026-05-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_alter_module_issue_alter_module_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='sort',
            field=models.CharField(choices=[('project', '프로젝트'), ('meeting', '회의'), ('issue', '업무'), ('time', '소요시간'), ('news', '공지'), ('docs', '문서'), ('forum', '게시판'), ('calendar', '달력')], db_index=True, max_length=10, verbose_name='모듈'),
        ),
    ]
