# Generated by Django 6.0.7 on 2026-07-11 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_projectsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerelation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='work.issue', verbose_name='선행 업무(이 업무를 우선 진행)'),
        ),
        migrations.AlterField(
            model_name='issuerelation',
            name='target',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relation', to='work.issue', verbose_name='후속 업무(이 업무를 다음에 진행)'),
        ),
    ]
