# Generated by Django 6.0.5 on 2026-05-29 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_permission_sort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('project', 'id'), 'verbose_name': '05. 단계', 'verbose_name_plural': '05. 단계'},
        ),
        migrations.AlterField(
            model_name='issueproject',
            name='default_version',
            field=models.ForeignKey(blank=True, help_text='기존 공유 단계에서만 작동합니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.version', verbose_name='기본 단계'),
        ),
        migrations.AlterField(
            model_name='version',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='단계 완료 기한'),
        ),
    ]
