# Generated by Django 6.0.7 on 2026-07-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-updated', '-created'), 'verbose_name': '09. 업무(작업)', 'verbose_name_plural': '09. 업무(작업)'},
        ),
    ]
