# Generated by Django 6.0.6 on 2026-06-20 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_issuerelation_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuerelation',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issuerelation',
            name='issue_to',
        ),
        migrations.RemoveField(
            model_name='issuerelation',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='issuerelation',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='work.issue', verbose_name='선행 업무'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuerelation',
            name='target',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relation', to='work.issue', verbose_name='후속 업무'),
            preserve_default=False,
        ),
    ]
