# Generated by Django 6.1 on 2026-08-14 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_issueproject_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectbookmark',
            options={'ordering': ('order', 'created'), 'verbose_name': '워크스페이스 북마크', 'verbose_name_plural': '워크스페이스 북마크'},
        ),
        migrations.AlterModelOptions(
            name='projectsubscription',
            options={'verbose_name': '워크스페이스 알림 구독', 'verbose_name_plural': '워크스페이스 알림 구독'},
        ),
        migrations.AlterField(
            model_name='customquery',
            name='is_public',
            field=models.BooleanField(default=False, help_text='체크 시 워크스페이스 멤버 전원이 사용할 수 있습니다.', verbose_name='공용 여부'),
        ),
        migrations.AlterField(
            model_name='customquery',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_queries', to='work.issueproject', verbose_name='워크스페이스 범위'),
        ),
        migrations.AlterField(
            model_name='customquery',
            name='target_type',
            field=models.CharField(choices=[('project', '워크스페이스'), ('meeting', '회의록'), ('issue', '업무'), ('calendar', '캘린더')], db_index=True, max_length=20, verbose_name='대상 모듈'),
        ),
        migrations.AlterField(
            model_name='issueproject',
            name='is_inherit_members',
            field=models.BooleanField(default=False, verbose_name='상위 워크스페이스 멤버 상속'),
        ),
        migrations.AlterField(
            model_name='issueproject',
            name='is_public',
            field=models.BooleanField(default=True, help_text='공개 워크스페이스는 모든 로그인한 사용자가 접속할 수 있습니다.', verbose_name='공개'),
        ),
        migrations.AlterField(
            model_name='issueproject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.issueproject', verbose_name='상위 워크스페이스'),
        ),
        migrations.AlterField(
            model_name='issueproject',
            name='slack_notifications_enabled',
            field=models.BooleanField(default=False, help_text='이 워크스페이스의 데이터 변동을 Slack으로 실시간 알림받습니다.', verbose_name='Slack 알림 활성화'),
        ),
        migrations.AlterField(
            model_name='member',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='work.issueproject', verbose_name='워크스페이스'),
        ),
        migrations.AlterField(
            model_name='module',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.issueproject', verbose_name='워크스페이스'),
        ),
        migrations.AlterField(
            model_name='news',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.issueproject', verbose_name='워크스페이스'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('project', '워크스페이스'), ('meeting', '회의'), ('issue', '업무'), ('news', '공지'), ('docs', '문서'), ('forum', '게시판'), ('calendar', '캘린더'), ('contract', '계약 관리'), ('payment', '수납 관리'), ('notice', '고지 관리'), ('ledger', '자금/원장 관리'), ('site', '사업 부지 관리'), ('hr_work', '인사 관리')], db_index=True, max_length=10, verbose_name='모듈'),
        ),
        migrations.AlterField(
            model_name='projectbookmark',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='work.issueproject', verbose_name='워크스페이스'),
        ),
        migrations.AlterField(
            model_name='projectsubscription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.issueproject', verbose_name='업무 워크스페이스'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_visible',
            field=models.CharField(choices=[('ALL', '모든 활성 사용자'), ('PRJ', '보이는 워크스페이스 사용자'), ('NOP', '없음')], default='ALL', max_length=3, verbose_name='사용자 보기 권한'),
        ),
        migrations.AlterField(
            model_name='search',
            name='project',
            field=models.BooleanField(default=False, verbose_name='워크스페이스 포함 여부'),
        ),
        migrations.AlterField(
            model_name='search',
            name='scope',
            field=models.CharField(choices=[('0', '모두'), ('1', '워크스페이스 내'), ('2', '하위 워크스페이스 포함')], max_length=1, verbose_name='검색 범위 조건'),
        ),
        migrations.AlterField(
            model_name='version',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='work.issueproject', verbose_name='워크스페이스'),
        ),
        migrations.AlterField(
            model_name='version',
            name='sharing',
            field=models.CharField(choices=[('0', '공유 없음'), ('1', '하위 워크스페이스'), ('2', '상위 및 하위 워크스페이스'), ('3', '최상위 및 모든 하위 워크스페이스'), ('4', '모든 워크스페이스')], default='1', max_length=1, verbose_name='공유'),
        ),
    ]
