# Generated by Django 6.1 on 2026-08-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_meeting_project_alter_meetingcategory_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='location',
            field=models.CharField(blank=True, default='', help_text='회의가 진행된 장소 (예: 본사 대회의실, 구청 미팅룸, Zoom 링크 등)', max_length=255, verbose_name='회의 장소'),
        ),
    ]
