# Generated by Django 6.0.7 on 2026-07-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_permission_options_alter_role_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ('-category', 'id'), 'verbose_name': '04. 권한', 'verbose_name_plural': '04. 권한'},
        ),
    ]
