# Generated by Django 6.0.5 on 2026-05-29 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_version_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='fixed_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='work.version', verbose_name='목표 단계'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='is_in_roadmap',
            field=models.BooleanField(default=True, verbose_name='추진현황에 표시'),
        ),
    ]
