# Generated by Django 6.0.7 on 2026-07-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_issue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueproject',
            name='status',
            field=models.CharField(choices=[('1', '사용'), ('2', '닫힘'), ('9', '잠금보관(모든 접근이 차단됨)')], default='1', max_length=1, verbose_name='사용여부'),
        ),
    ]
