# Generated by Django 6.1 on 2026-09-03 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_document_security_level'),
        ('forum', '0002_initial'),
        ('work', '0007_meeting_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogentry',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='내용/의제 요약 스냅샷'),
        ),
        migrations.AddField(
            model_name='activitylogentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='제목 스냅샷'),
        ),
        migrations.AlterField(
            model_name='activitylogentry',
            name='comment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.issuecomment', verbose_name='댓글'),
        ),
        migrations.AlterField(
            model_name='activitylogentry',
            name='document',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.document', verbose_name='문서'),
        ),
        migrations.AlterField(
            model_name='activitylogentry',
            name='issue',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.issue', verbose_name='업무'),
        ),
        migrations.AlterField(
            model_name='activitylogentry',
            name='meeting',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.meeting', verbose_name='회의'),
        ),
        migrations.AlterField(
            model_name='activitylogentry',
            name='news',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.news', verbose_name='공지'),
        ),
        migrations.AlterField(
            model_name='activitylogentry',
            name='post',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum.post', verbose_name='게시글'),
        ),
    ]
