# Generated by Django 6.0.5 on 2026-05-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_alter_issue_fixed_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='estimated_hours',
        ),
        migrations.AddField(
            model_name='issue',
            name='expected_duration',
            field=models.CharField(blank=True, choices=[('0', '당일처리'), ('1', '1일 이내'), ('3', '3일 이내'), ('5', '5일 이내'), ('10', '10일 이내'), ('30', '30일 이내'), ('90', '3개월 이내'), ('180', '6개월 이내'), ('365', '1년 이내'), ('366', '1년 이상')], default='0', max_length=3, null=True, verbose_name='예상 처리기간'),
        ),
    ]
