# Generated by Django 6.1 on 2026-09-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_activitylogentry_summary_activitylogentry_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogentry',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='activitylogentry',
            name='document',
        ),
        migrations.RemoveField(
            model_name='activitylogentry',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='activitylogentry',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='activitylogentry',
            name='news',
        ),
        migrations.RemoveField(
            model_name='activitylogentry',
            name='post',
        ),
        migrations.AddField(
            model_name='activitylogentry',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='상위 객체 PK(업무/포럼 등)'),
        ),
        migrations.AddField(
            model_name='activitylogentry',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='대상 객체 PK'),
        ),
    ]
