# Generated by Django 6.0.5 on 2026-05-29 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_remove_issue_estimated_hours_issue_expected_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='work.meeting', verbose_name='회의'),
        ),
    ]
