# Generated by Django 6.0.7 on 2026-07-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_alter_issueproject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueproject',
            name='status',
            field=models.CharField(choices=[('1', '사용중'), ('2', '닫힘'), ('9', '잠금보관(모든 접근이 차단됨)')], default='1', help_text='사용중: 활성화 상태, 닫힘: 읽기 전용 상태, 잠금보관: 관리자외 접근 제한', max_length=1, verbose_name='사용여부'),
        ),
    ]
