# Generated by Django 6.1 on 2026-09-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_backfill_activity_log_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('project', '워크스페이스'), ('meeting', '회의'), ('issue', '업무'), ('news', '공지'), ('docs', '문서'), ('forum', '게시판'), ('calendar', '캘린더'), ('contract', '계약 관리'), ('sales', '분양 관리'), ('payment', '수납 관리'), ('notice', '고지 관리'), ('ledger', '회계 관리'), ('site', '부지 관리'), ('hr_work', '인사 관리')], db_index=True, max_length=10, verbose_name='모듈'),
        ),
    ]
