# Generated by Django 6.0.5 on 2026-05-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_alter_issue_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='default_time_activity',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='issueproject',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='project',
        ),
        migrations.RemoveField(
            model_name='activitylogentry',
            name='spent_time',
        ),
        migrations.RemoveField(
            model_name='module',
            name='time',
        ),
        migrations.RemoveField(
            model_name='role',
            name='time_entry_visible',
        ),
        migrations.AlterField(
            model_name='activitylogentry',
            name='sort',
            field=models.CharField(choices=[('1', '업무'), ('2', '댓글'), ('4', '공지'), ('5', '문서'), ('8', '글')], default='1', max_length=1, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='sort',
            field=models.CharField(choices=[('project', '프로젝트'), ('meeting', '회의'), ('issue', '업무'), ('news', '공지'), ('docs', '문서'), ('forum', '게시판'), ('calendar', '달력')], db_index=True, max_length=10, verbose_name='모듈'),
        ),
        migrations.DeleteModel(
            name='CodeActivity',
        ),
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
