# Generated by Django 6.0.5 on 2026-05-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_remove_role_default_time_activity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylogentry',
            options={'ordering': ('-id',), 'verbose_name': '14. 작업 내역', 'verbose_name_plural': '14. 작업 내역'},
        ),
        migrations.AlterModelOptions(
            name='codedocscategory',
            options={'ordering': ('order', 'id'), 'verbose_name': '12. 문서 범주', 'verbose_name_plural': '12. 문서 범주'},
        ),
        migrations.AlterModelOptions(
            name='codeissuepriority',
            options={'ordering': ('order', 'id'), 'verbose_name': '11. 업무 우선 순위', 'verbose_name_plural': '11. 업무 우선 순위'},
        ),
        migrations.AlterModelOptions(
            name='issuecategory',
            options={'ordering': ('-project', 'id'), 'verbose_name': '08. 업무 범주', 'verbose_name_plural': '08. 업무 범주'},
        ),
        migrations.AlterModelOptions(
            name='issuelogentry',
            options={'verbose_name': '15. 업무 로그', 'verbose_name_plural': '15. 업무 로그'},
        ),
        migrations.AlterModelOptions(
            name='issuestatus',
            options={'ordering': ('order', 'id'), 'verbose_name': '09. 업무 상태', 'verbose_name_plural': '09. 업무 상태'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': '13. 공지', 'verbose_name_plural': '13. 공지'},
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ('order', 'id'), 'verbose_name': '07. 업무 유형', 'verbose_name_plural': '07. 업무 유형'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'verbose_name': '10. 업무 흐름', 'verbose_name_plural': '10. 업무 흐름'},
        ),
    ]
