# Generated by Django 6.0.5 on 2026-06-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_alter_activitylogentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylogentry',
            options={'ordering': ('-id',), 'verbose_name': '14. 실행 기록', 'verbose_name_plural': '14. 실행 기록'},
        ),
    ]
