# Generated by Django 6.0.5 on 2026-06-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_alter_activitylogentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='action_items',
            field=models.TextField(blank=True, default='', help_text='누가, 언제까지, 무엇을 할 것인가?', verbose_name='후속 조치 사항'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(blank=True, default='', help_text='회의에서 논의할 주요 의제 (사전 공유용)', verbose_name='회의 아젠다'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='decisions',
            field=models.TextField(blank=True, default='', help_text='회의를 통해 확정된 합의 내용', verbose_name='주요 결정 사항'),
        ),
    ]
