# Generated by Django 6.0.5 on 2026-06-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_meeting_action_items_meeting_agenda_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylogentry',
            options={'ordering': ('-id',), 'verbose_name': '15. 실행 기록', 'verbose_name_plural': '15. 실행 기록'},
        ),
        migrations.AlterModelOptions(
            name='codeissuepriority',
            options={'ordering': ('order', 'id'), 'verbose_name': '13. 업무 우선 순위', 'verbose_name_plural': '13. 업무 우선 순위'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('-id',), 'verbose_name': '08. 업무(작업)', 'verbose_name_plural': '08. 업무(작업)'},
        ),
        migrations.AlterModelOptions(
            name='issuecategory',
            options={'ordering': ('-project', 'id'), 'verbose_name': '10. 업무 범주', 'verbose_name_plural': '10. 업무 범주'},
        ),
        migrations.AlterModelOptions(
            name='issuelogentry',
            options={'verbose_name': '16. 업무 로그', 'verbose_name_plural': '16. 업무 로그'},
        ),
        migrations.AlterModelOptions(
            name='issuestatus',
            options={'ordering': ('order', 'id'), 'verbose_name': '11. 업무 상태', 'verbose_name_plural': '11. 업무 상태'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-meeting_date', '-created'), 'verbose_name': '06. 회의록', 'verbose_name_plural': '06. 회의록'},
        ),
        migrations.AlterModelOptions(
            name='meetingcategory',
            options={'ordering': ('order', 'id'), 'verbose_name': '05. 회의록 카테고리', 'verbose_name_plural': '05. 회의록 카테고리'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': '14. 공지', 'verbose_name_plural': '14. 공지'},
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ('order', 'id'), 'verbose_name': '09. 업무 유형', 'verbose_name_plural': '09. 업무 유형'},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('project', 'id'), 'verbose_name': '07. 단계', 'verbose_name_plural': '07. 단계'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'verbose_name': '12. 업무 흐름', 'verbose_name_plural': '12. 업무 흐름'},
        ),
    ]
