# Generated by Django 6.0.5 on 2026-06-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0015_alter_activitylogentry_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeDocsCategory',
        ),
    ]
