# Generated by Django 6.0.5 on 2026-06-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_delete_codedocscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('1', '준비중'), ('2', '완료됨'), ('3', '취소됨')], default='1', max_length=1, verbose_name='회의 상태'),
        ),
    ]
