# Generated by Django 6.0.5 on 2026-06-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0017_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogentry',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='work.meeting', verbose_name='회의'),
        ),
        migrations.AlterField(
            model_name='activitylogentry',
            name='sort',
            field=models.CharField(choices=[('1', '업무'), ('2', '댓글'), ('3', '회의'), ('4', '공지'), ('5', '문서'), ('8', '글')], default='1', max_length=1, verbose_name='구분'),
        ),
    ]
