# Generated by Django 6.0.5 on 2026-06-06 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('docs', '0001_initial'),
        ('work', '0018_activitylogentry_meeting_alter_activitylogentry_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogentry',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.document', verbose_name='문서'),
        ),
        migrations.AddField(
            model_name='activitylogentry',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.post', verbose_name='게시글'),
        ),
        migrations.AlterField(
            model_name='activitylogentry',
            name='sort',
            field=models.CharField(choices=[('1', '업무'), ('2', '댓글'), ('3', '회의'), ('4', '공지'), ('5', '문서'), ('6', '글')], default='1', max_length=1, verbose_name='구분'),
        ),
    ]
