# Generated by Django 6.0.1 on 2026-01-16 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_companyaccount_is_transfer_fee_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectincbudget',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.projectaccount', verbose_name='계정'),
        ),
        migrations.AddField(
            model_name='projectoutbudget',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.projectaccount', verbose_name='계정'),
        ),
    ]
