# Generated by Django 6.0.7 on 2026-07-13 15:41

import _utils.file_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectincbudget',
            options={'ordering': ('-project', 'id'), 'verbose_name': '02. 현장 수입예산', 'verbose_name_plural': '02. 현장 수입예산'},
        ),
        migrations.AlterField(
            model_name='project',
            name='area_usage',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='용도지역지구'),
        ),
        migrations.AlterField(
            model_name='project',
            name='build_size',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='건축규모'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_year',
            field=models.PositiveSmallIntegerField(verbose_name='사업개시년도'),
        ),
        migrations.AlterField(
            model_name='sitecontract',
            name='remain_pay',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='잔금'),
        ),
        migrations.AlterField(
            model_name='sitecontractfile',
            name='file',
            field=models.FileField(max_length=255, upload_to=_utils.file_upload.get_site_file_path, verbose_name='파일경로'),
        ),
        migrations.AlterField(
            model_name='siteownerconsultationlogs',
            name='follow_up_note',
            field=models.TextField(blank=True, default='', verbose_name='후속조치 내용'),
        ),
    ]
