# Generated by Django 6.0.6 on 2026-07-08 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('work', '0004_rename_sort_issueproject_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='issue_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='work.issueproject', verbose_name='업무 프로젝트'),
        ),
    ]
