# Generated by Django 6.1.1 on 2026-09-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-start_year', 'id'], 'verbose_name': '01. 프로젝트', 'verbose_name_plural': '01. 프로젝트'},
        ),
        migrations.AlterModelOptions(
            name='projectincbudget',
            options={'ordering': ('-project', 'id'), 'verbose_name': '02. 프로젝트 수입예산', 'verbose_name_plural': '02. 프로젝트 수입예산'},
        ),
        migrations.AlterModelOptions(
            name='projectoutbudget',
            options={'ordering': ('order', 'id', '-project'), 'verbose_name': '03. 프로젝트 지출예산', 'verbose_name_plural': '03. 프로젝트 지출예산'},
        ),
    ]
