# Generated by Django 6.0.1 on 2026-01-16 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibs', '0001_initial'),
        ('project', '0003_alter_projectincbudget_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectincbudget',
            name='account_d2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.projectaccountd2', verbose_name='대분류'),
        ),
        migrations.AlterField(
            model_name='projectincbudget',
            name='account_d3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.projectaccountd3', verbose_name='소분류'),
        ),
        migrations.AlterField(
            model_name='projectoutbudget',
            name='account_d2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ibs.projectaccountd2', verbose_name='대분류'),
        ),
    ]
