{{- if .Values.enabled }}
{{- if not .Values.auth.existingSecret }}
{{- $postgresPassword := .Values.auth.postgresPassword }}
{{- $userPassword := .Values.auth.password }}
{{- if .Values.global }}
{{- if .Values.global.dbPassword }}
{{- $postgresPassword = .Values.global.dbPassword }}
{{- $userPassword = .Values.global.dbPassword }}
{{- end }}
{{- end }}
---
# Superuser (postgres) credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpg.fullname" . }}-superuser
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cnpg.labels" . | nindent 4 }}
    cnpg.io/reload: "true"
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ required "A valid password is required (auth.postgresPassword or global.dbPassword)!" $postgresPassword | quote }}

---
# Application user credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpg.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cnpg.labels" . | nindent 4 }}
    cnpg.io/reload: "true"
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ include "cnpg.username" . | quote }}
  password: {{ required "A valid password is required (auth.password or global.dbPassword)!" $userPassword | quote }}
  {{- if .Values.auth.database }}
  dbname: {{ include "cnpg.database" . | quote }}
  {{- end }}
{{- end }}

{{- if and .Values.backup.enabled .Values.backup.s3.enabled }}
---
# S3 backup credentials (if enabled)
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cnpg.fullname" . }}-backup-s3
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cnpg.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  ACCESS_KEY_ID: {{ .Values.backup.s3.accessKeyId | default "" | quote }}
  ACCESS_SECRET_KEY: {{ .Values.backup.s3.secretAccessKey | default "" | quote }}
{{- end }}
{{- end }}
