# Generated by Django 6.0.7 on 2026-07-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLink',
        ),
    ]
