# Generated by Django 6.0.6 on 2026-06-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_notice', '-created'], 'verbose_name': '03. 게시물 관리', 'verbose_name_plural': '03. 게시물 관리'},
        ),
    ]
