# Generated by Django 6.1 on 2026-08-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='is_manager_only',
            field=models.BooleanField(default=False, help_text='체크 시 해당 포럼의 manager 또는 최고관리자만 작성 가능', verbose_name='게시판 관리자 전용'),
        ),
    ]
