# Generated by Django 6.1 on 2026-08-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_postcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='manager_only',
            field=models.BooleanField(default=False, help_text='체크 시 해당 포럼의 manager 또는 최고관리자만 글 작성/수정 가능', verbose_name='관리자 전용 게시판'),
        ),
    ]
