# Generated by Django 6.1 on 2026-08-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_forum_manager_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_faq',
            field=models.BooleanField(default=False, help_text='체크 시 FAQ 아카이브/아코디언에 노출', verbose_name='FAQ 지정'),
        ),
    ]
