# Generated by Django 6.1 on 2026-08-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_post_is_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'ordering': ['-is_manager_only', 'id'], 'verbose_name': '02. 카테고리 관리', 'verbose_name_plural': '02. 카테고리 관리'},
        ),
    ]
