apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod # name of clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@dyibs.com # Let's Encrypt account email
    privateKeySecretRef:
      name: letsencrypt-prod  # name of clusterissuer
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
