name: Django Update [Dev]

on:
  push:
    paths:
      - "app/django/**"
      - ".github/workflows/django_dev.yml"
    branches: [ "develop" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# job은 사용자가 정한 플랫폼을 통해 steps 라는 일련의 과정을 실행.
# 여러 개의 job 을 사용할 수 있으며, 여러 개의 job 을 사용할 때는 서로 정보도 교환 가능.
# 각각 독립적으로도 실행 가능.
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # 레파지터리 체크 아웃
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          ref: 'develop'

      # Source Django to server copy transfer
      - name: Copy django, etc data to NFS server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CICD_HOST }}
          username: ${{ secrets.CICD_USER }}
          password: ${{ secrets.CICD_PASS }}
          source: 'app/django'
          target: ${{ secrets.CICD_PATH }}/dev/
      
      # web pod --> django model migrations & collectstatic
      - name: Django collectstatic & model migration & fetch_commits
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.CICD_HOST }}
          username: ${{ secrets.CICD_USER }}
          password: ${{ secrets.CICD_PASS }}
          command: |
            web_pod=$(kubectl get pod -n ibs-dev | grep web | cut -d ' ' -f1)
            kubectl exec -n ibs-dev $web_pod -- python manage.py collectstatic --no-input
            kubectl exec -n ibs-dev $web_pod -- python manage.py makemigrations accounts board book cash company contract docs ibs items notice payment project work --noinput
            kubectl exec -n ibs-dev $web_pod -- python manage.py migrate
            kubectl exec -n ibs-dev $web_pod -- python manage.py fetch_commits
      
      # slack --> notification
      - name: Send slack when failed
        if: ${{ failure() }}                    # 실패했을 때 실행
        uses: ./.github/actions/slack-notify    # 직접 '만든' Action이므로 uses 키워드를 이용해서 아래 경로를 입력해줍니다.
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
      
      - name: Send slack if completed
        if: ${{ success() }}                    # 성공할 때만 실행
        uses: ./.github/actions/slack-notify
        with:
          status: success   # status input은 받는 쪽에서 default 값을 정해놨기 때문에 success일 때만 전달.
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
