name: Svelte Update [Dev]

on:
  push:
    paths:
      - "app/svelte/**"
      - ".github/workflows/svelte_dev.yml"
    branches: [ "develop" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# job은 사용자가 정한 플랫폼을 통해 steps 라는 일련의 과정을 실행.
# 여러 개의 job 을 사용할 수 있으며, 여러 개의 job 을 사용할 때는 서로 정보도 교환 가능.
# 각각 독립적으로도 실행 가능.
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      # 레파지터리 체크 아웃
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          ref: 'develop'
      
      # Node.js 사용
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      
      # pnpm use
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false
      
      # node_modules 캐싱
      - name: Cache svelte node
        uses: actions/cache@v3
        id: cache_svelte
        with:
          path: ./app/svelte/node_modules
          key: pnpm-packages-${{ hashFiles('**/pnpm-lock.yaml') }}
      
      # node_modules 변화기 있으면 빌드
      - name: Install Dependencies
        if: steps.cache_svelte.outputs.cache-hit != 'true'
        run: cd app/svelte && pnpm i
      
      - run: cd app/svelte && pnpm build
        if: ${{ always() }}
      
      # Source to NFS server copy transfer
      - name: Copy Svelte -> django static/dist (NFS server)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NFS_HOST }}
          username: ${{ secrets.NFS_USER }}
          password: ${{ secrets.NFS_PASS }}
          source: 'app/django/static/**'
          target: ${{ secrets.NFS_PATH }}/dev/static/
      
      # slack --> notification
      - name: Send slack when failed
        if: ${{ failure() }}                    # 실패했을 때 실행
        uses: ./.github/actions/slack-notify    # 직접 '만든' Action이므로 uses 키워드를 이용해서 아래 경로를 입력해줍니다.
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
      
      - name: Send slack if completed
        if: ${{ success() }}                    # 성공할 때만 실행
        uses: ./.github/actions/slack-notify
        with:
          status: success   # status input은 받는 쪽에서 default 값을 정해놨기 때문에 success일 때만 전달.
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
